### ISSUE TITLE
Add Image in check box text in multi select dropdown?

### ISSUE THREAD

**Issue by brijeshgupta** [ehynds/jquery-ui-multiselect-widget#119]
Hi,

How can I add image in multi select drop down with check box text ?

I am using this code 

$(function(){
    $("select").multiselect({
   selectedList: 4 // 0-based index
    });
});

<select title="Basic example" multiple="multiple" name="example-basic[]" size="5">
    <option value="option1" iconurl="big-flower.gif">Option 1</option>
    <option value="option2" iconurl="icon1.png">Option 2</option>
    <option value="option3" iconurl="icon1.png">Option 3</option>
    <option value="option4" iconurl="icon1.png">Option 4</option>
</select>

Thanks
Brijesh Gupta

**Comment by mlh758** [comment]
This feature is now supported. If you want an image add a `data-image-src` attribute with the path/link to the desired image on any options that should have an image next to the checkbox.
