### ISSUE TITLE
Displayed selection is incorrect (and highlights are broked)

### ISSUE THREAD

**Issue by tabarjack** [ehynds/jquery-ui-multiselect-widget#145]
Latest versions (as of sept. 12th) of Jquery, JQuery (UI & Widget) & v1.11
After refreshing a list following a delete, the actual chosen item is not displayed properly and highlights no longer works.

Create a single select combo box:

Select one
Option1
Option2
Option3

When choosing option1 - Delete the Select One option
Call the refresh ($("select#sel_province").multiselect("refresh");) method
Look in menu, nothing is selected.
Select option3
Option1 is still the selected option
Nothing is highlighted in the dropdown.

**Comment by mlh758** [comment]
This no longer seems to be applicable.
