### ISSUE TITLE
Single select mode - prevent option from being selected default

### ISSUE THREAD

**Issue by sirrocco** [ehynds/jquery-ui-multiselect-widget#147]
Hi,

Any way to make the browser not select the first option when in "Single select" mode ? And instead display noneSelectedText ?

Thank you

**Comment by nipunbhardwaj29** [comment]
How Can we deselect the value selected in case of jquery mulitselect single select. Amy Idea? Suppose I clicked one of the option from drodown but behaviour of dropdown is that it can be leave empty, so how can I remove the selection by clicking somewheere?
