### ISSUE TITLE
Height issue

### ISSUE THREAD

**Issue by pysis** [ehynds/jquery-ui-multiselect-widget#153]
Some select box have only 3 item but the height defaults to 5-6 item even if there are less no of item. Thus it's having a empty spaces Is this a issue or i can fix it myself. I tried auto but for long select boxes it takes the all the items

**Comment by mlh758** [comment]
This has been added in a [recent commit](https://github.com/ehynds/jquery-ui-multiselect-widget/commit/58c7c343268d44c7720dffba3c05a6efbfc4385a).
