### ISSUE TITLE
Text wrapping in IE 6+7

### ISSUE THREAD

**Issue by ScottGuymer** [ehynds/jquery-ui-multiselect-widget#155]
Hi

Not 100% if this is something im doing wrong so here we go.

i have a multiselect and i want to see a list of all the options that have been selected not just a "x of xx".

This works fine on Chrome and i get a nice list and re widget resizes to accomodate.

however in IE the text doesnt wrap and simply disappears off the right hand side of the widget and is hidden.

Is this a "feature" of ie or something im missing?

**Comment by mlh758** [comment]
I'm going to close this due to the age.
