### ISSUE TITLE
multiselectfilter plugin ignores optgroup labels

### ISSUE THREAD

**Issue by poeboy** [ehynds/jquery-ui-multiselect-widget#163]
The filter plugin ignores optgroup labels.  If a user types in the group label, I would expect all the items in that group to show up in the filtered results.

**Comment by luizsgpetri** [comment]
Me too

**Comment by luizsgpetri** [comment]
I was able to fix this issue, I'll add the PR link here once created.

**Comment by luizsgpetri** [comment]
Fix: https://github.com/ehynds/jquery-ui-multiselect-widget/pull/605
