### ISSUE TITLE
Clicking inside dropdown menu steals ESC key

### ISSUE THREAD

**Issue by poeboy** [ehynds/jquery-ui-multiselect-widget#165]
1)  Open the dropdown.  Press ESC.  Dropdown closes.

2)  Open the dropdown.  Click inside dropdown menu in a way that causes the dropdown to still stay open (easiest method is to click somewhere on the header).  Press ESC.  Nothing happens.

**Comment by mlh758** [comment]
This has been fully fixed in a [recent commit](https://github.com/ehynds/jquery-ui-multiselect-widget/commit/fd787242943090db121748f2a416091a1fdc4d09).
