### ISSUE TITLE
multiselect needs control positioning options

### ISSUE THREAD

**Issue by poeboy** [ehynds/jquery-ui-multiselect-widget#167]
I personally find it rather awkward to have the controls (e.g. "Check All") immediately above the entries in the dropdown but right below the current selection.  There should be options to specify where the controls are positioned in relation to the relevant elements on the page.  Possible options should include:  Top of dropdown (default), bottom of dropdown, or attached to top/right/bottom/left of triggering element.

**Comment by mlh758** [comment]
This is complex enough and a limited enough use case that I won't be adding it.
