### ISSUE TITLE
'multiple : false' weird UI problem with optgroups

### ISSUE THREAD

**Issue by poeboy** [ehynds/jquery-ui-multiselect-widget#168]
I realize that this is primarily for multiselect dropdowns but since you offer the ability to use it as a single select dropdown, there are some weird UI issues that crop up as a result.  When clicking an 'optgroup' header, the last item in the optgroup is selected.  The correct behavior should be to ignore all clicks on optgroup headers.

**Comment by mlh758** [comment]
This has been fixed in a recent release.
