### ISSUE TITLE
filter header has issue when multiple select on same line autoOpen: true

### ISSUE THREAD

**Issue by Guilaume** [ehynds/jquery-ui-multiselect-widget#178]
Filter header has issue when multiple select on same line
and auto open is set to true

the second multiselect header has a strange alignement

if seletc are open after, the alignement is good

**\* BASIC TEST CASE build from demo\filter.htm ********************

<p>
    &nbsp;</p>

<p>
    &lt;form style=&quot;margin:20px 0&quot;&gt;&nbsp;</p>

<p>
    &lt;p&gt;<br />
    &lt;select multiple=&quot;multiple&quot; size=&quot;5&quot; style=&quot;width:370px&quot;&gt;&nbsp;<br />
    &lt;option value=&quot;red&quot;&gt;Red&lt;/option&gt;&nbsp;<br />
    &lt;option value=&quot;green&quot;&gt;Green&lt;/option&gt;<br />
    &lt;option value=&quot;blue&quot;&gt;Blue&lt;/option&gt;&nbsp;<br />
    &lt;option value=&quot;orange&quot;&gt;Orange&lt;/option&gt;&nbsp;<br />
    &lt;option value=&quot;purple&quot;&gt;Purple&lt;/option&gt;&nbsp;<br />
    &lt;option value=&quot;yellow&quot;&gt;Yellow&lt;/option&gt;<br />
    &lt;option value=&quot;brown&quot;&gt;Brown&lt;/option&gt;<br />
    &lt;option value=&quot;black&quot;&gt;Black&lt;/option&gt;&lt;/select&gt;</p>

<p>
    &lt;!-- same select duplicate --&gt;</p>

<p>
    &lt;select multiple=&quot;multiple&quot; size=&quot;5&quot; style=&quot;width:370px&quot;&gt;&nbsp;<br />
    &lt;option value=&quot;red&quot;&gt;Red&lt;/option&gt;&nbsp;<br />
    &lt;option value=&quot;green&quot;&gt;Green&lt;/option&gt;<br />
    &lt;option value=&quot;blue&quot;&gt;Blue&lt;/option&gt;&nbsp;<br />
    &lt;option value=&quot;orange&quot;&gt;Orange&lt;/option&gt;&nbsp;<br />
    &lt;option value=&quot;purple&quot;&gt;Purple&lt;/option&gt;&nbsp;<br />
    &lt;option value=&quot;yellow&quot;&gt;Yellow&lt;/option&gt;<br />
    &lt;option value=&quot;brown&quot;&gt;Brown&lt;/option&gt;<br />
    &lt;option value=&quot;black&quot;&gt;Black&lt;/option&gt;&lt;/select&gt;</p>

<p>
    &lt;/p&gt;<br />
    &lt;/form&gt;</p>

<p>
    &lt;script type=&quot;text/javascript&quot;&gt;<br />
    $(&quot;select&quot;).multiselect({<br />
    &nbsp;&nbsp; &nbsp;<br />
    &nbsp;&nbsp; autoOpen: true<br />
    }).multiselectfilter();<br />
    <br />
    $(&quot;select&quot;).bind(&quot;multiselectbeforeclose&quot;, function(event, ui){<br />
    &nbsp;&nbsp; &nbsp;return false;<br />
    });<br />
    <br />
    &lt;/script&gt;</p>

**\* BASIC TEST CASE ********************

**Comment by mlh758** [comment]
This is no longer an issue.
