### ISSUE TITLE
Add support for knockout

### ISSUE THREAD

**Issue by darkroastjava** [ehynds/jquery-ui-multiselect-widget#190]
It should be possible to data-bind the multiselect widget by adding the knockout data-bind attributes to the <select> tag in the HTML. Since the select tag is hidden and replaced by the widget, the data-bind attributes have no visible effect.

There is a very simple way to work around this: http://darkroastjava.wordpress.com/2011/11/17/using-eric-hynds-multiselect-with-knockout/

But you may want to adapt the implementation of the widget such that it automatically updates the UI whenever a change to the underlying <select> is made (that is, if an option is added or removed, and if an option is selected or cleared). This way all knockout bindings on the underlying <select> tag would also work for the widget.

**Comment by mlh758** [comment]
The `refresh` method would refresh the widget for you.

We are also now copying any `data-` attributes from the options into the widget.
