### ISSUE TITLE
Ui tabs and width bug

### ISSUE THREAD

**Issue by mrpamacs** [ehynds/jquery-ui-multiselect-widget#194]
Hi 

When I use the multiselect to the second " Jquery Ui" tab, the multiselect width is wrong on the second tab.
Why?

Example (http://jsfiddle.net/gFCFF/)

Code:
Html:

<div id="my_tab"  class="tabs">        
        <ul>
            <li><a href="#my_1"><span>asdasdasd</span></a></li>
            <li><a href="#my_2"><span>cvbcvbcvb</span></a></li>
        </ul>
        <div id="my_1">
        <select name="test" style="width: 100px" multiple>
            <option>Select one</option>
            <option value="foo">foo</option>
            <option value="bar">bar</option>
            <option value="baz">baz</option>
        </select>         
        </div>

```
    <div id="my_2" class="tabs">

                <select name="test" multiple>
                    <option>Select one</option>
                    <option value="foo">foo</option>
                    <option value="bar">bar</option>
                    <option value="baz">baz</option>
                </select>

    </div>
</div>
```

Js:
$.ech.multiselect.prototype.options.minWidth = "auto";

$(document).ready(function() {
    $(".tabs").tabs({});
});

$("select").multiselect();

**Comment by mlh758** [comment]
The width won't calculate correctly on hidden elements. You should create the widgets when the user first navigates to that tab rather than on page load.
