### ISSUE TITLE
Internet Explorer scrolls on mouseover of last element

### ISSUE THREAD

**Issue by btjake** [ehynds/jquery-ui-multiselect-widget#195]
In Internet Explorer, when the mouse is passed over an element in the drop down list that is just barely visible, the element is scrolled in to view.

As far as I can tell from looking at the code, the reason this happens is because the input element is focused in this segment of code:

```
        .delegate('label', 'mouseenter.multiselect', function(){
            if( !$(this).hasClass('ui-state-disabled') ){
                self.labels.removeClass('ui-state-hover');
                $(this).addClass('ui-state-hover').find('input').focus();
            }
        })
```

commenting out that section causes the keyboard input to not work correctly so I assume it's a necessary evil; however, it's very annoying and bad for usability. 

If you know of any way to avoid this or can fix it, that would be great. Please don't hesitate to contact me if you want any more info on the bug.

Thanks!

**Comment by SteveTheTechie** [comment]
@mlh758 This is a bit old.  If the issue cannot be confirmed w/ new code, this should be closed.

**Comment by SteveTheTechie** [comment]
@mlh758 This should have auto-closed, but did not.
