### ISSUE TITLE
hover state css not working ie6

### ISSUE THREAD

**Issue by harisel** [ehynds/jquery-ui-multiselect-widget#198]
Hi!,

First of all thanks for your wonderfull plugin. I found some problem with the css of the hover state of the option list. What i can't understand is that the first option, and only the first, doesn't take the background color and the border color like the other options. I tried the demos with IETester, and the issue shows for all the configurations (i tried single.htm & basic.html examples). Any idea?

**Comment by mlh758** [comment]
Not supporting IE6 at this time.
