### ISSUE TITLE
jquery ui multiselect plugin does not let me drag drop consistently

### ISSUE THREAD

**Issue by chugh97** [ehynds/jquery-ui-multiselect-widget#213]
I am using jQuery ui.multiselect.js plugin to order columns in my jqGrid. I have noticed that there are some inconsistencies in the way this plugin behaves. It lets me drag-n-drop from right column to left but not left to right column. Has anyone got a working solution to this problem.

**Comment by mlh758** [comment]
I realize this is extremely old, but what can't you drag and drop? The button for the multiselect widget?
