### ISSUE TITLE
Can't click when multiselect is embedded in a jquery Dialog, on Firefox only

### ISSUE THREAD

**Issue by donino** [ehynds/jquery-ui-multiselect-widget#214]
I embed multiselect widgets in a Jquery UI dialog, It works fine on any browser except Firefox (tested with Chrome, IE, Safari, opera). 

I tried with multiselect 1.11 and 1.12,  jquery UI 1.8.13 and Firefox 7&9 : the multiselect widget is displayed correctly, the highligths work as expected on mouseover but i can't click on the items.  The only clickable things are the "Check all" and "Uncheck all"  options, but all the items & checkboxes cannot be selected neither by  by a click, neither by keyboard actions. 

And if the same widgets are displayed outside the Dialog, then it works fine even with firefox. 

I don't get any single error in firebug. Anyone else got this issue? Your multiselect in Dialogs  work correctly with firefox?
Please  help me to investigate

**Comment by akm6270** [comment]
Multiple dropdowns on a single page... how can we not let more than one box toggle at a time? Multiselect issue

selectTitle.click(function () {
            select_state = (select_state) ? false : true;
            selectContent.toggleClass('collapsed');
        });
