### ISSUE TITLE
Accents marks in filter search.

### ISSUE THREAD

**Issue by fudre** [ehynds/jquery-ui-multiselect-widget#221]
Hi,

I am using the filter feature in spanish language, with our special characters (accents marks, ñ).
Spanish search engines (google.es, yahoo.es)  ignore the accents marks in a search. For example, if you search the word "estación" (with the accent mark in o), it shows the same result lisf than if you search without the accent mark in the o).

So I have the multiselect widget working in a list of words, some of them with accent marks. If you search the word without the accent mark, the filter do not show the options.

I propose to make the filter feature accent-insensitive or accent-sensitive with a configuration option. Maybe it will be usefull in other languages (french, german)

Thanks in advanced.

**Comment by mlh758** [comment]
I don't think this will end up being something we support out of the box. I'm not aware of a simple way to replace decorated letters with their plain equivalents or vice versa reliably across languages.
