### ISSUE TITLE
Can't click on menu entries in Chrome with multiple: false

### ISSUE THREAD

**Issue by bg** [ehynds/jquery-ui-multiselect-widget#224]
With multiple: false set, I can't click on menu entries with Chrome. With the default multiple: true I don't have this problem. Other browsers seem to work fine. The only way I can make selections is to use arrow keys and press enter, but this doesn't work in conjunction with multiselectfilter.

Versions:
- Multiselect 1.12
- jQuery 1.7.1
- jQueryUI 1.8.17
- Chrome 16, Debian sid/unstable
- Chrome 17, Windows XP

**Comment by mlh758** [comment]
I'm going to close this since it only seems to apply to older browsers we are no longer supporting.
