### ISSUE TITLE
Feature Request: Ability to Select/Unselect All/disable programatically for an opt group

### ISSUE THREAD

**Issue by bigcmos** [ehynds/jquery-ui-multiselect-widget#231]
```
<select multiselect id="foo">
 <optgroup value="bar">BAZ</optgroup>
 <optgroup value="x">y</optgroup>
 <optgroup value="a">b</optgroup>
 </select>
```

What I want to write is something like this:
<code>
    $('#foo').multiselect('checkAll', {optgroupNum=0}); // checks all options under "BAZ"
</code>

Nice to have:
<code>
$('#foo').multiselect('uncheckAll', {optgroupValue="x"}); // unchecks all options under "y"
$('#foo').multiselect('disable', {optgroupText="b"}); // checks all options under "b"
</code>

Code I currently have to write:
<code>
$($('#foo').multiselect('widget').find('li.ui-multiselect-optgroup-label')[0]).nextUntil('.ui-multiselect-optgroup-label').find(':checkbox').each(function(i, e) {
 if ($(this).attr('aria-selected')) {
  this.click();
 }
});
</code>

**Comment by vshekharjha** [comment]
you can hide by changing in css class 

.ui-multiselect-header { margin-bottom:3px; padding:3px 0 3px 1px; display:none;}

**Comment by mlh758** [comment]
In version 2.x of the widget, the option groups are built as `ul` tags so you can cut down the work by finding the right list and operating on all the children.

That said, it seems like it would be good to add this into the ongoing version 3 work.

**Comment by SteveTheTechie** [comment]
@mlh758  I think this can be done.  I am thinking that there would be an extra groupID parameter and its type would be checked (number or string) to determine the strategy used for finding the appropriate group.

**Comment by mlh758** [comment]
Yeah, I did something like that for the `addOption` method, although it just looks for the label.

It might be useful to add a method that takes a string/number and returns an option group that both `addOption` and this new method can leverage. That way their behavior is the same and one isn't limited to just labels.

**Comment by SteveTheTechie** [comment]
@mlh758 I now have this working as expected in my WIP code.

**Comment by SteveTheTechie** [comment]
@mlh758 For some reason, this did not automatically get closed w/ the merge.  (I did reference it in the PR.)  You can close this.
