### ISSUE TITLE
Validate Error message not getting removed 

### ISSUE THREAD

**Issue by vivekmyself** [ehynds/jquery-ui-multiselect-widget#250]
I tried to validate the your jQuery multiselect plugin using jquery.validate.js . Its working properly for validation, but its not removing the error message.

For example if it a required field. Without selecting any option when I tried to submit, it shows the error message 'This is required'.

The problem is when I select any options from the multiselect, the error message is not removed. Still its shows the error message. I tried using without the Jquery plugin its working properly.

How can I remove the error message in the above scenario.

Thank you

Vivek

**Comment by mlh758** [comment]
I'm going to close this one due to age.
