### ISSUE TITLE
multiselectfilter - optgroups hiding

### ISSUE THREAD

**Issue by kogaion** [ehynds/jquery-ui-multiselect-widget#251]
Hello Eric,

I found, while using the multiselect with the multiselectfilter option, a certain situation where the optgroups get hidden even if they shouldn't. 

For instance, if the multiselect is updated offline, using dom / specific js triggers, and if the multiselect is not open (visible), when calling the multiselect('refresh') method, the optgroups are hidden, due to the following code:

```
this.instance.menu.find(".ui-multiselect-optgroup-label").each(function(){
    var $this = $(this);
    $this![ $this.nextUntil('.ui-multiselect-optgroup-label').filter(':visible').length ? 'show' : 'hide' ]();
});
```

I believe that this action should be enclosed within a if (this.instance._isOpen) {..} clause.

Thanks.

**Comment by mlh758** [comment]
It looks like this was fixed after the issue was opened.
