### ISSUE TITLE
Google Chrome and scrolling

### ISSUE THREAD

**Issue by vtmoren** [ehynds/jquery-ui-multiselect-widget#255]
Have you ever seen an issue with Google Chrome  and scrolling?
I create using following code:

Main java script file:
...
        var select = Widgets.createSelect("#sample", "Select an option:", 1, false);
...

Widgets class:
...
        createSelect : function(elementId, noneSelectedText, selectedList, multiple) {
            var select = $(elementId).multiselect({
                multiple: multiple,
                noneSelectedText: noneSelectedText,
                selectedList: selectedList
            }).multiselectfilter();  
            return select;
        }, 
...

Multiple is set to false.
Whenever I scroll the plugin seems to get stuck attempting to display (like the refresh is failing).
I will try to add a picture if I can...

OS: Mac OSX 10.7.3
Google Chrome: 19.0.1084.46
jQuery: 1.6.2
jQueryUI: 1.8.16

**Comment by mlh758** [comment]
I'm closing this issue due to age and it seems to be resolved.
