### ISSUE TITLE
Doesn't work when an option value contains a doublequote character

### ISSUE THREAD

**Issue by atsushiba** [ehynds/jquery-ui-multiselect-widget#263]
Hi,

First of all, thank you for such a nice component. I like it.

I'm using it on one of our cusomers site and  encountered an issue entitled. 

I use jQuery MultiSelect UI Widget 1.12.

To fix this issue, I made the following change.

I hope it will help.

Thanks again,

toshiki

132c132
## &lt;                            value = this.value,

&gt;                            value = escapeHTML(this.value),
215a216
&gt;                            value=escapeHTML(value);
668c669,681
&lt; })(jQuery);
## \ No newline at end of file

&gt; })(jQuery);
&gt;
&gt; function escapeHTML(str) {
&gt;   return str.replace(/[&amp;&quot;&#039;&lt;&gt;]/g, function(c) {
&gt;     return {
&gt;       &quot;&amp;&quot;: &quot;&amp;amp;&quot;,
&gt;       &#039;&quot;&#039;: &quot;&amp;quot;&quot;,
&gt;       &quot;&#039;&quot;: &quot;&amp;apos;&quot;,
&gt;       &quot;&lt;&quot;: &quot;&amp;lt;&quot;,
&gt;       &quot;&gt;&quot;: &quot;&amp;gt;&quot;
&gt;     }[c];
&gt;   });
&gt; }

**Comment by mlh758** [comment]
We are no longer using string concatenation so this should be fixed.
