### ISSUE TITLE
jquery-ui-multiselect-widget Tab Key Support

### ISSUE THREAD

**Issue by nocarrier** [ehynds/jquery-ui-multiselect-widget#281]
Is there any support for a multiselect widget with a tab index and the ability for the widget to auto open on tab focus? 

Before I start to extend the plug in to support this, I was hoping you'd have some advice/feedback/input.

Thanks.

**Comment by mlh758** [comment]
We've made some improvements that have fixed keyboard navigation. When you highlight the button, spacebar will open the menu. Closing the menu (tab or escape) returns focus to the button so that the user can continue navigating the form.

**Comment by mlh758** [comment]
https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Keyboard-Navigation
