### ISSUE TITLE
Add checkbox to optgroup title

### ISSUE THREAD

**Issue by Drezdenozk** [ehynds/jquery-ui-multiselect-widget#284]
It's very nice, that we can toggle optgroup's checkboxes by click on optgroup title, but can we add checkbox to optgroup title? I  think i must added it on  jquery.multiselect.js

145
html += 
li a input type="checkbox" + optLabel + /a /li

it works, but on click that checbox does't change state..

**Comment by mlh758** [comment]
I'm going to close this in favor of adding a collapsible option. There is already a `cursor: pointer;` attribute for the label which should give enough indication that it can be clicked.
