### ISSUE TITLE
jQuery Validate 1.9 and Multiselect plugin Not Working for me.

### ISSUE THREAD

**Issue by Soupy** [ehynds/jquery-ui-multiselect-widget#285]
I'm trying to use the Validation plugin found here http://bassistance.de/jquery-plugins/jquery-plugin-validation/ in combination with this multiselect widget and am having no luck making it work.

I've tried searching this forum and the Validation forum and although several "solutions" appear, I can get none of them to work for me. I can make the Validation work fine with a normal multiple select control. However, once I "Multiselect" it using this plugin, I don't see my error message which is to have at least one option selected.

My markup looks something like this:

<pre>

<form id="myform">
<p>
   <label for="test2">Test:</label>
   <select class="test2" id="test2" name="test2" multiple="multiple" valid="required:true" title="Select at least one option" > 
      <option VALUE="F">One</option>
      <option VALUE="C">Two</option>
      <option VALUE="A">Three</option>
   </select>
</p>
</form>

</pre>

and the script is:

// multiselect the control
$("#test2").multiselect();

//validate the form
$.metadata.setType("attr", "valid");
$('#myform').validate(); 

When this is run, the multiselect look like it should (styled and dropdown with checkboxes etc.) but if I do not select any options, no error is shown. If I eliminate the call to the multiselect plugin, the error shows but it isn't styled like it should be.

Can someone please give me a working HTML snippet and script that would make these two plugins work correctly?

TIA

**Comment by luisferparra** [comment]
> Soupy - I'm pretty sure I know what's going on. The multi-select plug-in makes the fields hidden, and by default, the jquery.validate.js does not select hidden elements. This can be overridden with the "ignore" property when you call validate. Here is an example: $("#search").validate({ errorPlacement: function(error, element) { //This bit here is going to make sure the error label is placed after the button. var possibleButton = element.siblings("button"); if (possibleButton.length == 1) { element = possibleButton; } element.after(error); }, ignore: ".ignore", onfocusout : false, onkeyup : false, onclick : false }); You should be able to use that with any form, and it will validate everything including multi-selects!

Thanks dude. It works for me. thanks
