### ISSUE TITLE
focus() on filter field when opened

### ISSUE THREAD

**Issue by manovraresoft** [ehynds/jquery-ui-multiselect-widget#286]
Compared to a normal select box, this great plugin still has too many clicks necessary  for a keyboard user during data entry. This is frustrating for power users.

When you click on the select box, at the very least it should focus on the filter so that the user can begin typing to find results JUST like the intrinsic behavior of a select box.

I would create an "open" function, but have no idea how to access the generated element, the <input type='search'> as it has no unique identifier, and I can't access it using .children()  of  "#select1"  (because it is not the widget but instead the underlying element)
### Create 3 Select Boxes:

**1:**
&lt;select id='select1' name='select1&gt;
&lt;option value='1'&gt;1&lt;/option&gt;&lt;option value='2'&gt;2&lt;/option&gt;&lt;option value='3'&gt;3&lt;/option&gt;
&lt;/select&gt;

**2:**
&lt;select id='select2' name='select2&gt;
&lt;option value='1'&gt;1&lt;/option&gt;&lt;option value='2'&gt;2&lt;/option&gt;&lt;option value='3'&gt;3&lt;/option&gt;
&lt;/select&gt;

**3:**
&lt;select id='select3' name='select3&gt;
&lt;option value='1'&gt;1&lt;/option&gt;&lt;option value='2'&gt;2&lt;/option&gt;&lt;option value='3'&gt;3&lt;/option&gt;
&lt;/select&gt;

Instantiate Widget:

```

$(document).ready(function() {
    $("#select1").multiselect({
        multiple: false,
        header: "Select an option",
        noneSelectedText: "Select an Option",
        selectedList:1}).multiselectfilter();


    $("#select2").multiselect({
        multiple: false,
        header: "Select an option",
        noneSelectedText: "Select an Option",
        selectedList:1}).multiselectfilter();

    $("#select3").multiselect({
        multiple: false,
        header: "Select an option",
        noneSelectedText: "Select an Option",
        selectedList:1}).multiselectfilter();
    });
```

**Comment by mlh758** [comment]
The filter input is now focused when the menu is opened.

Additionally, hitting escape correctly closes the menu when the input is focused.

Hitting ALT-R will reset the text box so you don't have to mouse over to the reset button.

When the menu closes, the button is focused again which fixes tab ordering and navigation while tabbing.
