### ISSUE TITLE
Difficulty formatting height and width of multiselect box

### ISSUE THREAD

**Issue by ChayaCooper** [ehynds/jquery-ui-multiselect-widget#295]
I have 2 formatting questions regarding setting the height and width of the multiselect box, and after spending close to 24 hours on the jQuery Forum, I'm really hoping that you could tell me how I can adjust the code to get it to play well with everything else :-)

How do I remove/override everything that affects the margins and padding? In order for it to align with any other form input fields I need to create consistent inside padding amongst all my fields and not have any external margins, but even after removing everything from the css file as well as the default height and minWidth from the options it still has some padding inside the box and apx. 10% margin to the right of the box.

What can I adjust for the multiselect field to follow the dictates of the cell it's in instead of the table? The widget seems to be overriding the HTML and instead of the multiselect field being the width of the cell it equals the width of the table, so if the cell it's in is 28% of the table width and I want the box to be the width of the cell instead of saying width:100% I would need to set the multiselect field to equal 28%. I've designed all my forms with tables in order to easily align the fields and set their widths, and declare the width of the field to equal 100% of the cell <select style="width:100%"... and with hundreds of fields it would be far too cumbersome for me to have to reset each one individually.

**Comment by mlh758** [comment]
I'm closing this due to age and how many versions have come out since this was opened.
