### ISSUE TITLE
height should have a threshold for setting "auto" automatically

### ISSUE THREAD

**Issue by suit** [ehynds/jquery-ui-multiselect-widget#304]
if you have multiple lists with different item lenghts it chould get annoying to set each height manually to auto or a fixed value - so there should be a treshold for "height" to do this automatically

you already can do this with this little snippet - but that is not very clean:

```
$('select').each(function() {
    length = parseInt($('option',this).length);
    $(this).multiselect({
        height: ((length > 5) ? 175 : 'auto')
    });
})
```

another alternative is to set a maxheight and the height could be set in an "items length" since its a bit odd to define the height in pixels while you actually want to set it for a specific amout of items

this setting could also be read from the "size"-Attribute of the original select-Element

**Comment by mlh758** [comment]
The height option now behaves as a maximum height.

If the list of menu items is shorter than the height set in the height option the menu will shrink to fit those elements.
