### ISSUE TITLE
New option to impose a fixed width to the widget

### ISSUE THREAD

**Issue by stenda** [ehynds/jquery-ui-multiselect-widget#311]
Hi ,

first of all thank you for your great plugin! :)

I've a little improvement suggestion for you, namely an extra config option "width" (similar to the "height"  option) to impose a fixed width to the widget.

Also a maxWidth property could be great.

**Comment by Lukapt** [comment]
+ 1 on this. It would be great.

**Comment by mlh758** [comment]
In the changelog for 1.14:

> Added: menuWidth option to manually set the width of the menu

Is that the kind of option you were looking for?

**Comment by Lukapt** [comment]
Yes :) I was using 1.13. Thanks for the reply.

**Comment by mlh758** [comment]
I never noticed the confirmation. I'm going to go ahead and close this then!
