### ISSUE TITLE
Multiselect lose position when resizing window

### ISSUE THREAD

**Issue by pcarva** [ehynds/jquery-ui-multiselect-widget#319]
I have a problem when the screen is resize. And find out that en http://www.erichynds.com/jquery/jquery-ui-multiselect-widget/   is also happening.

See my screenshots to clarify the issue.
Before Maximized
http://www.freeimagehosting.net/oh51v

then after
http://www.freeimagehosting.net/gbdtg

Thanks!

**Comment by babarmashkoor** [comment]
Hi I am still getting the problem, can you share the code which will keep the opened multiselect remain in the position

**Comment by ClearlyEnergy** [comment]
Eric,
We switched away from using multiselect, not that it wasn¹t a great tool,
just other constraints came in the way.
Apologies,
Veronique


From:  babarmashkoor <notifications@github.com>
Reply-To:  ehynds/jquery-ui-multiselect-widget
<reply+001d591f3e3bc448a084de3a2dc9467992716fb71219844d92cf0000000110cd312a9
2a169ce00755f29@reply.github.com>
Date:  Tuesday, January 13, 2015 at 8:16 PM
To:  ehynds/jquery-ui-multiselect-widget
<jquery-ui-multiselect-widget@noreply.github.com>
Cc:  Veronique Bugnion <vbugnion@clearlyenergy.com>
Subject:  Re: [jquery-ui-multiselect-widget] Multiselect lose position when
resizing window (#319)


Hi I am still getting the problem, can you share the code which will keep
the opened multiselect remain in the position

‹
Reply to this email directly or view it on GitHub
<https://github.com/ehynds/jquery-ui-multiselect-widget/issues/319#issuecomm
ent-69801662> .

**Comment by babarmashkoor** [comment]
Thanks
Any other tool you recommend which provide same functionality like
multiselect?

we need dropdown list with checkboxes

On Tue, Jan 13, 2015 at 3:14 PM, ClearlyEnergy <notifications@github.com>
wrote:

> Eric,
> We switched away from using multiselect, not that it wasn¹t a great tool,
> just other constraints came in the way.
> Apologies,
> Veronique
>
>
> From: babarmashkoor <notifications@github.com>
> Reply-To: ehynds/jquery-ui-multiselect-widget
> <reply+001d591f3e3bc448a084de3a2dc9467992716fb71219844d92cf0000000110cd312a9
>
> 2a169ce00755f29@reply.github.com>
> Date: Tuesday, January 13, 2015 at 8:16 PM
> To: ehynds/jquery-ui-multiselect-widget
> <jquery-ui-multiselect-widget@noreply.github.com>
> Cc: Veronique Bugnion <vbugnion@clearlyenergy.com>
> Subject: Re: [jquery-ui-multiselect-widget] Multiselect lose position when
> resizing window (#319)
>
>
> Hi I am still getting the problem, can you share the code which will keep
> the opened multiselect remain in the position
>
> ‹
> Reply to this email directly or view it on GitHub
> <
> https://github.com/ehynds/jquery-ui-multiselect-widget/issues/319#issuecomm
> ent-69801662> .
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ehynds/jquery-ui-multiselect-widget/issues/319#issuecomment-69811412>
> .
>



-- 
Regards

Babar Mashkoor
Email: babarmashkoor@gmail.com

**Comment by scottmcconnell** [comment]
Yeah some code for context would be hugely appreciated. Thanks
