### ISSUE TITLE
Problem with jquery ui 1.9

### ISSUE THREAD

**Issue by mojtabajml** [ehynds/jquery-ui-multiselect-widget#320]
I upgrade my jquery ui and I have error in multiselect widget : 
TypeError: jQuery.easing[this.easing] is not a function
/js/jquery-1.8.2.js Line 8915

**Comment by gitdust** [comment]
i also have this problem!

**Comment by mlh758** [comment]
@gitdust What version of jQuery are you using?

**Comment by gitdust** [comment]
I'm pretty sure is v1.11.3

**Comment by mlh758** [comment]
When are you getting the error? Does this happen whenever you try to instantiate the widget, or in certain use conditions?

**Comment by gitdust** [comment]
problem sovled! I don't know why，I have try it again and it worked.

**Comment by mlh758** [comment]
Good news! Thank you for the update.
