### ISSUE TITLE
Allow pre rendered html

### ISSUE THREAD

**Issue by Shikyo** [ehynds/jquery-ui-multiselect-widget#340]
It takes time for the plugin the build the multiselect menu, for long lists (say 1000 items) this can take, especially in IE7, a considerable amount of time.

I just tested a list of 1600 items on a IE7 machine and the browser locked up for about ~5 minutes.

Also, because the plugin does must of the html sometimes you can see a dropdownlist being converted to a multiselect menu. This gives a bad user experience because the user can see the page flicker.

We tried pre rendering the html but the multiselect plugin ended up rendering the mutliselect menu a second time.

Right now we don't use the multiselect plugin on long lists and we have the plugin instantiation right below the html instead of in a document ready handler to counter the flickering effect.

I suggest a way for the plugin to see if the html is already pre rendered. Perhaps as an option or the plugin could check if certain elements exists.

**Comment by mlh758** [comment]
Not supporting IE7, but performance improvements have been made recently.
