### ISSUE TITLE
MultiSelect not visible at all in modal dialog [critical]

### ISSUE THREAD

**Issue by vivoices** [ehynds/jquery-ui-multiselect-widget#344]
jQuery 1.8.2, jQueryUI 1.9.1, CanJS 1.1.2

I would like to include MultiSelect in a modal dialog that is completely rendered as a documentFragment before inserted into the DOM.

Changing
[CODE] menu = . . .   .appendTo( document.body ) [CODE]
to
[CODE] menu = . . .   .appendTo( this.element[0].parentNode ) [CODE]
appends the menu <div> in a suitable position inside the documentFragment, so it gets removed when the dialog closes.

But the button does not get inserted neither into the DOM or the documentFragment after changing
[CODE] button = . . .  .insertAfter( el ) [CODE]
to
[CODE] button = . . .  .insertAfter( this.element[0] ) [CODE]

MultiSelect is broken in this situation.

**Comment by mlh758** [comment]
The appendTo option is available to allow placement of the widget HTML.
