### ISSUE TITLE
When I have select columns in the jqGrid use the widget, it never selects the correct value

### ISSUE THREAD

**Issue by jimshaw613** [ehynds/jquery-ui-multiselect-widget#357]
I have a jqGrid (actually the application has several) and I am trying to use the widget for any and all select (single and multiple) columns within the grid, for editting cells. In the jqGrid 'select' column definition we define the dataInit event to handle the 're-rendering' of the select control as the multi- select widget. Most of our 'select' columns are single select, although we have a couple as multiple select. The select columns also use the dataUrl method to get the data for the drop down.

The problem is when the drop down is shown, the option which is supposed to be selected is not, only the first item is highlighted. I believe the issue is due to when the mutliselect control is defined (in the dataInit event) the jqgrid code has not marked the selected element.

Here is the order of events within jqGrid...

1) Call dataUrl with info
2) On success:
         i) call buildSelect callback to generate select html (which we do implement)
         ii) append html to DOM element
         iii) call all bindable events for edit column options
                 - calls our dataInit callback function
                           where we 'extend' the select control ('elem' control in jqGrid code)
                           $(elem).multiselect(... multiple: false, ... );
         iiii) Make sure the correct option is selected.
                   - This is happening too late, I fear, or is not interpreted by the widget.

If anyone knows of a quick solution it would be appreciated. It will take some time to recreate this code in a sample js and html (as we have over 60 grids in our application, and they use a base grid helper class and functions to generate the appropriate code).

Ciao!
Jim Shaw

**Comment by mlh758** [comment]
Closing this due to age.
