### ISSUE TITLE
Is there a way to render MultiSelect elements with multiple columns/rows?

### ISSUE THREAD

**Issue by ChayaCooper** [ehynds/jquery-ui-multiselect-widget#362]
Is there a way to render multiselect elements with multiple columns/rows (similar to the way the gentleSelect plugin does)?  I have a few multiselect elements with large datasets (i.e. a list of sizes), and this would make it more manageable for the user. 

I'm not proficient enough in js to figure this out, but it looks like optgroup (possibly together with ._setButtonWidth and ._setMenuWidth) might be able to accommodate this.

I'm kind of partial to this widget so I'd rather not have to start using another plugin for a few elements. Plus it has more advanced functionality than gentleSelect does ;-)

**Comment by mlh758** [comment]
We've just added a `groupColumns` option, which you can find on the wiki that will allow for this behavior. The change is available in master.
