### ISSUE TITLE
Wrap Text of each Select Option

### ISSUE THREAD

**Issue by JoeGiunta** [ehynds/jquery-ui-multiselect-widget#365]
I can't seem to find this in previous threads, so I am posting new.

Is there a way to have the text of each Option wrap?  Some of the items in my select list are very short, others are very long.  The text is clipping in the very long items, see the screenshot below.

Thanks,
-- Joe --
![TextClipping](https://f.cloud.github.com/assets/3238818/58315/746c384a-5b6c-11e2-8982-4dcbce59b6a7.png)

**Comment by SteveTheTechie** [comment]
@mlh758  #744 addresses this ... wrapText option.

**Comment by mlh758** [comment]
Yup, closing.
