### ISSUE TITLE
Database Lookup On Filter

### ISSUE THREAD

**Issue by JoeGiunta** [ehynds/jquery-ui-multiselect-widget#368]
All,

Can anyone point me in the right direction on this.  I want to use the Filter functionality to not filter from the list of existing drop down option.  

I instead want to pirate that functionality to do a live look up against the database.  I'm guessing I would hijack the Filter event, but as I am fairly new to this control I am wondering if someone could at least give me a step in the right direction.

Thanks,
-- Joe --

**Comment by mlh758** [comment]
We won't be adding this to our widget. I think [autocomplete](https://jqueryui.com/autocomplete/) widget would be a better fit for this behavior.

It's an interesting idea though, might consider leaving that up as a fork of this repo.
