### ISSUE TITLE
Mousing over options steals focus from filter textbox

### ISSUE THREAD

**Issue by leo-the-manic** [ehynds/jquery-ui-multiselect-widget#375]
When using this widget in conjunction with the filter plugin, mousing over an option will steal focus from the filter text input.

To see it in action, go here: http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/#filter

Once on that page:
1. Click on either of the dropdown handles to bring up the full popup.
2. Type 'e' into the filter box
3. Mouse over one of the filtered options
4. Attempt to continue typing into the filter box

**Comment by mlh758** [comment]
I think this behavior is working as intended, however we've added some keyboard shortcuts which might be helpful to you.

You can now SHIFT-TAB back up to the header (and eventually the input)
If you type in some filter text and have your results filtered down to what you want, you can hit ALT-A to select all the visible options without having to leave the input.

ALT-R will clear the filter so you can search for other items.

ALT-L will jump from the filter to the list of check boxes.

Hopefully this mitigates the issue for you.
