### ISSUE TITLE
not able to change selected option index.

### ISSUE THREAD

**Issue by PratibhaSharma6982** [ehynds/jquery-ui-multiselect-widget#377]
after certain event how would i change selected option index to 0.

**Comment by jasonperrone** [comment]
Ehynds is this still true in the latest versions?

**Comment by mlh758** [comment]
What are you trying to achieve?

**Comment by jasonperrone** [comment]
Well, I haven't had time to dig into it, I will tomorrow. But at first glance, trying to pre-select checkboxes in JavaScript with $(element).val() and refreshing is not working since I upgraded from 1.13 to 2.0.1.

**Comment by mlh758** [comment]
I opened up the basic demo  from the repo and started assigning values like this:
`x.val(["option1", "option2"])`

and then:

`x.multiselect('refresh')`

and I'm seeing 2 selected.

**Comment by jasonperrone** [comment]
Ok, thanks Michael. I'm about to dig deeper to see what the problem is.

**Comment by mlh758** [comment]
What version of jQuery UI are you using?

**Comment by jasonperrone** [comment]
1.12.1

**Comment by jasonperrone** [comment]
Might be onto something. At the point in my code where the value is set and widget refreshed, it exists in the DOM, but not yet visible. I believe it's just nested in a container which is not visible, but it's definitely there, the element is retrieved by jQuery, I set the value and refresh, but by the time the element is set to visible, the values have unset. If in the console, I manually element.val(["24"]) and refresh it works. So, I am working on that angle right now.

**Comment by jasonperrone** [comment]
I figured it out Michael. It is a change in the multiselect widget.

If you have set values on the multi-select, and then call .multiselect({'multiple': true}) (or false I'm guessing), it unsets the values. 

I can be more diligent about this process but in the meantime, yeah, it does that now.

**Comment by mlh758** [comment]
This is done [deliberately](https://github.com/ehynds/jquery-ui-multiselect-widget/blob/master/src/jquery.multiselect.js#L940) when you change the status of the select from multiple to single select or vise versa.

If you have multiple values selected and go to single, there's no way of knowing which value is the one that should be kept. Going from single to multiple it could keep the one value, but the intent is changing so it doesn't necessarily make sense to maintain the values.

Do you have a need to dynamically change the widget from single to multiple? If not, you can just use the multiple option when you declare the widget.

**Comment by jasonperrone** [comment]
But I think in this case it went from multiple to multiple. Re-calling the initializer erases the values regardless of whether you're changing the type. 

I worked around it by simply holding onto the current values before calling the initializer, and the reapplying them afterwards. Problem solved.

I really appreciate your responses on this, Michael. Thank you and happy holidays!

**Comment by mlh758** [comment]
@jasonperrone I'm moving this conversation to #712 since this may be something different.
