### ISSUE TITLE
multiselect filter is not working for html encoded charecter like $,>,<

### ISSUE THREAD

**Issue by ddalapati** [ehynds/jquery-ui-multiselect-widget#388]
We need to html-encode the input text

_handler: function(e) {
            var term = $.trim(this.input[0].value.toLowerCase()),

**Comment by mlh758** [comment]
We are now using `text()` to set the values so this should work.

If you need custom rendering, see [here](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Customization).
