### ISSUE TITLE
Store checked items in a cookie

### ISSUE THREAD

**Issue by ghost** [ehynds/jquery-ui-multiselect-widget#393]
Hi, just wondering if it's possible to sort checked items in a cookie?

Using JSON.parse and localstore on _checked. Or any other way via jQuery cookies or Cookify, thanks

**Comment by mlh758** [comment]
Yeah, you could hook into one of the widget [events](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Events) and create a cookie using a JSON string with the list of selected items.

Use `$("select").val()` to get the list of selected values and store it.
