### ISSUE TITLE
What modifications are needed for jQueryUI 1.10.x & jQueryCore 1.9.x?

### ISSUE THREAD

**Issue by DawsonGreen** [ehynds/jquery-ui-multiselect-widget#394]
This question applies to both the core widget and the filter add on. I'm at a point where I really want to upgrade from UI 1.8 & Core 1.8, but I'm not sure what changes are necessary in the source code. What hot fixes have people had to make to get quick functionality for everything?

Please also note that I'll provide feedback on memory leaks I find with these hotfixes. My site is very sensitive to them, so I really want to avoid (or at least document) detached DOM elements or leaving javascript objects laying around.

Thanks to all who can help!

**Comment by mlh758** [comment]
I'm going to close this since there doesn't appear to be issues with newer versions of jQueryUI and regular jQuery.
