### ISSUE TITLE
Why add CSS "ui-state-hover" class to the first option on open ?

### ISSUE THREAD

**Issue by GxiGloN** [ehynds/jquery-ui-multiselect-widget#396]
Why apply the CSS class "ui-state-hover" to the first option of the multiselect on open ?
I think this is very disturbing for user because that make him feel that this one is selected :/

**Comment by mlh758** [comment]
The first element is focused automatically so that it is easier to navigate with a keyboard.

The exception being when the filter widget is applied, then the text box is focused instead.
