### ISSUE TITLE
Multiselect filter error on dialog

### ISSUE THREAD

**Issue by rasj** [ehynds/jquery-ui-multiselect-widget#397]
When modal param is true, the focus always goes to the first input and can't filter options...

jQuery v1.9.0 or v1.9.1
jQuery UI - v1.10.1

jsfiddle example:
http://jsfiddle.net/x3AQD/2/

**Comment by ThamizhmaniXCDSYS** [comment]
I sorted this problem by making z-index: 0 in my modal popup. 
 .dropdown-menu {
               z-index: 0;
    }
Thanks, @rasj 

NOTE: On parent page z-index not required.

**Comment by mlh758** [comment]
Updating to the 2.x version of the widget should also solve this since it's no longer relying on z-index in the css to end up at the front.
