### ISSUE TITLE
Keyboard selection

### ISSUE THREAD

**Issue by 2ge** [ehynds/jquery-ui-multiselect-widget#401]
Hi,

I implemented your widget, it is just great, 90% users like it. But there are 10% users, who don't like it, just because, they can not use just keyboard, as normal drop down select box. That means, they navigate to select element with <TAB> and then press a key, lets say "y" to select (and rotate) through selections which start on "y". It would be great to have this possibility and for example with <SPACE> selecting or deselecting the options.

I am also willing to donate if this will be implemented, I read other comments (on your blog and also here), and there are quite a few people looking forward to make this possible.

Thanks!

**Comment by mlh758** [comment]
The widget has been updated to substantially improve keyboard navigation.
