### ISSUE TITLE
MultiSelect

### ISSUE THREAD

**Issue by KevinMarete** [ehynds/jquery-ui-multiselect-widget#402]
Hi,
I need your help.
First I have used the multiselect-widget to display a dropdown list and in that list there is a checkbox for other.That if other is clicked it enables a textarea at the bottom which you can write any other choice but onchange that new written text is pushed to replace the value of the checkbox that is other.Hence my question how can i get all checked  values from this widget.I have tried the method getChecked but it is only returning the initial vlaue of other not the new value.Please Help.

**Comment by mlh758** [comment]
You should update the original select element the widget is built from, adding the selected attribute if you want it to be checked, and then call refresh.
