### ISSUE TITLE
multiselectfilter breaking check all / uncheckall

### ISSUE THREAD

**Issue by mbates** [ehynds/jquery-ui-multiselect-widget#404]
I had the multiselect working great, but when I added the multiselectfilter the check all and uncheck all stopped working properly. They would update the ui element, but not the original dom input element

I updated 1 line in the jquery file, here's the git diff output

--- a/cdn/js/jquery.multiselect.filter.js
+++ b/cdn/js/jquery.multiselect.filter.js
@@ -78,7 +78,7 @@
         // select option tags
         this.element.find('option').filter(function() {
           if(!this.disabled && $.inArray(this.value, values) > -1) {
--            _self._toggleState('selected', flag).call(this);
++            instance._toggleState('selected', flag).call(this);
           }
         });

that seems to have fixed the issue.

**Comment by mlh758** [comment]
The behavior now appears to be consistent between filter mode and regular.
