### ISSUE TITLE
Safari Mobile scrolling issue

### ISSUE THREAD

**Issue by ntierdevelopers** [ehynds/jquery-ui-multiselect-widget#406]
On iPad 2, on Safari mobile I'm not able to scroll within the list of items. I think it's not picking up the event because the items are in the way.

Have you had this issue? See screenshot. I can try to make a jsFiddle if needed. Thanks!

![multiselectissue](https://f.cloud.github.com/assets/3975181/303109/8803c996-961c-11e2-9b90-d8f286b3b697.png)

**Comment by SteveTheTechie** [comment]
@mlh758 I am pretty sure that this is not an issue anymore.  Reason:  I have hundreds of thousands of people all over the world that use my web application that incorporates this widget.   They use both iPads and Macs in addition to phones and Windows desktops. (a wide mix of devices and browsers)  If this was still an issue, I would have definitely heard about it by now.  (my users are vocal)

Therefore, I believe that this issue can be closed.

**Comment by mlh758** [comment]
Just tested it out using a phone emulator. Looks to be fine now.
