### ISSUE TITLE
How to attach functionality before uncheckAll is fired??

### ISSUE THREAD

**Issue by Alchemication** [ehynds/jquery-ui-multiselect-widget#410]
I would just like to check how many checkboxes is checked before uncheckall is fired, if I attach my method on uncheckAll - it fires after uncheck-all functionality and gives me 0 elements checked... Thanks

**Comment by mlh758** [comment]
There isn't an event for before uncheck/check all is fired. You could hook into the open event and store the number of checked items at that time though.
