### ISSUE TITLE
Cursor trap for keyboard-only users

### ISSUE THREAD

**Issue by webmagnetix** [ehynds/jquery-ui-multiselect-widget#411]
When using TAB to access select boxes, if a user uses Shift+TAB to reverse direction, the drop-down closes, and the cursor sticks to whatever option was previously selected.

Using the keyboard to select/deselect the option is still possible (one can see the number of options selected changing as the checkbox is toggled, even though it is no longer visible), but tabbing away from the drop-down is no longer possible. The mouse is the only way out.

Perhaps there's a way to detect when the drop-down closes, and to transport the cursor back to main select box object.

**Comment by mlh758** [comment]
The cursor trap has been fixed in a recent commit since the button is now focused when the menu is closed by tab/escape.
