### ISSUE TITLE
maxWidth option?

### ISSUE THREAD

**Issue by cce32** [ehynds/jquery-ui-multiselect-widget#412]
Hi,

I have select lists with CSS widths set to 100% constrained inside table cells so a large number of them are all the same width no matter how small or large their largest option is.

When multiselect converts them to input buttons they expand.

The only way I could get it to work with my layout was to add a maxWidth option to multiselect and if one is passed in don't use the .width(xx) but .css("width", xx) instead.
This way I can pass in maxWidth 100% and it get set on the button.

Maybe there is a better way, or maybe you would want to add this functionality?

Thanks for a great widget!

**Comment by SteveTheTechie** [comment]
PR #744 addresses this.

**Comment by SteveTheTechie** [comment]
@mlh758 I believe that PR #744 addresses this.  This could be closed.
