### ISSUE TITLE
field width bigger when opening select field

### ISSUE THREAD

**Issue by joujou** [ehynds/jquery-ui-multiselect-widget#418]
How could I change the width of the field only when it is opened ?
I want the field to be not too large when closed but I have long texts inside the select box that I want to be displayed on a long line when the selectbox is opened.
That's what happens with classic selectboxes.
Thanks

**Comment by mlh758** [comment]
There is a `menuWidth` [option](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Options) available that does exactly this.
