### ISSUE TITLE
with selectedlist option the ampersand "&" becomes &amp;

### ISSUE THREAD

**Issue by u-name** [ehynds/jquery-ui-multiselect-widget#424]
If I have an option in the multiselect list like "cats & dogs" 
in the selectedlist.htm demo than the character "&" (ampersand) becomes "amp;" if I select it!
?

**Comment by JPustkuchen** [comment]
Same problem here. Is there a possibility for a new release? Fix from above solved this.

**Comment by mlh758** [comment]
This has been resolved in the latest release of the code. If you would prefer not to use the latest version, the docs show how to override this behavior: https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Customization

This was a design decision to make the code safer by default: https://github.com/ehynds/jquery-ui-multiselect-widget/issues/229
