### ISSUE TITLE
Optionally hide 'Check all' and/or 'Uncheck all' header text

### ISSUE THREAD

**Issue by homme** [ehynds/jquery-ui-multiselect-widget#427]
There are cases where it would be useful to be able to hide the 'Check all' or 'Uncheck all' text in the header.  Setting the `checkAllText` or `uncheckAllText` options to one of `undefined`, `null`, `false` could be used to specify this when instantiating the multiselect.  This would hide both the text and associated ✔/✘ icons.

**Comment by vishnu777** [comment]
You can simply use the following method to hide the 'checkall' and 'uncheckall' link. 

$("#selContacts").multiselect({
                    	   beforeopen: function(){
							      $(".ui-multiselect-all").hide();
							      $(".ui-multiselect-none").hide();
							   },
			  open: function(){
							      $(".ui-multiselect-all").hide();
							      $(".ui-multiselect-none").hide();
							   },   
});

**Comment by homme** [comment]
@vishnu777 Thanks.  That approach looks like it should work well, and seeing as this issue appears to be a niche case I'll close it :)
