### ISSUE TITLE
_self is undefined when checking all options

### ISSUE THREAD

**Issue by johanalkstal** [ehynds/jquery-ui-multiselect-widget#431]
When clicking the option to check all items in the list,
I get an error that ```_self``` is undefined. Looking in jquery-multiselect-filter.js file I can't find any other references to ```_self```.

```javascript
// select option tags
this.element.find('option').filter(function() {
if(!this.disabled && $.inArray(this.value, values) > -1) {
_self._toggleState('selected', flag).call(this);
}
});
```

**Comment by mlh758** [comment]
This issue appears to have been resolved in the source code at this point.
