### ISSUE TITLE
JQuery multiselect drop down menu display over the header in IE browser

### ISSUE THREAD

**Issue by Naresh2255** [ehynds/jquery-ui-multiselect-widget#432]
Thanks for providing multiselect drop down widget.

I am using this widget in my project.  But these multiselect drop downs are created dynamically by using Java script dynamic table rows and cells.  When click on the drop down first time, the drop down menu positons are appearing over the header and some times somewhere on the form when the form size goes beyond its default size in the IE browser but not in Mozilla and Chrome.  But the second time onwards, it's appearing below the drop down button.  I am attaching screen shots herewith this post.

I have tried to fix it out but didn't get any luck.  

I have set the following poisiotion code when initializing the multiselect widget.
position: {
            my: 'right top', 
            at: 'right bottom' 
}

This code seem to be not working when clicking on the drop down first time.

Could you please help me out from this issue?

Thanks and regards,
Naresh

**Comment by mlh758** [comment]
We recently made improvements to the positioning of the widget which should resolve this issue.
