### ISSUE TITLE
optgrouptoggle not firing

### ISSUE THREAD

**Issue by MB34** [ehynds/jquery-ui-multiselect-widget#435]
Modified the example for displaying checked values elsewhere on the page:
"Show checked values on another part of my page?": http://jsfiddle.net/ehynds/rTjkr/
However, the optgrouptoggle event does not fire when bound.
http://jsfiddle.net/Mrbaseball34/F3QSV/

**Comment by mlh758** [comment]
The drop down closes properly in the newer versions.
