### ISSUE TITLE
Incorrect offset of "Enter Keywords" in filter module when zooming

### ISSUE THREAD

**Issue by jmhiller** [ehynds/jquery-ui-multiselect-widget#440]
1) Create multiselect with filter enabled
2) In the browser window, zoom to enlarge the page (on Mac/Chrome, command++ at least twice)
3) Open the multiselect, and you can see the "Enter Keywords" text is offset incorrectly (see attached image)

![Screen Shot 2013-04-24 at 10 29 30 AM](https://f.cloud.github.com/assets/1541751/421313/54d47868-ad05-11e2-82d2-8316b64df783.png)

**Comment by mlh758** [comment]
This appears to be theme and browser dependent. The placeholder text is controlled by the browser.
