### ISSUE TITLE
Pass separator string as option?

### ISSUE THREAD

**Issue by abennouna** [ehynds/jquery-ui-multiselect-widget#443]
Great plugin that I have just been able to use :-)

I happen to use it in a bi-directional app, and the comma currently used to separate the displayed checked (selected) values should adapt to the language.

The line 225 seems to be the one:
`value = $checked.map(function() { return $(this).next().html(); }).get().join(', ');`

To be as generic as possible, do you think it is possible to specify the separator as an option?

In the case I'm not clear: here's what the comma looks in Arabic:
`،`

So multiple selected values can be:
`قط، فأر`

which is Arabic for

`cat, dog`

**Comment by mlh758** [comment]
There is an option available for this: https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Options

`selectedListSeparator`
