### ISSUE TITLE
Width of the checkbox in a multiselect dropdown box.

### ISSUE THREAD

**Issue by abhideo1983** [ehynds/jquery-ui-multiselect-widget#446]
When I have the multiple option set to true, the multiselect dropdown displays a checkbox and the width of the text. How can I change the css or js code to make sure that the width of the checkbox isn't much.

![image](https://f.cloud.github.com/assets/4295354/440448/1713128a-b0fe-11e2-9c7b-f5249495cc29.png)

**Comment by mlh758** [comment]
You would be better off just doing the following:


```
jQuery.get('/Controller/GetAllCountries', function (data) {
    jQuery('#Country').empty();

    if (data.length > 0) {
        jQuery.each(data, function () {
            jQuery('#Country').append(jQuery("<option></option>").val(this['Value']).text(this['Text']));
        });
    } else {
        jQuery("#Country").empty().append('<option selected="selected" value="0">Not available<option>');
    }

     jQuery('#Country').multiselect({ selectedList: 4, minWidth: 200 });
});
```

`jQuery("select#Country")` is over-qualified, you are grabbing all the selects then filtering on that ID, looking up by just the ID would be faster.

There is no need to uncheck all or enable. If you create the widget after adding the options to the select then there is also no need to refresh. Calling uncheckAll would undo what you did in this line:

    jQuery("#Country").empty().append('<option selected="selected" value="0">Not available<option>');
