### ISSUE TITLE
Not using multiple attribute when initalizing

### ISSUE THREAD

**Issue by yehuda54** [ehynds/jquery-ui-multiselect-widget#447]
On some of my selects I have the multiple attribute set to multiple, while others I have set to non-multiple (single select).  I would expect when I initalize the multiselct, it should respect those attributes on the original select -- but it does not

I tried to grab it from the original, but it did not help:
$(".multi_select").multiselect({
    multiple: $(this).attr('multiple') == 'multiple',
});

Any suggestions?

**Comment by mlh758** [comment]
You aren't grabbing it from the original properly, if `$(this).attr('multiple') == 'multiple'` actually evaluated to a boolean it would work.
