### ISSUE TITLE
just a little issue when working in Single mode

### ISSUE THREAD

**Issue by ricardoafb3000** [ehynds/jquery-ui-multiselect-widget#449]
Hello,

I'm using this wonderful plugin to my select components, but in single mode. There's a little problem when it opens the popup to show the items the first item is always selected.

I've fixed the problem just setting a little code. In the jquery.multiselect.js file, about line 586, I set to refresh again the items:

...
// select the first not disabled option
// triggering both mouseover and mouseover because 1.4.2+ has a bug where triggering mouseover
// will actually trigger mouseenter.  the mouseenter trigger is there for when it's eventually fixed
this.labels.filter(':not(.ui-state-disabled)').eq(0).trigger('mouseover').trigger('mouseenter').find('input').trigger('focus');

[new command]
//refresh items
this.refresh(false);
...

I hope that this fix is going to be useful to you.

Great plugin.
Best regards,
Ricardo

**Comment by mlh758** [comment]
First item is no longer automatically selected when opening the widget, only focused on.
