### ISSUE TITLE
Add the possibility to define own filter rules

### ISSUE THREAD

**Issue by gityhuber** [ehynds/jquery-ui-multiselect-widget#454]
At the moment it is only possible to use the build in filter criteria. The used internal regex works as a 'contains' filter. But there can be usecases where a 'beginsWith' filter or other criterias are useful. Because of that there should be the possibility to define own filter rules.

**Comment by SteveTheTechie** [comment]
@mlh758 This sounds like a great idea.  However, there is a question about how this would actually be implemented in the UI.   If you have a regular select drop-down in the heading to pick the filter rule, would that seem a bit wonky?  (a normal select in the heading of an enhanced multi-select widget)  

If you put a simple checkbox labeled "Pattern" to the right of the filter box, that could work, but then you have to consider what would types of "patterns" would be understandable and usable by end users... probably not regular expressions.

I would suggest leaving this issue open until someone can suggest a creative UI approach for implementing this.  (I don't have an approach for this so I am ignoring it.)

**Comment by mlh758** [comment]
I don't think they meant in the UI. They probably meant as an option to the filter plugin.
