### ISSUE TITLE
Up key doesn't work - Fix suggestion

### ISSUE THREAD

**Issue by cjlack** [ehynds/jquery-ui-multiselect-widget#460]
Hi. Thanks for the multiselect, it was just what I was looking for. 

There is a bug with the up key though, it always moves to the first item. The fix is to change the following line in _traverse()...

<pre>
$next = $start.parent()[moveToLast ? 'prevAll' : 'nextAll']('li:not(.ui-multiselect-disabled, .ui-multiselect-optgroup-label)')[ moveToLast ? 'last' : 'first']();
</pre>

to...

<pre>
$next = $start.parent()[moveToLast ? 'prevAll' : 'nextAll']('li:not(.ui-multiselect-disabled, .ui-multiselect-optgroup-label)')['first']();
</pre>

**Comment by mlh758** [comment]
It looks like this is resolved in later versions of the widget.
