### ISSUE TITLE
Clone the MultiSelect

### ISSUE THREAD

**Issue by manigarg** [ehynds/jquery-ui-multiselect-widget#463]
Hello,

I do clone a multiselect element on the top and would like to have all the Elements UnSelected in the Cloned Element. However, the Drop down for the Cloned Element is not working. also the elements are staying selected as well. I tried to call refresh but it doesnt fire even.

Manish

**Comment by mlh758** [comment]
Cloning widgets is not supported in jQuery UI: https://bugs.jqueryui.com/ticket/3803
