### ISSUE TITLE
multi-select not refreshing properly on ie8

### ISSUE THREAD

**Issue by gekidoslair** [ehynds/jquery-ui-multiselect-widget#471]
Hello,

Trying to do an Ajax update of a select - the plugin en whole works great, browser support has been excellent, however I have one instance where I am doing an Ajax request to retrieve states by country and I can't seem to get the multiselect to refresh properly in IE8.

Select's in IE8 seem to be problematic at best in general, so I'm not 100% sure if it's related to how I'm populating the select or if it's just not refreshing properly.

The code in question basically does this:

if (http.readyState == 4)
    {
        var a = http.responseText;
        document.getElementById("states").innerHTML = a
    }

and then I call the multiselect 'refresh' function on the multiselect.

what happens is the select entry 'looks' like it has entries (you can see the dropdown / mouse over the entries), but none of the option text is being set - all of the entries in the select are blank basically.

Any thoughts?

**Comment by mlh758** [comment]
Not supporting IE8 anymore.
