### ISSUE TITLE
question: how can I get text using .map

### ISSUE THREAD

**Issue by Hokwang** [ehynds/jquery-ui-multiselect-widget#472]
hello.

I want to know value and text.
I can get value using below code, but I don't know text!.

Please help. 
<code>
var cq = $("#cq_select").multiselect("getChecked").map(function() {
                     return this.value;
              }).get();
</code>

**Comment by mlh758** [comment]
var cq [];
    $("#cq_select").multiselect("getChecked").each(function(idx, el) {
        cq.push($(el).next().text());
    });

That would give you a list of the labels that belong to checked elements.

`$("#cq_select").val()` would give you the values for all the checked elements in an array.
