### ISSUE TITLE
multiselect filter cannnot be selected inside dialog with modal: true

### ISSUE THREAD

**Issue by petia83** [ehynds/jquery-ui-multiselect-widget#474]
I'm using the the following jquery libraries:

jQuery v1.10.1
jQuery UI v1.10.3
jquery multiselect 1.13
filter addon
When i use the multiselect filter on any select, it works just find.
When i use the multiselect filter inside the Dialog UI with property "model:true" i cannot longer select to filter out the list - the placeholder of search, cannot be chosen.

Without the property modal:true, it works just fine.

I've tried to add the propery "appendTo: 'form'", but still having issues.

Edit: sample code http://jsfiddle.net/dQzxJ/3/

Any ideas?
Thanks,
Eddie

**Comment by NYPD** [comment]
Thank you so much @lordvacilaoerrocerto && @rd-here

**Comment by mlh758** [comment]
I guess I can probably close this issue then.

**Comment by alejoGaviria** [comment]
Thank you @rd-here  and  @lordvacilaoerrocerto  you have saved me a lot of time.
