### ISSUE TITLE
For ie 9.0 the Multiselect check box list is not working  as per mentioned in the link below

### ISSUE THREAD

**Issue by mvdatars13** [ehynds/jquery-ui-multiselect-widget#475]
Hi All,

For ie 9.0 the Multiselect check box list is not working  as per mentioned in the link below

http://forums.asp.net/t/1703902.aspx/1?JQuery+How+to+multiple+selectable+dropdown+list+

Please help ASAP. we required to develop on the IE 9.0

**Comment by mlh758** [comment]
We no longer support IE 9.
