### ISSUE TITLE
Change "X" on Filter Toolbar to "OK"

### ISSUE THREAD

**Issue by darkfeather** [ehynds/jquery-ui-multiselect-widget#477]
In our user testing, we've found users think clicking the "X" on the filter toolbar just closes the filter dropdown without saving the changes made to the filter. We're suggesting changing the "X" to "Ok" or adding "Ok" as an option in addition to the "X". We see this functionality being added to the Options parameters. We'd be willing to work on the code if you would be willing to accept it and commit the changes. Please let us know if you will make these changes or are willing to commit any work we do.

Thanks!

**Comment by mlh758** [comment]
The "X" on the filter search has become pretty standard. At this point it should stay as is.
