### ISSUE TITLE
Option values are also being displayed as tooltips when using jquery tooltips

### ISSUE THREAD

**Issue by robz1330** [ehynds/jquery-ui-multiselect-widget#482]
I'm using the multiselect widget as well as the jquery UI tooltip widget, and I am having the same problem as in issue #324. However, the difference is that I _want_ to display a tooltip  within the multiselect widget when the user hovers over each item within the widget while it is open.

This actually is working fine already, except, I end up seeing TWO tooltips for each item: one is part of the "title" attribute that I have defined, and the other is the option value of the item, as referenced in issue 324.

I'd like to display only the tooltip for the title attribute, and not the option value.

**Comment by mlh758** [comment]
We have since removed the title attribute being the value of the option. The title shown in the tooltip is pulled from the title attribute of the option. This issue should be resolved.
