### ISSUE TITLE
multiselect widget not working properly within a fixed topbar (jsFiddle example provided)

### ISSUE THREAD

**Issue by natorojr** [ehynds/jquery-ui-multiselect-widget#484]
Greetings,

I cannot get the multiselect widget to work properly within a fixed div (topbar). I've provided an example of what I mean on jsFiddle: http://jsfiddle.net/natorojr/w24QR/

To reproduce, please take the following steps:

(1) Load http://jsfiddle.net/natorojr/w24QR/
(2) Click on the multiselect widget (either one)
(3) Scroll down using your mouse

You'll notice that the drop-down list scrolls off of the screen along with the page underneath it.

Is there an easy workaround for this?
Is this a bug, or am I doing something wrong?

Thanks in advance!

**Comment by schittuluri1** [comment]
@natorojr Were you able to figure the issue?

**Comment by mlh758** [comment]
http://jsfiddle.net/nfvu02qv/
