### ISSUE TITLE
Question about blur event on multiselect

### ISSUE THREAD

**Issue by AltiusRupert** [ehynds/jquery-ui-multiselect-widget#490]
Hi Eric, great stuff, this jQuery multiselect component !

I'm not a pro, but need some help : when multiple items are selected and I click on another part of the page (eg Save button), neither the "close" or the "beforeclose" events are triggered, so I cannot grab the last list of selected values.

Relying on "onchange" is not good for me since I am sending data to my server : sending each individual update would generate too much network traffic.

I need to receive an event "after the last change" : I need to detect "blur", "close" or even "mouse out".
Can you help ?

Rup

**Comment by mlh758** [comment]
Here is the wiki on listening to events:

https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Events
