### ISSUE TITLE
Multiple instances of the widget on one page, not doable?

### ISSUE THREAD

**Issue by jarodtaylor** [ehynds/jquery-ui-multiselect-widget#491]
'm running into issues when having multiple instances of this on one page. Click events on 'label' text are not working on the first 3 or 4 choices. When I comment out one of the Multiselects, everything works as normal.

From what I'm seeing in the source (Dev tools), the labels in the multiselects are conflicting. Both of my instances have the same checkbox id and for attribute on its corresponding label. For instance both instances of multiselect have ui-multiselect-_-option-0 for their first checkbox/label.

I guess we cannot run multiple instances of this on one page?

**Comment by mlh758** [comment]
This is a great fix, and in a later version of this utility code was added to ensure a unique ID was generated regardless to help mitigate this further.
