### ISSUE TITLE
Select box changes its width upon refresh!!

### ISSUE THREAD

**Issue by ellhn** [ehynds/jquery-ui-multiselect-widget#492]
I 've created the following select list:
 $("#offer").multiselect({
 minWidth:430,
 height:250,
 noneSelectedText: 'Ἐπιλέξτε',
 multiple:false,
 header:false,
 selectedList: 1
 });

Every time I am trying to clear its contents with:
 $("#offer").val("");
 $("#offer").multiselect("refresh");

the width of the selected list grows up a little to the right... Why this? It is very annoying. Any idea to correct it?
 Thank you very much

**Comment by mlh758** [comment]
I just confirmed this still happens on the latest version of the widget, jquery, and jquery ui.

All that's required is calling `refresh` on the widget after it is initialized. Changing the value isn't necessary to reproduce the issue.

**Comment by mlh758** [comment]
This is fixed in version3.
