### ISSUE TITLE
Propose change to _setMenuWidth

### ISSUE THREAD

**Issue by rekowsky** [ehynds/jquery-ui-multiselect-widget#493]
When adding long text and willing to have the select or multiselect boxes having smaller widths the text inside the Menu adjust itself to the main width which creates some multi-line text and IMHO does not look good.

I suggest changing the '_setMenuWidth' function a littel so it gets the text length and autofits content.

I hope it can be added to any future versions.

Code below for autosizing the menu:

    // set menu width
	_setMenuWidth: function(){
        var maxLength = 0;
        jQuery(this.button).each(function(){

            var length = jQuery(this).val().length;
            if(length > maxLength) {
                maxLength = length;
            }
        });
		var m = this.menu,
			width = maxLength-
				parseInt(m.css('padding-left'),10)-
				parseInt(m.css('padding-right'),10)-
				parseInt(m.css('border-right-width'),10)-
				parseInt(m.css('border-left-width'),10);

		m.width( width || this.button.outerWidth() );
	},

**Comment by mlh758** [comment]
The new `menuWidth` option will cover most cases where this is needed.
