### ISSUE TITLE
JavaScript Error with Minified version - jquery.multiselect.filter.min.js

### ISSUE THREAD

**Issue by mahboob-awan** [ehynds/jquery-ui-multiselect-widget#495]
Uncaught TypeError: Cannot read property 'menu' of undefined 

I am getting this error with minified version. Things work fine with development version.

**Comment by shakoorattari** [comment]
https://github.com/ehynds/jquery-ui-multiselect-widget/pull/386
here is solution

**Comment by mlh758** [comment]
@shakoorattari Thank you
