### ISSUE TITLE
User filters without "Check All" and "Uncheck All"

### ISSUE THREAD

**Issue by WilliamVercken** [ehynds/jquery-ui-multiselect-widget#497]
I want to use the filter plugin, but I don't want to have the options "Check All" and "Uncheck All" in the header.

If I disable the header, the filter isn't there.

An option to disable "Check All" and/or "Uncheck All" (and not all the header) would be great.

**Comment by mlh758** [comment]
The options `showCheckAll` and `showUncheckAll` are available and do what you would like.
