### ISSUE TITLE
Plural "selectedText" option

### ISSUE THREAD

**Issue by WilliamVercken** [ehynds/jquery-ui-multiselect-widget#498]
Hi,

I have a problem.
In french, we say :
- 1 selected -> 1 sélectionné
- 7 seleced -> 7 sélectionné<b>S</b>

With Multiselect Widget, I can change the "selectedText" option, but I can't do it when I have several options selected.

An option to solve this problem would be great ! :-)

Thanks a lot !

**Comment by SteveTheTechie** [comment]
This should be closed as the already existing ability to use a function for setting selectedText addresses this use case.

**Comment by mlh758** [comment]
Good call, thank you.
