### ISSUE TITLE
Tab order isn't maintained

### ISSUE THREAD

**Issue by downzer0** [ehynds/jquery-ui-multiselect-widget#507]
It appears that tab order is lost when this plugin is active. If I've got a form with say, five fields, once I tab to activate the select menu, press Enter to open the choices, and then press Enter to select a choice, the next Tab goes back to the top of the page.

This is the case in the pure demos here as well as in my interface.

I've managed to find a workaround using the following code:

```
open: function(event, ui) {
    $(this).parent().find('button.ui-multiselect').attr('tabindex', '-1');
},
close: function(event, ui) {
    $(this).parent().find('button.ui-multiselect').focus();
}
```

Sorry if this is a duplicate.

**Comment by mlh758** [comment]
This has been fixed [in a recent commit](https://github.com/ehynds/jquery-ui-multiselect-widget/commit/fd787242943090db121748f2a416091a1fdc4d09)
