### ISSUE TITLE
scroll bar unreachable when changing rezolution or browser dimensions

### ISSUE THREAD

**Issue by adelina1985a** [ehynds/jquery-ui-multiselect-widget#509]
I used a demo on the official page and as you can see in the first image I can't scroll through even half of the list in a smaller browser window.
![untitled](https://f.cloud.github.com/assets/4322542/1342843/49d12788-366a-11e3-9349-9b31d8abf5b3.png)
The 2nd image shows default behavior - going outside the window.
![untitled2](https://f.cloud.github.com/assets/4322542/1342984/0de9cb06-366c-11e3-8240-92e259d04085.png)

EDIT: even without the scrollbar, there still is a problem because the dropdown isn't fully visible as you can see.

**Comment by mlh758** [comment]
There isn't a way for us to have HTML elements extend outside the window. The dropdown in the second image is part of the browser itself, not the web page.
