### ISSUE TITLE
ADDING OPTIONS TO A MULTISELECT DROP DOWN LIST

### ISSUE THREAD

**Issue by ozzarch** [ehynds/jquery-ui-multiselect-widget#514]
Hi, thank you for the plugin!

I am using Eric Hynds multiselect plugin for my website.

I have tried to load it on jsfiddle but it did not work (I have uploaded it to my server)

I would like to include more options when the users select some of them (It means creating a new option when value one is checked or show the next hidden option when the previous one is checked).

This is how it is: 
http://ozzarch.com/try/Superprueba02.html

This is the first step how I would like it to be:
http://ozzarch.com/try/Superprueba03.html

This is the second step how I would like it to be:
http://ozzarch.com/try/Superprueba04.html

2 and 3 are the same but 3 has got more checked options. Please notice that there is always a none-checked option for each person.

I thought that it would be easier however the plugin:

.does NOT give single values of selected options. All of them appear in a list separated by commas. Please see the link above
(I thought that it could be a good idea create an Array from the list and get the values from the Array)

.The list of values is not indexed, which means that if you want to put them in an Array. it always says that the index is 0 for all the values and you cannot split them into different values. Please see the link above

Well I cannot find the way of creating an Array from that.

If you have a better idea for adding more options to this multiselect dropdownlist, please let me know.

Thank you

**Comment by mlh758** [comment]
I'm going to close this one due to age and broken links, sorry.
