### ISSUE TITLE
Multiselect getChecked function can not get the list of text

### ISSUE THREAD

**Issue by Bryan1220** [ehynds/jquery-ui-multiselect-widget#518]
In 1.13 Release, we can do this to get the list of text,

var checkedValues = $.map($(this).multiselect("getChecked"), function (input) {
                    return input.title;
                });

But currently, input.title doesn't work.

So I read the code and find this 

var title = this.title;  ( Line 140 in  jquery.multiselect.js 1.14pre)

It is different from 1.13 Release.

title = this.innerHTML;  ( Line 130 in  jquery.multiselect.js 1.13)

So I replace this.title with this.text in 1.14pre, and can get the list of text.

Is it right :)

**Comment by mlh758** [comment]
As of the current release, if you want the values of all the checked items you can just do:

`$("selector").val()`

If you want the labels for the checked items this would work:

    $("selector").multiselect("getChecked").each(function(idx, element) {
        console.log(element.next().text());
    });

The span for the label comes after the checkbox so `next()` gives you the label. Calling `text()` gives you the text content of that span.
