### ISSUE TITLE
MVC 4 with @Html.ValidationMessageFor

### ISSUE THREAD

**Issue by Nyikelo** [ehynds/jquery-ui-multiselect-widget#519]
I've been using this widget for a very long time and just started to using it on my MVC 4 project and the validation does not work.
The validation on the dropdown list works fine without the widget, but as soon as I use it, all the validation does not work.

My c# class
[Required(ErrorMessage = "Please enter Marital Status")]  
public string MaritalStatusID { get; set; }

My View
@Html.DropDownListFor(model => model.MaritalStatusID, Model.MaritalStatus.MLOMaritalStatus, String.Empty, new { @class = "select" }) 
                            @Html.ValidationMessageFor(model => model.MaritalStatusID)

My js
$(".select").multiselect({
             header: "Choose an Option",
             noneSelectedText: 'Choose an Option',
             selectedText: "# of # selected",
             selectedList: 4,
             minWidth: 150,
             height: 100,
             hide: "explode",
             multiple: false
}).multiselectfilter();
$('.select').multiselect('refresh');

**Comment by mlh758** [comment]
Looks like a solution was found.
