### ISSUE TITLE
checkall uncheckall do not fire

### ISSUE THREAD

**Issue by DaveC426913** [ehynds/jquery-ui-multiselect-widget#520]
Neither checkall nor uncheckall will fire.

What I'm trying to accomplish is have any change to the checklist resubmit the form. That must include checkall and uncheckall.

This is how I'm doing it, but does not work:

	$("#filter").on("multiselectclick", function(event, ui) {
		// Fires
	});
	$("#filter").on("checkall", function(event, ui) {
		// Does not fire
	});
	$("#filter").on("uncheckall", function(event, ui) {
		// Does not fire
	});

**Comment by mlh758** [comment]
The documentation was incorrect, the events are in camel case so as @fglueck pointed out `checkAll` and `uncheckAll` would fire but `checkall` would not. Prepending the namespace would also work, but wouldn't be the intended way of going about it.
