### ISSUE TITLE
Single select dropdown validation

### ISSUE THREAD

**Issue by katibogar** [ehynds/jquery-ui-multiselect-widget#521]
When I'm trying to validate my single select dropdownbox, even if nothin's been selected and the "Please Select" is visible, it still thinks that the first item in the list is the selected one.

$j("#ddlAlternativeCode option:selected").val()  just gets back the value of my first item in the dropdown. I need it to be 0 or null. 

Please look at the Select error code dropdown. Even if i leave it at that, the value of my first item "123" comes back. Any idea why?

**Comment by mlh758** [comment]
You can get the value of the select with $("#selectId").val(), which returns null if nothing has been selected.
