### ISSUE TITLE
IE8: Browser is not responding if there's more than 400 options in the select

### ISSUE THREAD

**Issue by litex1982** [ehynds/jquery-ui-multiselect-widget#522]
Page load very slow and become not responding if there's more than 400 options in the select in IE8, and worse in IE8 compatible mode.
![script error](https://f.cloud.github.com/assets/6386632/1898220/4d3d257c-7c13-11e3-8c12-1a120af2a507.jpg)

**Comment by mlh758** [comment]
Some performance improvements have been made with the latest release, I also have no intention of supporting IE8 in 2016.
