### ISSUE TITLE
autoOpen=true puts widget on top of DOM in Google HtmlService

### ISSUE THREAD

**Issue by arnovb-github** [ehynds/jquery-ui-multiselect-widget#524]
When invoked in Google's HtmlService API, I am having trouble when I set autoOpen property to true. The widget then gets displayed on top of the DOM.

I have tried to create a very simple example of this problem in this spreadsheet: https://docs.google.com/a/highiq.nl/spreadsheet/ccc?key=0AuivUqLIUoZ5dDEwbVMwMGxNY29fV1R5cGdNUlIwcUE#gid=0. I included instructions on how to reproduce the problem in the sheet itself.

Please note that because the example uses a Google service, it is required that you are logged in at Google (any account will do) and make a copy of the spreadsheet to reproduce the problem. As with any Google Apps Script service, you are asked to grant permission before executing. No data is read or edited, but I realize that's just me saying so. By all means review the script code first if you are distrustful!

I would like the widget displayed in an 'opened' state on the second tab, not on top of all elements. Thank you for any suggestions.

-arno

**Comment by mlh758** [comment]
In some recent changes we removed the z-index property from the widget and went with a more standard behavior for appending the menu. This should keep it from appearing over the rest of the DOM.  If it is still appearing in the wrong place, you can use the `appendTo` option to make sure the menu ends up in the right place.

If your height, width, and position relative to the button are correct then you can ignore this paragraph. If the tab is hidden, you should wait until the tab is revealed by the user before instantiating the widget, just leave it as a regular select until then. A lot of element properties can't be calculated properly while an element is hidden.
