### ISSUE TITLE
jQuery multiSelectable() is not reloading the selectable values in to selected list with IE 9 

### ISSUE THREAD

**Issue by mywebworld** [ehynds/jquery-ui-multiselect-widget#525]
Hello,

When I selected any option from selectable box, those options values are appearing with the First Letter of the option value in the Selected box. When I refresh the page after selection it is appearing with proper value.

Can anyone encounter the same situation, could you please help me in this.

Thanks in Advance

**Comment by mlh758** [comment]
Closing this issue due to age and IE9.
