### ISSUE TITLE
website demo points to raw file

### ISSUE THREAD

**Issue by rafaelcastrocouto** [ehynds/jquery-ui-multiselect-widget#526]
The first demo on http://www.erichynds.com/blog/jquery-ui-multiselect-widget
is not working since it's 'jquery.multiselect.js' is pointing to github raw file.

Refused to execute script from 'https://raw.github.com/ehynds/jquery-ui-multiselect-widget/master/src/jquery.multiselect.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. 

All you gotta do is change it to http://www.erichynds.com/examples/jquery-ui-multiselect-widget/src/jquery.multiselect.js

**Comment by mlh758** [comment]
Unfortunately the website is no longer being updated. Pertinent documentation is now on the wiki here and being kept up to date but the demos aren't likely to get updated.
