### ISSUE TITLE
multiselect filter dont work when used with jQuery Dialog

### ISSUE THREAD

**Issue by ajeetcoolkarni** [ehynds/jquery-ui-multiselect-widget#527]
Hi Eric,
I was trying to implement multiselectfilter() with jQuery Dialog, altough control renders fine but the problem is it's filter input box keyup and keydown events dont get fired. Where as input box click event is fired. And I felt the multiselct check box check\uncheck event works too slow on IE when used with  jQuery dialog. 
Kindly tell me a solution and fix the issue. Thank You

**Comment by mlh758** [comment]
Using `appendTo` to place the menu in the dialog somewhere will make it work. I'm making a commit today to make it position more reliably within the modal.
