### ISSUE TITLE
Text alignment issue + pop up position

### ISSUE THREAD

**Issue by malhayek2014** [ehynds/jquery-ui-multiselect-widget#529]
Hi
First I want to thank you for this great widget. I am encountering possible bugs in the widget.

When I have a long text as an option it seems that the text alignment will switch from ltr to rtl only for the long text option.

second problem when I click on the option to display the menu it opens it on the bottom of the page not next to it. When I use the position element method then it works most of the times. I don't know why I have to use the position element for it to work.

third if I want to hide the menu by defaults I can't. I tried adding display: none  then use the $('#na').show(); that does not work.

**Comment by mlh758** [comment]
The positioning issue should be fixed in a recent commit.

The menu is always hidden by default. You would need to use `autoOpen: true` to do otherwise. You should be opening and closing the menu with `$("selector").multiselect("<open/close>");`
