### ISSUE TITLE
Can i override format of selectedtext in mulitiselect widget

### ISSUE THREAD

**Issue by tech2504** [ehynds/jquery-ui-multiselect-widget#531]
Is there any possible to override format on selecttedtext on multiselect.I tried to change update in  jquery.multiselect.js .But this is was impact on entire apps. But I required only particular screen only.

So Is there any feature here like dropdownchecklist. textFormatFunction?

Thanks advance

**Comment by mlh758** [comment]
You can pass a function that generates a string to the selectedText option. If you want to add HTML or JavaScript to it you will have to override the `setButtonValue` method to allow for HTML in the button.

You can find sample code for that here: https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Customization
