### ISSUE TITLE
Search box results for single character

### ISSUE THREAD

**Issue by gav137** [ehynds/jquery-ui-multiselect-widget#532]
Could you consider improving the usability of the filter search box in the case of a single character typed by only returning results which start with that letter? There is too much noise currently for single key entries and users are generally wanting  the dropdowns behave in more useful way similar to the native dropdowns in this case.
Thanks so much

**Comment by mlh758** [comment]
I'm not sure if the option existed then, but there is a [callback](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Filter-Events) available to further filter results down if you don't like the default behavior.
