### ISSUE TITLE
Using Jquery 1.7.2 Receiving JS error in chrome inspector: 

### ISSUE THREAD

**Issue by EminenceHC** [ehynds/jquery-ui-multiselect-widget#535]
Uncaught TypeError: Object function ( selector, context ) {
        // The jQuery object is actually just the init constructor 'enhanced'
        // Need init if jQuery is called (just allow error to be thrown if not included)
        return new jQuery.fn.init( sele...<omitted>...t'

**Comment by mlh758** [comment]
I'm closing this due to the age of the issue.
