### ISSUE TITLE
How should i handle escape character for option values? 

### ISSUE THREAD

**Issue by mahboob-awan** [ehynds/jquery-ui-multiselect-widget#536]
Hi,
```
<select>
 <option value='test"ABC"test'><!-- value is already escaped at the time of generation-->
</select>
```

I am getting problem with escape characters present in SELECT's OPTION's value and that i solved with following change:

https://github.com/ehynds/jquery-ui-multiselect-widget/blob/master/src/jquery.multiselect.js#L141
```
var value = escapeHTML(this.value),
```

where escapeHTML is just escaping characters(e.g. ', ", < etc)
```
  var entityMap = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': '&quot;',
    "'": '&#39;',
    "/": '&#x2F;'
  };

  function escapeHtml(string) {
    return String(string).replace(/[&<>"'\/]/g, function (s) {
      return entityMap[s];
    });
  }
```

Kindly guide me to fix this problem or update this plugin. Thanks

**Comment by JPustkuchen** [comment]
I can confirm this problem exists... what can we do?

**Comment by mlh758** [comment]
@JPustkuchen Have you tried the latest code from the repository? A relatively recent commit (https://github.com/ehynds/jquery-ui-multiselect-widget/commit/b34d1d3ef0fb3a4cab8b3b071f82ef4dee78d0d9) should have resolved this and does in my test cases.

**Comment by JPustkuchen** [comment]
Thank you very much! You are right. It's fixed in there. This can be closed. FIXED!

**Comment by mlh758** [comment]
Not a problem, just glad it's fixed.
