### ISSUE TITLE
minWidth auto ends up with a width calculation that's a bit too short.

### ISSUE THREAD

**Issue by mealy** [ehynds/jquery-ui-multiselect-widget#544]
Setting minWidth to "auto" works, except that the control ends up being sized such that it's a _little_ too short to prevent the longest options from wrapping.  Possibly it's failing to account for the width of the checkbox element itself, or failing to account for the width of the vertical scrollbar. 

I'm afraid I don't know the length of the options before hand so I do need the control to set the option width based on the actual text content. 

As a secondary request, it'd be great if when you set minWidth to auto if there could be a maxWidth.  ie a width beyond which auto is not allowed to go.  in other words beyond which it should wrap and/or scroll the option list.

**Comment by sebhaase** [comment]
I seem to have this issue, too.

**Comment by Ellingson** [comment]
Look around line number 543 for:
`var width = this.element.outerWidth();`

And replace with:
`var width = this.button.outerWidth();`

**Comment by SteveTheTechie** [comment]
@mlh758  I believe PR #744 addresses this.  This should be closed.
