### ISSUE TITLE
Disable on hover (style)

### ISSUE THREAD

**Issue by franciscocorrales** [ehynds/jquery-ui-multiselect-widget#548]
Hi,
I want to disable the on hover event properly. So when the cursor pass over the options, it just doesn't break anything, and shows little (my custom) style.

Right now, what I have done to do that is: 
`jQuery(".ui-corner-all").unbind('mouseenter mouseleave');`
and I set up my style like this:
`jQuery(".ui-multiselect").removeAttr("style")
    jQuery(".ui-multiselect").css('width','130px;');
    jQuery(".ui-state-default").css('color',  '#777777;');
    jQuery(".ui-state-hover").css('color',  '#777777;');`

That is one way of doing it (yeah, not the best one...), cause it causes some troubles like in Internet Explorer, the first option has focus (take a look at the image).  I fix that with this code: `open:function(){ jQuery(".ui-corner-all").focus();}` in the creation of the _multiselect_

**So the question:**
     1.  how can I disable on hover event properly, so I don't have to be fixing those details (that might occur) in each browser...
     2.  how can I set my custom style properly in a .css file

![internet explorer - multiselect - border - onhover](https://cloud.githubusercontent.com/assets/4010693/2572386/c9c8dfe6-b912-11e3-9938-db88f8bc1fdb.png)

**Comment by mlh758** [comment]
I feel like it would be easier to customize a theme where the hover states look the way you want them to instead of trying to disable the default hover functionality, and then override it with different functionality to display a different style.

https://jqueryui.com/themeroller/
