### ISSUE TITLE
click to scroll issue

### ISSUE THREAD

**Issue by metinata** [ehynds/jquery-ui-multiselect-widget#551]
Hello,

I have a horizontal scrolling page and when click selectbox scrollbar going to left side

**Comment by SteveTheTechie** [comment]
@mlh758 This should be checked against the new code.

**Comment by mlh758** [comment]
Checking the PR it looks like I wasn't able to verify the issue in IE 11 or Edge even on the 2.0 code and never closed these issues.

Given the dates this was probably an older IE problem. I'll still double check though.

**Comment by SteveTheTechie** [comment]
@mlh758 This should have auto-closed, but did not.
