### ISSUE TITLE
Not able to add data-attribute in checkboxes if available in <option />

### ISSUE THREAD

**Issue by ashishkumar-ui** [ehynds/jquery-ui-multiselect-widget#554]
Let say, I have some data attributes available in &lt;option> tags in the source select tags, It is not generating the same data attributes in the multiselect checkboxes as well.

I have tweaked the code a bit in my local system and this is working great to me, but this is something which should be available in the plugin.

Code added: 

[Line-148]: <code>var dataAttrs = $this.data();</code>
[Line-190]: <code>$.each(dataAttrs, function(attr, attrVal){</code>
            <code>html += ' data-' + attr + '="' + attrVal +'"';</code>
        <code>});</code>

**Comment by mlh758** [comment]
This is now built in functionality.
