### ISSUE TITLE
Remember selected values

### ISSUE THREAD

**Issue by Paul-Isache** [ehynds/jquery-ui-multiselect-widget#557]
Hi!
I am using this multiple select in a grid and I am trying to make this grid dynamic (I put the values in the dropdown depending on what you chosen), I ran in to a problem, if a make the 2 or 3 selects from the selects, deselect their values, is a there any other way to check in the select, if I try to checkAll option I run into infinite loop. I want to bypass this by adding a class or something. Is this possible?

Thank you

**Comment by mlh758** [comment]
You can add the `selected` attribute to the items you want checked then call the `refresh` method on the widget.

You could also get the widget instance and call the native `click` method on the items you want selected.

https://github.com/ehynds/jquery-ui-multiselect-widget/wiki
