### ISSUE TITLE
jquery-ui-multiselect-widget flickering while loading the data?

### ISSUE THREAD

**Issue by rajesh2210** [ehynds/jquery-ui-multiselect-widget#558]
jQuery MultiSelect UI Widget 1.14pre

This is an issue for me with the long list. See the below image for the onload and after load effect(click on link).

I just tested a list of 1600 items on a mozilla machine and the browser locked up for about ~5 minutes.

https://camo.githubusercontent.com/3dc1a939065e6364e699eef8f08b9cd653741cf0/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f333439313130312f3335313235362f61636133333962652d613034322d313165322d393462382d3239396561333065663532632e706e67

Is there any suggestion how to solve this

**Comment by mlh758** [comment]
The newer versions of the plugin have a number of performance improvements that should help with this.
