### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by ronk30** [ehynds/jquery-ui-multiselect-widget#559]
Hello and thanks for you great widget,

is RTL working ? is there exmple somewhere?

im having issue with it text are disappear 'off' the widget size when rtl mode,
i found an old thread talking on it here and suggesting fixed css but its not helping

**Comment by SteveTheTechie** [comment]
@mlh758 The following looks interesting:
[http://rtlcss.com/](http://rtlcss.com/)

**Comment by mlh758** [comment]
I'll give this a shot. Looks like they have a CLI so I should just be able to generate a second set of stylesheets.

**Comment by mlh758** [comment]
Okay, that flag doesn't seem to do much except flip the flags page... That's odd.

Anyway, I tried running rtlcss and while it _mostly_ worked for the regular drop down, the inputs are still on the left which looks a little strange. That might have been because RTL mode wasn't doing anything though.

The single select was still very broken. I'll have to look into it more.

**Comment by SteveTheTechie** [comment]
> so I should just be able to generate a second set of stylesheets.

@mlh758  Yeah that was what I was hoping for.

**Comment by SteveTheTechie** [comment]
@mlh758  Some decent references:

http://blog.scottlogic.com/2015/02/13/rtl.html
https://hacks.mozilla.org/2015/09/building-rtl-aware-web-apps-and-websites-part-1/
https://alfy.me/2014/07/26/lets-talk-about-rtl.html
http://www.ctomczyk.pl/right-to-left-implementation-tricks/642/

One of them mentions a way of just putting [dir="rtl"] overrides in same CSS file.  I was not aware that was possible, but it would eliminate having to maintain an extra CSS file.

I think that the Javascript is going to have to detect the direction and adjust for it.  If you consider something like the _makeOption() function, it builds the input, possible icon, and text in a particular order.  If the pieces can be built, but the proper order determined at the end, that may be the right approach.

**Comment by mlh758** [comment]
> One of them mentions a way of just putting [dir="rtl"] overrides in same CSS file. I was not aware that was possible, but it would eliminate having to maintain an extra CSS file.

That would be better, then people don't have to pull separate files.

**Comment by mlh758** [comment]
7 years in I'm going to say this feature won't be added.
