### ISSUE TITLE
jQuery UI Multiselect Widget With Images

### ISSUE THREAD

**Issue by cacuestai** [ehynds/jquery-ui-multiselect-widget#564]
Hello:

See:
http://stackoverflow.com/questions/22274392/jquery-ui-multiselect-widget-with-images-eric-hynds-version

Thank,

Carlos

**Comment by mlh758** [comment]
I've tentatively added this feature. 

Adding `data-image-src` with the image source URL to the option element will cause an image to be added to the menu item in the widget.
