### ISSUE TITLE
No click event after cloning div

### ISSUE THREAD

**Issue by misterpo** [ehynds/jquery-ui-multiselect-widget#566]
Hi,

I have embedded jquery-ui-multiselect-widget in a responsive website.
Everything works as expected except when resizing the window to lower than 480px wide on the following page: http://sportair.alptic-dev.fr/biex_liste_exposants_filtre.php.
I had to clone the div containing the multiselect-widget to another visible div and  nothing happens anymore when I click on the choices button.

Here is the Jquery code I have used :
if ($('.z-tabs-nav').hasClass("z-hide-menu")) {
  var clone = $(this).children('.checkboxes-sub-menu').clone();
  clone.appendTo('.z-tabs-mobile');
  }

Any idea ?

**Comment by mlh758** [comment]
https://bugs.jqueryui.com/ticket/3803

Cloning widgets is unfortunately not supported by jQuery UI.
