### ISSUE TITLE
Modifying multiselect list height in terms of rows, not pixels

### ISSUE THREAD

**Issue by smontanaro** [ehynds/jquery-ui-multiselect-widget#569]
I'm not much of a JS/jQuery person, so I may be going about this all wrong, however...

There seems to be no obvious way to set the height of the <ul> widget generated by jquery.multiselect (again, consider that I know little about how all this JS/jQuery stuff works, so am probably missing something everyone else "just knows"). What little I was able to discover from looking at the code suggests that it never attaches units to the height either, so "px" are always assumed. This seems to be a bit of a regression in terms of abstraction. Plain old <select> widgets have a size attribute which is specified in rows. It would be nice if that size attribute was translated to something meaningful by this system. As an alternate, allowing setting of the height with attached units ("em"?) would be better than specifying them in pixels.

**Comment by SteveTheTechie** [comment]
This will be addressed in my next PR.

**Comment by SteveTheTechie** [comment]
Implemented by #735.   Closing this.

**Comment by SteveTheTechie** [comment]
@mlh758 Implemented by #735. This can be closed.
