### ISSUE TITLE
Manually check or uncheck not working on SingleSelect

### ISSUE THREAD

**Issue by RajeshTheCool** [ehynds/jquery-ui-multiselect-widget#571]
When $(#Select).multiselect({ multiple: false}); and tried to select a value on the dropdown using the below code is not working

$(#Select).multiselect("widget").find(":checkbox[value='1']").each(function () {this.click(); });

But when $(#Select).multiselect({ multiple: true}); it is working fine

**Comment by mlh758** [comment]
There are no checkboxes in single select mode, so `:checkbox` isn't going to do anything.
