### ISSUE TITLE
How to Add the classes to only ui-multiselect-menu and not to button

### ISSUE THREAD

**Issue by dkedar** [ehynds/jquery-ui-multiselect-widget#572]
Hello,
I am using Jquery Multiselect Pluging in my current project. Its a Great plugin.

There are several instances on page of Jquery Multiselect and I need to give width to each  ui-multiselect-menu differently, Only ui-multiselect-menu and not to button.

How it is possible

Thanks
Kedar

**Comment by mlh758** [comment]
There is a "menuWidth" option in the latest release that will allow you to do exactly this. Good luck!
