### ISSUE TITLE
client side pagination

### ISSUE THREAD

**Issue by saneletm** [ehynds/jquery-ui-multiselect-widget#573]
How can I implement some kind of client side pagination. My multiselect sometimes gets over 10 000 items. I would like to do some pagination to improve performance, especially for Chrome and Safari where this is especially slow. Basically, in the case where I have say 10 000 options, I would like to initially display, say 1000 options, and incrementally add as the user scrolls though the list.  Any help will be greatly appreciated.

**Comment by mlh758** [comment]
This might be outside the scope of what multiselect would be good for.

You might instead wish to build a list box view of some kind, and use a library like [jScroll](http://jscroll.com/) to provide infinite scrolling. A multiselect would be cumbersome with that many items.
