### ISSUE TITLE
Default $("#selRecID").multiselect();  produces Error

### ISSUE THREAD

**Issue by joeller** [ehynds/jquery-ui-multiselect-widget#577]
This default implementation $("#selRecID").multiselect(); produces an error "Object doesn't support this property or method" when using JQuery versions 1.8.2 or 1.11.1 with JQuery UI versions 1.8.24 or 1.11.2  I also tried $("select#selRecID").multiselect();  same error.
I have not seen any reason for this or way around it.

This is with simple HTML select with multiple attribute set. and with command in $("document").ready function.

**Comment by mlh758** [comment]
I haven't been able to reproduce this issue and it's an old one so I'm closing it.
