### ISSUE TITLE
bower is still pulling old library

### ISSUE THREAD

**Issue by sameercaresu** [ehynds/jquery-ui-multiselect-widget#580]
Hi,
I couldn't post issue https://github.com/seferov/jquery-ui-multiselect-widget

But when I do `bower install ui-multiselect`. It is still pulling the old library and not being updated with the new one.

I think maybe tag is not updated

bower install ui-multiselect#master gives me updated one

**Comment by gregfr** [comment]
It seems that way we can obtain up to 1.14, whereas the library is currently at version 1.17
