### ISSUE TITLE
single select set value to empty string without multiselect("refresh") ?

### ISSUE THREAD

**Issue by wkrick** [ehynds/jquery-ui-multiselect-widget#593]
I'm using the multiselect widget in single select mode.

I need to "reset" the select to no selection in certain situations.  This by itself doesn't work...

$("#myselect").val("");

...so based on comments I've found on the Internet, I also need to follow it with...

$("#myselect").multiselect("refresh");

...which works, but is really, really, really, unacceptably slow on Internet Explorer (even IE11) when the list contains many items.

I don't understand why it's necessary to rebuild the control when simply selecting nothing.  The list of items hasn't changed.

Is there something I'm missing?  It should just work like a normal select when you set the val to an empty string.  If that's not possible, then maybe a "reset" method...

$("#myselect").multiselect("reset");

**Comment by mlh758** [comment]
You can use the uncheckAll method even in single select mode to reset the selections.
