### ISSUE TITLE
How to sort between the optgroups (Alphabetically) 

### ISSUE THREAD

**Issue by sankety** [ehynds/jquery-ui-multiselect-widget#599]
To sort alphabetically within the optgroups

optgroup 1
c
d
a
b
/optgroup

result should be
optgroup 1
a
b
c
d
/optgroup

**Comment by mlh758** [comment]
You would want to build the content alphabetically before turning it into a multiselect, or before refreshing an existing one. JavaScript has a built in `sort()` to accomplish this.
