### ISSUE TITLE
Unable to disable or enable

### ISSUE THREAD

**Issue by tpanini** [ehynds/jquery-ui-multiselect-widget#601]
dynamically want to enable or disable multiselect dropdown using below code.
.multiselect("enable");
or
.multiselect("disable");
But consistently getting
Error: cannot call methods on multiselect prior to initialization; attempted to call method 'disable'.
Not sure why this multiselect is not initialized. I can see the widget working & initialized.

There is something or some error which is throwing up this error.

**Comment by Gwasshoppa** [comment]
You will probably find that the checkbox list has not been initialized... This can happen when you use a popup but bind the list on the parent page.

if this is the case use the jquery .on() to bind the list correctly... https://api.jquery.com/on/

**Comment by mlh758** [comment]
@Gwasshoppa is correct. I'm going to go ahead and close this.
