### ISSUE TITLE
Single Select not showing the By Default option in dropdownllist

### ISSUE THREAD

**Issue by chetanpatil6** [ehynds/jquery-ui-multiselect-widget#602]
Hi All,
I try to use the below code to select the first value of the dropdown by default selected but it is not showing.

HI All,
I am using below code to show the by default value to single select option . But it is still showing me the Select Options as by default value instead of Next Value in the list . I try with change selectedList numbers. 

    $("#select_time_juri").multiselect({
        multiple: false,
        noneSelectedText: "Select Options",
        selectedList: 1,
    });

Please help me on the above problem .

**Comment by vijay1608** [comment]
putting "multiple:false" in code let you you choose only one option ,but dosnt close atomatically,this code will help you to close automatically after one selection 

$("select").bind("multiselectclick", function()
{
 $(this).multiselect("close");
});

**Comment by mlh758** [comment]
If you want the first value to be selected automatically (or any value in either mode) you can modify the select before turning it into a multiselect widget, or modify it after and call the refresh method. You'll want to add `selected="selected"` to the option(s) you want selected automatically. It might look something like this:

     <select id="MultiSelectTest2">
                <option value="1"  selected="selected">Option 1</option>
                <option value="2">Option 2</option>
                <option value="3">Option 3</option>
                <option value="4">Option 4</option>
      </select>
