### ISSUE TITLE
Why is this not actively maintained.. ??

### ISSUE THREAD

**Issue by gs-akhan** [ehynds/jquery-ui-multiselect-widget#603]
Can someone fork it and stabilize all bugs that are open. I am sick of this !!

Thanks

**Comment by JacobChrist** [comment]
Sounds like you are volunteering.

**Comment by gs-akhan** [comment]
I would love to. There are tons of issues that needs to be fixed on this. If someone wants to take initiative I am very much interested to contribute..

**Comment by gs-akhan** [comment]
I think the repo owner has expired.. Feel really sorry for him

**Comment by OsakaWebbie** [comment]
gs-akhan: Why don't you just take the initiative yourself? If you do fork it, let us know where to find it.

**Comment by alokpant** [comment]
@gs-akhan what are you talking about? Eric Hynds is alive. Close this issue. This is not even an issue. Ungrateful idiot. Do some research before writing that the repo owner is dead.

**Comment by gs-akhan** [comment]
Hi all..
Here I've duplicated this repo. I will start fixing all issues, setup a API page and Merge PR's as fast as a Ferrari.
https://github.com/gs-akhan/new-jquery-multiselect-widget
Thanks

**Comment by softcircuits** [comment]
@gs-akhan I took a look at your branch. I noticed there is not Issues link on the right so that I have no way to make comments. Do you know why that is?

I also am having several issues with the Eric's original code. I was wondering if you have a change log that I could review. And I would possibly contribute to add my own fixes if they have not been addressed. Thanks.

@alokpant Lighten up dude. People need some fixes and are just asking if the original author is available and would consider making them. There is nothing on this planet wrong with that. Your response is completely inappropriate.

**Comment by alokpant** [comment]
@softcircuits I understand your point. I have used multiselect many times and have struggled only to find solutions in stackoverflow. I think what Eric has done already solves alot of issues. So calling him dead is not nice.

Also the fork does not have the issues section enabled by default. It needs to be enabled.
This can be changed in the settings of forked repo. New issues reported into forked will not be integrated on this one. @gs-akhan

**Comment by gs-akhan** [comment]
Yup. Forked repos don't have issue section. What I will do is create new
repo and have all infra setup. Including build. Tests and linting. So we
have a active contributions and releases ..

**Comment by mlh758** [comment]
Starting to work on this now, @gs-akhan has been maintaining this in a separate repo but I would like to get the original going again so people can look to the original source.

**Comment by gs-akhan** [comment]
@mlh758  Are do you have merge rights to this repo ?
thanks

**Comment by mlh758** [comment]
@gs-akhan I do, I'm starting to work through the pull requests but I will be moving slowly at first. I want to make sure I have a good understanding of the code and unit tests before making changes. A lot of the open pull requests don't have unit tests either.

**Comment by gs-akhan** [comment]
Thank you so much. I will make sure I am also revewing code too.

**Comment by mlh758** [comment]
@gs-akhan Thank you, that will be a big help having a second set of eyes on all this. I figure it will be best to get the unit tests all up to date and working, then move on to enhancements so we can prevent regressions as we work on this.

**Comment by gs-akhan** [comment]
@mlh758  Sounds great !! :+1:

**Comment by mlh758** [comment]
@gs-akhan I just opened and merged a pull request for issue 595. If you update your copy of this repo, you should see [this file](https://github.com/ehynds/jquery-ui-multiselect-widget/blob/master/tests/unit/testSuite.html) which will let you run the unit tests locally. Are you seeing 6 failures? I see 2 failures in options: minWidth and 4 in events: multiselectclick.

If you're seeing the same failures then that might be a good first change for us to make.

**Comment by gs-akhan** [comment]
Will check it out.
