### ISSUE TITLE
is there any chance to get responsive view

### ISSUE THREAD

**Issue by lavaraju** [ehynds/jquery-ui-multiselect-widget#604]
there is no responsive for this multiselect dropdown list if there is any chance to get it plz tell me

**Comment by mlh758** [comment]
Could you clarify what you are asking for?

**Comment by amydws** [comment]
I think I'm having the same issue as the OP. The dropdown is added before the </body> tag so it doesn't respect the max-width of the original container. I have fluid width fields in a sidebar that are the max-width of the container, but the multi-select does it's own thing.

**Comment by mlh758** [comment]
Would you mind testing with the latest code? There were some bug fixes to honor the containers max width in the last release, and several more fixes that haven't gone into a release yet. If you are still having a problem I'll label this as a defect and take a closer look.

**Comment by GordonLesti** [comment]
We have solved this problem with the `appendTo` option. Default for this option is `body`, but we just surround our multiselect with a `<div id="divId"></div>` and create the multiselect with the option `appendTo`:
```
 $("select").multiselect({
   appendTo: "#divId"
 });
```
This will add the widget to them same div as the origin multiselect and let you use some CSS like `width: 100%` on the classes of the widget.

**Comment by mlh758** [comment]
@GordonLesti I'm glad to hear there is a workaround for this.
