### ISSUE TITLE
Is there a way to set the container width separately from the dropdown box?

### ISSUE THREAD

**Issue by ChayaCooper** [ehynds/jquery-ui-multiselect-widget#606]
Is there a way to set the container width separately from the dropdown box? I've tried assigning it in both the function and in the css file, but none of the obvious methods seem to do the trick.

**Comment by mlh758** [comment]
Yes, you can use the `menuWidth` option that was recently added to specify a width for the menu separate from that of the button.

This feature wasn't available when you asked this question though.
