### ISSUE TITLE
Use outerWidth before hiding

### ISSUE THREAD

**Issue by CheriePun** [ehynds/jquery-ui-multiselect-widget#609]
> The value reported by .outerWidth() is not guaranteed to be accurate when the element or its parent is hidden. To get an accurate value, ensure the element is visible before using .outerWidth(). - [Documentation](http://api.jquery.com/outerwidth/)

I am having the problem of the widget being extremely since it was getting a much larger outerWidth after the widget was hidden. The value should be retrieved before hiding.

**Comment by mlh758** [comment]
Fixed in a recent commit. Thank you for bringing this up.
