### ISSUE TITLE
Multiselect in comination with ui tabs

### ISSUE THREAD

**Issue by thunder141** [ehynds/jquery-ui-multiselect-widget#610]
I habe a problem with autoopen.
I have a site with 3 tabs generated by jquery ui tab widget.
My Selectbox is on a non active tab. But I want to have it opened, so i use autoopen:true.
But on loading the page the opened checkedlistbox is shown on the first active tab while the listbox is on the second tab.
Also the autoopen seems to ignore settings like minWidth.
What can I do to get around?

**Comment by mlh758** [comment]
You probably wouldn't want to have the multiselect open when it isn't on an active tab. I would recommend avoiding `autoOpen` for this reason and instead call the [open method](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Methods) on the multiselect after the user navigates over to that tab.
