### ISSUE TITLE
Small Custom Work Order $$$

### ISSUE THREAD

**Issue by ShaneTaylor** [ehynds/jquery-ui-multiselect-widget#612]
Hey Eric, 

I went to your profile, but nothing loads when I click on your website to contact you... 

I was wondering if I could get you to do some $custom work for me. It's a chained-select search menu that works with a 3rd party IDX real estate database. I think I have most of it figured out and just need a pro to make it do what I need it to do. 

State > County > City > Neighborhood > 

I just need you to set up the basics for me and I can do all of the data entry. And I need you to edit out any files or code that you don't think I'll need. I'm trying to keep the smallest amount of code on my server.

Please let me know as I really hope you can find the time to help me. Thanks in advance :)

Shane Taylor

**Comment by mlh758** [comment]
You should try reaching Eric on Twitter rather than on the issue tracker for this project.
