### ISSUE TITLE
.hide(), .show(). .toggle() and others do not work

### ISSUE THREAD

**Issue by JacobChrist** [ehynds/jquery-ui-multiselect-widget#613]
Just tried a .hide() method and it did not work.  The .show() method works but reveals the original hidden drop down box.

**Comment by mlh758** [comment]
If I have a multiselect on the page and call hide/show on it it seems to behave as expected.

    $(".ui-multiselect").hide()

hides the select.

Perhaps you are calling these on the button rather than the menu? Also, what version of jQuery is in use?

**Comment by mlh758** [comment]
Closing due to lack of response and age of issue. I can't reproduce this unfortunately.

**Comment by vientoho** [comment]
I think he means that the specific drop down list cannot be hide.
I have also met the same issue and a workaround is as below,
$("#ddl").next(".ui-multiselect").hide();    // instead of $("#ddl").hide()

**Comment by mlh758** [comment]
If you want to open/close a specific drop down, why not use the open/close methods?
