### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by SoftCircuits** [ehynds/jquery-ui-multiselect-widget#614]
Is this project still active? I am seeing a number of issues.

For example, I am having some issues related to the control width. When the control is first initialized, the width is not set to the width of the original `<select>` control. And after I do a refresh, it sets the width by calling `outerWidth()` on the original `<select>` control; however, that control is hidden and the result is not reliable (or correct, in my case).

>The value reported by .outerWidth() is not guaranteed to be accurate when the element or its parent is hidden.

Source: http://api.jquery.com/outerwidth/

Perhaps it should obtain the width before hiding it initially.

In addition, it might be nice to be able to control the z-index setting of the dropdown to play nicely with other elements. And it really needs an option to display "All Checked" when all items are checked. (As a quick way for the user to know that no more need to be checked if they want them all checked.)

JavaScript and jQuery are not my main language but I'm prepared to work through these issues. But it would be nice if either A) the original author could fix these or B) my changes could be incorporated into the project so that I could still benefit from any changes made by the author.

**Comment by dspiegel** [comment]
@softcircuits 

Not sure what is going on with this project. Has not been touched for years, but it works fairly well.

I added some code to fix the issue you refer to:

- 1. Added maxWidth to default options (~ line 32)
```javascript
options: {
  ...
  minWidth: 225,
  maxWidth: 250,
  classes: '',
  ...
}
```
- 2. Added Test for maxWidth inside _setButtonWidth() function (~ line 433)
```javascript
    _setButtonWidth: function() {
      var width = this.element.outerWidth();
      var o = this.options;

      if(/\d/.test(o.minWidth) && width < o.minWidth) {
        width = o.minWidth;
      }

      // Add ability to control max width of  DAS 07/23/2015
      if (/\d/.test(o.maxWidth) && width > o.maxWidth) {
        width = o.maxWidth;
      }

      // set widths
      this.button.outerWidth(width);
    },
```
 - 3. Now I just add maxWidth to my options when creating multiselect and it will stay under that size. No guarantees, your mileage may very.

- Dave

**Comment by jitbit** [comment]
I fixed this by simply moving the "this.element.hide();" line to the end of "_create" function

**Comment by mlh758** [comment]
@jitbit I just verified your fix. Waiting to hide the element until the end of `_create` ensures that the `refresh` function has executed and set the width appropriately.

This has been added.
