### ISSUE TITLE
Documentation site is 502

### ISSUE THREAD

**Issue by underblob** [ehynds/jquery-ui-multiselect-widget#616]
http://www.erichynds.com/jquery/jquery-ui-multiselect-widget/
502 Bad gateway

**Comment by onlygecko** [comment]
Google helped out. It seems the documentation page moved to: http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/

@ehynds: Would you please update the link on the readme?

**Comment by rafinha90** [comment]
@onlygecko This is not the documentation, just some demos.

@ehynds I know you are not working on the project anymore, but a lot of people still uses it. At least put the documention here on GitHub, so new people can continue working with/on it.

**Comment by mlh758** [comment]
@underblob  @onlygecko I've moved the docs to the repository's wiki. Let me know if you see any issues.

**Comment by arkuuu** [comment]
The link mentioned above [http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/](http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/) gives an HTTP 500 error.

**Comment by mlh758** [comment]
Looks like the whole site is down.

**Comment by mlh758** [comment]
You can still run the demos from https://github.com/ehynds/jquery-ui-multiselect-widget/tree/master/demos

The wiki on this GitHub is kept up to date as well.
