### ISSUE TITLE
Can we add format as one of the attributes of multiselect widget.

### ISSUE THREAD

**Issue by charuag** [ehynds/jquery-ui-multiselect-widget#620]
I want to create a select dropdown using multiselect widget with options containing name and address. And, using jquery would like to format this address.

For Example, 
`<option>John Doe - 78 West Main St Apt 3A, Bloomsburg, PA 12345</option>
<option>Jane Doe - 78 West Main St Apt 3A, Bloomsburg, PA 12345</option>`

Can this be done using multiselect widget?

**Comment by mlh758** [comment]
You can add styles to the `<option>` tags and those CSS classes will be inherited by the list items that make up the multiselect.

Beyond that, your options are pretty limited: http://stackoverflow.com/questions/1895476/how-to-style-a-select-dropdown-with-css-only-without-javascript

Unfortunately, the plugin doesn't have native support any fancy formatting of the list items.
