### ISSUE TITLE
Get checked items in uncheckAll()

### ISSUE THREAD

**Issue by Emerald214** [ehynds/jquery-ui-multiselect-widget#623]
Hi, I have this snippet to get checked items before unchecking all items but it prints nothing. How to get checked items in uncheckAll()?

			uncheckAll: function() {
				...
				
				// Get checked inputs.
				var checkedCategories = $("[id^=ui-multiselect-categories-option-][aria-selected=true]");
				
				// It prints nothing.
				console.log(checkedCategories);
			}

**Comment by Emerald214** [comment]
This is my fix.

    uncheckAll: function(e) {      
  	  var checkeds = this.menu.find('input').filter(':checked');
	  
         this._toggleChecked(false);
         this._trigger('uncheckAll', e, checkeds);
    },

**Comment by Emerald214** [comment]
This is my fix.

uncheckAll: function(e) {      
	var checkeds = this.menu.find('input').filter(':checked');
	this._toggleChecked(false);
	this._trigger('uncheckAll', e, checkeds);
},

**Comment by Emerald214** [comment]
This is my fix.

    uncheckAll: function(e) {
  	  var checkeds = this.menu.find('input').filter(':checked');
      this._toggleChecked(false);
      this._trigger('uncheckAll', e, checkeds);
    },

**Comment by mlh758** [comment]
The `getChecked` method will also give you all the checked items. https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Methods

This would allow you to get all the currently selected items before triggering `uncheckAll`.
