### ISSUE TITLE
Up key cycles between the first and last item of the selection

### ISSUE THREAD

**Issue by FrancisMurillo** [ehynds/jquery-ui-multiselect-widget#624]
I noticed when the menu is open and you press the up key,
the selection goes to the first item, then the last item and back again.

Good component by the way

**Comment by FrancisMurillo** [comment]
I found the source of the behavior at the traverse function

```javascript
 _traverse: function(which, start) {
      var $start = $(start);
      var moveToLast = which === 38 || which === 37;
```

It seems here that the Up(38) and Left(37) button are really designed to do this behavior.
I find it a bit odd.

Is there a bug or issue that is being avoided because of this?

**Comment by mlh758** [comment]
@FrancisMurillo There is a pull request open to amend this behavior. Does Left(37) and Right(39) going to top and bottom make more sense to you from a usability standpoint?

**Comment by FrancisMurillo** [comment]
@mlh758 
The true concern is just the up and down button. As long as it goes up and down, then I guess it's okay.
