### ISSUE TITLE
little improvement: style and class in options

### ISSUE THREAD

**Issue by jk987** [ehynds/jquery-ui-multiselect-widget#626]
Hi,
I slightly "improved" the refresh() function because I wanted to use the widget this way:

```
<select ...>
  <option style='...'>...</option>
  <option class='...'>...</option>
</select>
```

I'm not familiar with the git and pull requests and such, so I just attached modified js file.

[jquery.multiselect.zip](https://github.com/ehynds/jquery-ui-multiselect-widget/files/51897/jquery.multiselect.zip)

**Comment by mlh758** [comment]
I'm sorry, but if you want to have this code included you will need to open a pull request. You would need to fork this repository using the button in the top right corner, create a branch (`git checkout -b <branch name>`) and then once you have your changes committed to your own repository you can open a pull request by following the instructions on the pull requests tab.
