### ISSUE TITLE
Hide on print

### ISSUE THREAD

**Issue by EochaiVerdonckt** [ehynds/jquery-ui-multiselect-widget#627]
When I want to print a page that contains the widget. The options are always shown! This sucks a lot. Who would want to print out all the options anyway? I have tried hiding the parent div that contains the form. The entire form is hidden when printing a page but not the options. Yes I have checked stack exchange.

**Comment by mlh758** [comment]
For reference, this issue appears in IE. In Chrome only the button is shown.

**Comment by mlh758** [comment]
@EochaiVerdonckt I added a fix to the css to prevent this issue from happening. Good luck!
