### ISSUE TITLE
I am binding data dynamically but issue is second time it does not reflect with the new changes.

### ISSUE THREAD

**Issue by RizwanSiddiqui** [ehynds/jquery-ui-multiselect-widget#629]
Hi,
I am binding data dynamically to multiselect-widget but the problem I am facing is that it is work first time to bind the correct data but the rest time it does not reflect  the changes in the widget. it shows previous data. i have also tried refresh function but refresh reflect  with previous data which I don't want.  What should I do?

**Comment by mlh758** [comment]
What are you using to re-bind the data?

`refresh` uses the original select list that the multiselect widget was instantiated on. Are you modifying the original select element before calling `refresh`?

**Comment by imikhn** [comment]
use this method : $("#select").multiselect("refresh");
as soon as you bind data to your select
