### ISSUE TITLE
cannot call methods on multi select prior to initialization attempted to call method 'widget' in multiselect dropdown

### ISSUE THREAD

**Issue by achaloza** [ehynds/jquery-ui-multiselect-widget#634]
I have two multi select drop-down use in same page. but i am manually check in check box using jquery then got this type of error.

"cannot call methods on multi select prior to initialization attempted to call method 'widget' in multiselect dropdown"

Using this type of code

$("#My_dropdown_id").multiselect("widget").find(":checkbox").each(function(){
   this.click();
});

**Comment by mlh758** [comment]
To my knowledge this is the intended behavior of jQuery widgets. See the [widget section](https://api.jqueryui.com/jquery.widget/) of the API documentation.
