### ISSUE TITLE
Problem with jQuery v1.11.3

### ISSUE THREAD

**Issue by eliaso** [ehynds/jquery-ui-multiselect-widget#637]
When using  jQuery v1.11.3, if you click CheckAll the checkboxes are not refreshed meaning that the X are not drawn. However I see that the message changes to 12 Selected (there are 12 menu items), so it is processing all internally but it's not "drawing" the X, so it looks like the options are not selected. The same thing happens with the Uncheck all,

Also when I select 2 items, the names of the items are not drawn I can only see the "," that used to be between the names.

**Comment by mlh758** [comment]
Is this jQuery 1.11.3 or jQuery UI 1.11.3?

Also, which version of the multiselect are you using?

**Comment by eliaso** [comment]
Thanks so much Michael, I am using:

 

*         jQuery 1.11.3 (attached)

 

*         jQuery MultiSelect UI Widget 1.14pre (attached)

 

*         also I’m using jqueryui 1.8 from http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js

 

 

Please let me know,

 

Thanks!,

Eli

**Comment by eliaso** [comment]
Sorry Michael, the problem is not compatibility with jquery, what is causing the Multiselect not to work is this script that has the template I’m using (form Metronic) :

 

 

    // Handles custom checkboxes & radios using jQuery Uniform plugin

    var handleUniform = function () {

 

 

Here I need to exit if it is a checkbox belonging to the multiselect, how can I do in javascript something like if the name of the checkbox start with “multiselect” return;

 

        if (!$().uniform) {

            return;

        }

        var test = $("input[type=checkbox]:not(.toggle, .md-check, .md-radiobtn, .make-switch, .icheck), input[type=radio]:not(.toggle, .md-check, .md-radiobtn, .star, .make-switch, .icheck)");

        if (test.size() > 0) {

            test.each(function() {

                if ($(this).parents(".checker").size() === 0) {

                    $(this).show();

                    $(this).uniform();

                }

            });

        }

    };

 

 

Can you tell me?

 

Thanks so so much!,

Eli

**Comment by mlh758** [comment]
No problem, just makes my life easier!

**Comment by mlh758** [comment]
Sorry, I didn't see the rest of this message when it came to my e-mail.

To get the name of an element with jQuery you can use $(selector).prop("name") to give you the name of the element. There are also selectors in pure javascript that can do this. Take a look at: http://www.w3schools.com/cssref/sel_attr_begin.asp You would use name instead of class in this case.
