### ISSUE TITLE
Jquery error on click plus SELECT title attr is manditory or length error

### ISSUE THREAD

**Issue by jbrozowski** [ehynds/jquery-ui-multiselect-widget#645]
Loaded the latest version and not happy with current build.  I even copied demo HTML to project and it did not work.
FYI - plug in requires that a select tag have a title property.  This was not the case in other version and logic should allow attr not found and ignore.

Click on select to open.
http://localhost:50959/Scripts/jquery-1.12.3.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method '400'

**Comment by mlh758** [comment]
A title tag is still not required. This is verified in both the unit tests and my current test page. I wouldn't recommend copying the html from the demos on the original site directly. Those haven't been maintained in quite some time. The wiki here on GitHub should have everything you need to get started while the demos show off available features.

**Comment by jbrozowski** [comment]
True.  My mistake I took master not tag 1.14.  That version is fine with demo and title is optional.  Please close out.
