### ISSUE TITLE
Version 1.14 filter not showing in demo html files using IE11

### ISSUE THREAD

**Issue by jbrozowski** [ehynds/jquery-ui-multiselect-widget#646]
Looking at example for project and demo version for filter is not displaying using multiselect().multiselectfilter();

bower_components/jquery-ui-multiselect-widget/demos/filter.htm

**Comment by mlh758** [comment]
I'm looking into this now to see if I can find an issue.

**Comment by mlh758** [comment]
I just opened up a test page (simple html, just a select with some css styles) and the filter is displaying in IE 11 and is searchable.

**Comment by jbrozowski** [comment]
Yes I used master instead of tag and filter is working as designed
