### ISSUE TITLE
minWidth auto is buggy

### ISSUE THREAD

**Issue by neonoxGER** [ehynds/jquery-ui-multiselect-widget#654]
hey,
when I use minWidth: 'auto' the size is 0px. Is there any chance to get width: 100% working?

**Comment by mlh758** [comment]
What version of the plugin are you currently using?

**Comment by neonoxGER** [comment]
jQuery MultiSelect UI Widget 1.16pre

**Comment by mlh758** [comment]
Do you have a fiddle or anything for where width: 100% isn't working for you?

**Comment by neonoxGER** [comment]
Nothing public, can I get in touch with you by e mail?

**Comment by mlh758** [comment]
From discussion, one bug for sure: minWidth expects a pixel value but it should fail more gracefully than going to a 0 width if it gets something else.
