### ISSUE TITLE
how to programmatically check given options ?

### ISSUE THREAD

**Issue by sebhaase** [ehynds/jquery-ui-multiselect-widget#655]
Is this already possible, or would this be a feature request !?

Right now I only find `checkAll()` and `uncheckAll()`

**Comment by mlh758** [comment]
Just to clarify, are you asking how to check the settings of the multiselect (options that have been set/configured)? Or are you trying to see what options have been selected in the drop down menu (what items a user has checked)?

**Comment by sebhaase** [comment]
I need the corresponfing `setChecked()` to the existing `getChecked()`.
I have something working now, I added these functions:
```javascript
    _setChecked: function(group) {
      var $inputs = this.inputs;
      var self = this;

      // gather an array of the values that actually changed
      var values = {};
      // toggle state on inputs
      $inputs.each(function() {
		  if(group.index(this)>=0) {
			  if(!this.checked) {
				  values[this.value] = +1; // flag
				  self._toggleState('checked', true).call(this);
			  }
		  } else {
			  if(this.checked) {
				  values[this.value] = -1; // flag
				  self._toggleState('checked', false).call(this);
			  }
		  }
	  });

//CHECK focus
//      // give the first input focus
//     $inputs.eq(0).focus();

      // update button text
      this.update();

      // toggle state on original option tags
      this.element
        .find('option')
        .each(function() {
          if(!this.disabled && values[this.value]) {
            self._toggleState('selected', values[this.value]>0 ).call(this);
          }
        });

      // trigger the change event on the select
      if($inputs.length) {
        this.element.trigger("change");
      }
    },
```
and 
```javascript
	setChecked: function(values) {
		var $inputs = this.inputs;
		var group = $inputs.filter(function() {
			return values.indexOf(this.value)>=0;
		});
		this._setChecked(group);
	},
```

**Comment by mlh758** [comment]
Before adding new methods, does [this section](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki) from the wiki help you? Scroll down to "Manually Check/Uncheck a Checkbox".

That said, I can see the value of being able to pass an array of values you want selected and having the widget handle it automatically.

**Comment by mlh758** [comment]
Also, in the methods you are adding it looks like you are changing the values on the original Select element. You could save a few steps by just doing that in the method and having the set method call `refresh`.

**Comment by sebhaase** [comment]
I just duplicated what I saw in `checkAll`.

Just now, I added an optional argument `noChangeEvent`.  Otherwise I would have to do heavy tricks, to get the multiselect initialized without inadvertently those selections being resaved...

**Comment by sebhaase** [comment]
Oh, oh -- I think I was just wasting time ...
I should have selected the  `<option>` before calling `multiselect()` the  first time ... done.   right !? no event either...

**Comment by mlh758** [comment]
Haha yeah if you just wanted to pre select values that would be the easiest
way. If you need to do something like that after calling multiselect then
you can still just change the original options in the select and call
refresh.

**Comment by mlh758** [comment]
I'm going to go ahead and close this one since it looks like you've found a way to accomplish what you needed with existing code.
