### ISSUE TITLE
another additions: selectedListSepartor and 

### ISSUE THREAD

**Issue by sebhaase** [ehynds/jquery-ui-multiselect-widget#656]
How about this:
I wanted to have multiple selected values on the button separated by newline.
So I added these lines of code:

```javascript

options: {
...
   selectedListSepartor: ', ',
...
}

update: function() {
...
        } else if(/\d/.test(o.selectedList) && o.selectedList > 0 && numChecked <= o.selectedList) {
          value = $checked.map(function() { return $(this).next().text(); }).get().join(o.selectedListSepartor);
        } else {
...
}

    _setButtonValue: function(value) {
		this.buttonlabel.text(value);
		this.buttonlabel.html(this.buttonlabel.html().replace(/\n/g,'<br/>'));
    },



```

**Comment by mlh758** [comment]
If you submit this as a pull request with a unit test I can review it more carefully and merge it in.

**Comment by mlh758** [comment]
For reference, it looks like this change would also resolve #590

**Comment by sebhaase** [comment]
I wish I would know how to do pull requests .. :-(
sorry.

**Comment by mlh758** [comment]
I added this feature. If you want HTML in the button text you'll need to use the method described in the [wiki, here](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Customization)

**Comment by sebhaase** [comment]
Good.
But you really should put in the special handling of `<br>`.
If I see that right, even your test case ist "messed up" ;-)
You don't what `<br>` in the `text()` .  you ONLY want it in the `html()`

So, please just put in this one-line change:
```
_setButtonValue: function(value) {
        this.buttonlabel.text(value);
        this.buttonlabel.html(this.buttonlabel.html().replace(/\n/g,'<br/>'));
    },
```
... would make it much more useful ;-)

**Comment by mlh758** [comment]
I put that test case in there just to show that it could be done. If you follow the link it shows how to override the _setButtonValue method to allow for HTML. That's been the route the widget has taken for a while. By overriding it you can make it do exactly your desired behavior.

**Comment by sebhaase** [comment]
I did read the wiki already.
But #590 would also prefer something simpler than overwriting methods...
so please reconsider.
My one line is no harm, if you mention that `\n` in `selectedListSepartor` is translated to a newline (i.e. `<br>`).
