### ISSUE TITLE
Multiselect taking lot of time to build with 5000 data values.

### ISSUE THREAD

**Issue by k2kkapoor** [ehynds/jquery-ui-multiselect-widget#659]
.multiselect().multiselectfilter(); is being called for each edit or add functionality of jqgrid, have like 5000 data values to be added to the multiselect dropdown. It is taking few seconds over the call mentioned in the beginning. Can anybody help to lessen this time.

**Comment by mlh758** [comment]
You could do your additions to the underlying select element, wait until you're done adding all the elements, and then call the `refresh` method instead of re-instantiating the widget on every add operation.

**Comment by k2kkapoor** [comment]
Is there a way to make this filter option conditional. Like making it as a button or link on which if clicked then only filter box is shown.

**Comment by mlh758** [comment]
You can call the filter plugin later after some event happens in your project.

    $("select").multiselect().multiselectfilter();
