### ISSUE TITLE
Problem when element is not visible on initialization

### ISSUE THREAD

**Issue by sebhaase** [ehynds/jquery-ui-multiselect-widget#660]
I'm having trouble with a `<select>` inside a ui-tab - i.e. when I open a dialog with tabs and the multiselect is not on the tab initially visible.
I guess the code section 

``` javascript
this.menu
          .show()
          .position(o.position)
          .hide();
```

is problematic..... what are you trying to do here ?
Similarly the `<select>` is not being hidden in this case.

**Comment by mlh758** [comment]
I'm not sure what's happening there. Do you have a fiddle or anything that can demonstrate the failure? That would help me investigate the issue.
