### ISSUE TITLE
Stopping the dropdown from being destroyed.

### ISSUE THREAD

**Issue by k2kkapoor** [ehynds/jquery-ui-multiselect-widget#661]
I am using a jqgrid and trying to create the drop down for once and reusing it again and again, as i have large data set due to which rebuilding the drop down every time is not an option, but the problem is once I am done with saving one row again if I edit or add a new row drop down is destroyed and can't be called again. 
Can anybody suggest how to stop the drop down from being destroyed.
Thanks in advance.

**Comment by mlh758** [comment]
The most direct way of getting new options into the widget is to add them to the underlying select element and then calling `refresh` on the widget.

Newer versions of jQuery UI let you call an `instance` method. You could use the menu property of the instance to manually add additional inputs.
