### ISSUE TITLE
Blog example won't run on Chrome/Edge + 2 failed unit tests?

### ISSUE THREAD

**Issue by tomasmed** [ehynds/jquery-ui-multiselect-widget#665]
When I run the example (which is being ran by JFiddle) on Chrome or Edge/IE I will not get the multiselect widget instead I just get the native html select.

**Comment by mlh758** [comment]
Have you run the unit tests from the master branch? Those have all been updated. A lot of the examples from the original website are out of date.

**Comment by tomasmed** [comment]
I didn’t run them from the master branch, I’m assuming they are working, I’ve been working with the plugin throughout the morning and I got it to work alright, I think that there was some issue with the dependencies not working. I’m thinking there is no problems code wise, maybe just the blog post that explains the plugin is a little bit outdated.

**Comment by mlh758** [comment]
Yeah, you might want to use the wiki for documentation moving forward: https://github.com/ehynds/jquery-ui-multiselect-widget/wiki
