### ISSUE TITLE
WIKI: Customization _setButtonValue()

### ISSUE THREAD

**Issue by RuZniki** [ehynds/jquery-ui-multiselect-widget#666]
https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Customization
```
$( "#foo" ).multiselect().data( "multiselect" )._setButtonValue = function( value ) {
   this.buttonlabel.html( value );
};
```
Instead I use data( "**echMultiselect**" )
```
$( "#foo" ).multiselect().data( "echMultiselect" )._setButtonValue = function( value ) {
   this.buttonlabel.html( value );
};
```
I'm not sure about using latest version, so is it outdated wiki need to be update?

**Comment by mlh758** [comment]
I think you might be right, I'll take another look at the code and see if I need to change the wiki.

**Comment by mlh758** [comment]
You were right, the Wiki has been corrected. Thank you for bringing this to my attention.
