### ISSUE TITLE
1.16 Minified Files are encoded in UTF-16 with dos line endings

### ISSUE THREAD

**Issue by thewunder** [ehynds/jquery-ui-multiselect-widget#667]
This causes issues when combining with any other javascript... 

They should be encoded in UTF-8 like every other file out there...

**Comment by mlh758** [comment]
You're right, I'll put up a fix for this.

Apparently if you use PowerShell instead of command prompt when creating a text file it defaults to UCS2-LE BOM.

**Comment by mlh758** [comment]
It's been re-released: https://github.com/ehynds/jquery-ui-multiselect-widget/releases/tag/v1.17

Thank you for bringing this up.
