### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by abzainuddin** [ehynds/jquery-ui-multiselect-widget#669]
First of all, thanks for all the great work!

I use npm to install dependencies, and was wondering if you are interested to publish this package to npmjs.com. If so, then you need:
- an account on npmjs
- a package.json (see https://docs.npmjs.com/getting-started/using-a-package.json)
- use semver (http://semver.org/)

I could help setup with some of this. Let me know what you think.

**Comment by mlh758** [comment]
I think this is a good idea. I can get an account going and start following the rules in semver more strictly after this last release.

I'll have to look at working on the package.json. I've used those to build projects pretty frequently, but I imagine this will be different

**Comment by medhatdawoud** [comment]
@abzainuddin This is urgently needed on npm please, and thanks for your efforts

**Comment by mlh758** [comment]
Sorry for the delay, I've been really busy with my day job.

Here you go: https://www.npmjs.com/package/jquery-ui-multiselect-widget
