### ISSUE TITLE
'checkall' and 'uncheckall' are fired twice

### ISSUE THREAD

**Issue by SergeyBan** [ehynds/jquery-ui-multiselect-widget#670]
I bind my multiselect widget with 'change' event. When I click 'checkall' or 'uncheckall' it is handled twice by handler that is bound with widget via 'change' event. 
Is it bug or am I doing something wrong?

**Comment by mlh758** [comment]
To test this, I took the "preselected" demo included with the widget and I bound a listener to the change event like so (I added an ID to the select to make it easier):

`$("#test").on("change", function() {console.log("hello");});`

I tried checking and unchecking values, then clicked check all and uncheck all. The event only ever fired once each time.
