### ISSUE TITLE
how to make it work on IE8

### ISSUE THREAD

**Issue by zff1222** [ehynds/jquery-ui-multiselect-widget#673]
Yes, IE8 :(
the widget seems to work nearly perfect ,except the "filter" plugin on IE8 .
So ,is there any way to make it work on IE8?

**Comment by mlh758** [comment]
I haven't been making any particular effort to maintain IE8 support with
this plugin. If you're on the latest version you could try using 1.13.
Check the patch notes since then to make sure you don't need any of the new
features or fixes.

**Comment by zff1222** [comment]
@mlh758 
Thanks!
I've added 'keyup' and 'click' events to the latest version like 1.13 dose.It works.
