### ISSUE TITLE
filter plugin don't work when jquery-ui dialog option is { modal: true }

### ISSUE THREAD

**Issue by flyingQuQu** [ehynds/jquery-ui-multiselect-widget#675]
when put multiselect in a jquery-ui dialog while the dialog option is { modal: true }, the filter plugin's input can not be focused.

$("select").multiselect({
    "multiple": false,
    "header": true,
    "selectedList": 1
}).multiselectfilter();

$("#dialog").dialog({ width: 800, height: 640, modal: true, autoOpen: true, title: ""});

![image](https://cloud.githubusercontent.com/assets/12640805/21607133/112a61f0-d1ef-11e6-903a-86b6f7d51fe9.png)

**Comment by mlh758** [comment]
Would you be able to set up a [jsfiddle ](https://jsfiddle.net/) demonstrating the issue?

**Comment by flyingQuQu** [comment]
@mlh758 here is the test code https://jsfiddle.net/flyingQuQu/ghcrgvqm/1/

**Comment by mlh758** [comment]
Thank you, that helps a lot.

**Comment by mlh758** [comment]
I found two issues and one will require changes from me that will be available for you today.

The second thing is that the filter input ends up behind the dialog. You can use the `appendTo` option to make sure it ends up in the right place. 

Here's your fiddle back with everything working: https://jsfiddle.net/ghcrgvqm/4/

That has the latest changes that I'll be making to the repo today.

**Comment by mlh758** [comment]
I ended up making another commit, you don't need the appendTo attribute at all now. We should have been following the jQuery spec on [stacking elements](https://api.jqueryui.com/theming/stacking-elements/) as demonstrated in UI Autocomplete [here](https://github.com/jquery/jquery-ui/blob/master/ui/widgets/autocomplete.js).
