### ISSUE TITLE
Height Auto Set

### ISSUE THREAD

**Issue by flyingQuQu** [ehynds/jquery-ui-multiselect-widget#676]
I change the soucre code so that the height can be auto setted.

https://jsfiddle.net/flyingQuQu/ghcrgvqm/3/

![image](https://cloud.githubusercontent.com/assets/12640805/21631669/f2751144-d278-11e6-915a-2373a4f8d6aa.png)

**Comment by mlh758** [comment]
What is your goal with those code, and what is the use case?

Also, you might consider opening a pull request instead of sending me a screenshot of code.

**Comment by flyingQuQu** [comment]
@mlh758 
The situation is:
Since the options are dynamically generated by querying a database, the number of options can't be sure. 

Sometimes, the number is too small**(likes 1)**, and the height of multiselect menu is fixed**(175)**, so the multiselect menu contains too many blank content.
![image](https://cloud.githubusercontent.com/assets/12640805/21665498/cf8baf6c-d327-11e6-96d0-975d3143b5c9.png)

Some users think it's too ugly.

I add some code so that the multiselect has a maxHeight function. https://jsfiddle.net/flyingQuQu/ghcrgvqm/3/
When the sum of every menu option height is less than the fixed height of multiselct menu, the height of multiselct menu is set at he sum of every menu option height.
![image](https://cloud.githubusercontent.com/assets/12640805/21665832/0a7028f0-d329-11e6-8dc8-84e0af795f88.png)

**Comment by mlh758** [comment]
Makes sense, I'll start adding this into the code base.
