### ISSUE TITLE
Performance tuning...

### ISSUE THREAD

**Issue by sebhaase** [ehynds/jquery-ui-multiselect-widget#677]
Hi...
I have about 1500 `<option>s` in my `<select>`.
I'm changing the selections from my javascript code,
and then calling `.multiselect("refresh")` takes more than 1 sec.

Could that be speed up in general ?   Or at least for the frequent case where nothing is selected ?

Where in the code base should I look ?

Thanks, Sebastian

**Comment by mlh758** [comment]
I've just made a commit to master that allows you to add and remove options without a refresh.

`addOption` and `removeOption` are what you're looking for. I'll update the [wiki](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki) with the information

**Comment by sebhaase** [comment]
Great ! Please refer the exact wiki link - when it's ready - here ...

**Comment by sebhaase** [comment]
I found them at https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Methods

I just realized - I don't need to add or remove options - but I need to sync the selected-states from the underlying `<select>`

**Comment by mlh758** [comment]
> Could that be speed up in general ? Or at least for the frequent case where nothing is selected ?

For that case, I'm assuming you know at this point nothing is selected, could you just call the `uncheckAll` method?

You could also use the new `getLabels` method, find the ones you just updated, and then call `click` on them.

**Comment by mlh758** [comment]
I've updated the pertinent example on the [main wiki page](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki) with something that might be more illustrative. If you're already updating the `<select>` this wouldn't be much different and would negate the need for a refresh.
