### ISSUE TITLE
What files should be host on cdnjs?

### ISSUE THREAD

**Issue by hare1039** [ehynds/jquery-ui-multiselect-widget#678]
Hi, I am a member from cdnjs. We'd like to host this library on cdnjs. 
What files in this library should we host?
Thank you !

**Comment by mlh758** [comment]
Both the css files:
https://github.com/ehynds/jquery-ui-multiselect-widget/blob/master/jquery.multiselect.css
https://github.com/ehynds/jquery-ui-multiselect-widget/blob/master/jquery.multiselect.filter.css

And the two JS files:
https://github.com/ehynds/jquery-ui-multiselect-widget/blob/master/src/jquery.multiselect.js
https://github.com/ehynds/jquery-ui-multiselect-widget/blob/master/src/jquery.multiselect.filter.js

Both those sets can be concatenated together and minified. Do you plan on hosting them under their respective versions or just regularly grabbing what is sitting on master?

**Comment by hare1039** [comment]
We plan to host them under their respective versions. We have a bot that grabs the needed files to cdnjs for each git tag, and it is perfectly fine to change the file structure in the future release. If you want to change the files that needs to be host on cdnjs, fire an issue on cdnjs repo!

**Comment by mlh758** [comment]
If you're grabbing the releases then go ahead and do the minified .js files instead.
