### ISSUE TITLE
Bower installs very very old version

### ISSUE THREAD

**Issue by gregfr** [ehynds/jquery-ui-multiselect-widget#680]
Greetings
I've just installed via bower and got the very old version 1.4.1.
Is there a way to install the latest with bower?
TIA

**Comment by gregfr** [comment]
Several other tickets here on the subject but they are not open...

**Comment by mlh758** [comment]
I'm not too familiar with Bower, it's possible the previous repo owner set it up. I'll have to see what I can do. The project is on npm if that is a workable alternative for you.

**Comment by mlh758** [comment]
Never mind, it turns out Bower walks the tagged versions and only looks at releases that follow semantic versioning. I was getting ready to release 2.0.0 anyway so I went ahead and did so. Bower now has the latest version on it.
