### ISSUE TITLE
_bindHeaderEvents only check for ui-multiselect-all

### ISSUE THREAD

**Issue by akeonly** [ehynds/jquery-ui-multiselect-widget#681]
I add a predefined filters apart from "Check all" and "Uncheck all" e.g. filter from item that contains certain word. but when I click it will uncheck all selected item from the list first since the logic in _bindHeaderEvents only checks for $(this).hasClass('ui-multiselect-all'). Please see photo
![2017-02-01_14-59-10](https://cloud.githubusercontent.com/assets/7870829/22499051/185259cc-e88f-11e6-9988-470c07b8d708.png)

**Comment by mlh758** [comment]
Ah, yeah the current mechanism assumes there will only be those pre-defined buttons. I can update this to be more robust. I'll have the change up soon.

**Comment by akeonly** [comment]
Thanks!
