### ISSUE TITLE
update() must return undefined

### ISSUE THREAD

**Issue by sebhaase** [ehynds/jquery-ui-multiselect-widget#682]
... otherwise  jquery-ui  in `$.widget.bridge`  will break `.each()` loop and only first element will get updated !

I have a line like this:
`$any_tetstyle.multiselect("update");`
`$any_tetstyle` in a jQuery object of 3 multiselect objects.  Only the first is being updated !

Likely there are other functions with same bug.
-S.

**Comment by mlh758** [comment]
I finally got a chance to do a little investigating on this issue. Returning something does not break `each`, you just can't chain methods that return something other than a jQuery object or `undefined`. 

Unless I'm missing something, there has to be something else going on. I'm referencing their guides [here](https://learn.jquery.com/jquery-ui/widget-factory/widget-method-invocation/)

**Comment by mlh758** [comment]
Are you using jQuery UI 1.11.0+?

**Comment by sebhaase** [comment]
jquery-ui-1.11.4

**Comment by mlh758** [comment]
You were right, `update` needed to return `undefined`

I pushed a fix for this.
