### ISSUE TITLE
.ui-multiselect-optgroup-label  was changed to .ui-multiselect-optgroup

### ISSUE THREAD

**Issue by sebhaase** [ehynds/jquery-ui-multiselect-widget#683]
in `jquery.multiselect.filter.js`  around line 152 
`this.instance.menu.find(".ui-multiselect-optgroup-label")`
and following..

the new class name `.ui-multiselect-optgroup` must be used.
-S.

**Comment by sebhaase** [comment]
line 154 should bre changed to
`var isVisible = $this.children("li").filter(function() {`

apparently optgroups are now nested differently from before ...

**Comment by mlh758** [comment]
Are you sure you're looking at the right version? These changes [are already in place](https://github.com/ehynds/jquery-ui-multiselect-widget/blob/master/src/jquery.multiselect.filter.js#L156)

**Comment by sebhaase** [comment]
Still not working correctly.
I'm really sorry for the confusion - I did forget to copy the filter files from the git repository to the docroot folder.  But it appears that the new version  shows only the *first* option  when opened the multiselect the first time. After entering any character into the filter input an removing then it, i see the expected full list...

**Comment by mlh758** [comment]
What browser are you using? I don't see this issue at all.

Are your css files also up to date?

**Comment by sebhaase** [comment]
google chrome on osx.   css should be up to date.

**Comment by mlh758** [comment]
What happens if you open the filter demo file?

There's 2 selects in that demo, one with option groups and one without. Both of those behave as expected for me using Chrome and IE on Windows. What happens when you try?

**Comment by mlh758** [comment]
Closing this for now due to lack of response and I can't reproduce.
