### ISSUE TITLE
original select field value not available 

### ISSUE THREAD

**Issue by coda-apps** [ehynds/jquery-ui-multiselect-widget#685]
I am plugging this onto an existing <select> field in form, which submits to a Classic ASP server side process. 
When i **request.form** for the original field name, i only get one value. When i **request.form** for the plugin-generated **multiselect_** fields - they come up empty, because it seems that they are not generated within the <form> - thus when i submit, they are not there.

How can i overcome this, so that the values are available on the server side?

Thank you

**Comment by coda-apps** [comment]
Sorry - my bad. i had not put the multiple="multiple" in the <select>
Hopefully others can learn from this :-)

Thanks

**Comment by mlh758** [comment]
I love it when issues close themselves while I'm still brushing my teeth :)

**Comment by coda-apps** [comment]
:-)
