### ISSUE TITLE
v2.0.0 refresh method problem

### ISSUE THREAD

**Issue by flyingQuQu** [ehynds/jquery-ui-multiselect-widget#686]
I have just tried the v2.0.0.

When i have two select, while each one doesn't have id, after i called the "refresh" method, the second one doesn't work normally and it always affect the first one.

But when the select both have id, the problem doesn't exist.

here is the test code https://jsfiddle.net/ghcrgvqm/5/

**Comment by mlh758** [comment]
I think this is related to #682

**Comment by flyingQuQu** [comment]
@mlh758 Yo man, have the problem been solved yet?

**Comment by mlh758** [comment]
Not yet, my day job has taken priority for the last few weeks. You're
welcome to open a pull request.

**Comment by mlh758** [comment]
Are you using jQuery UI 1.11.0 or greater?

**Comment by mlh758** [comment]
Never mind, saw that your fiddle has 1.11.4.

**Comment by mlh758** [comment]
In your fiddle I see `refresh` being called 8 times. 4 for the initialization, and 4 for the line `$("select").multiselect("refresh");`

That seems to be working as intended.

**Comment by flyingQuQu** [comment]
@mlh758 
In the fiddle, in the first row, the second select always affects the first on. 
When i chose one option in the second select, the first select will be selected too, that's normal? T_T

**Comment by mlh758** [comment]
No, but you didn't describe that problem until now...

**Comment by mlh758** [comment]
To specify the problem further: This issue is specific to the labels for the checkboxes. Clicking the checkboxes themselves still changes the correct menu, as does using the keyboard to select items or the header options. There's something wrong with how the labels are listening to clicks.

**Comment by mlh758** [comment]
The error is in `_makeOption`, the input ID is assigned as 
```
var inputID = 'ui-multiselect-' + multiselectID + '-' + (option.id || id + '-option-' + this.inputIdCounter++);
```

which creates duplicate IDs if the multiselect doesn't have an ID.

**Comment by mlh758** [comment]
I've updated master with a fix and corresponding unit tests.

If this solves your problem I'll tag another release right away.

**Comment by flyingQuQu** [comment]
@mlh758 
Thanks a lot, it solved the problem.

**Comment by mlh758** [comment]
I'll get a tag out soon.
