### ISSUE TITLE
multiselect("addOption") should show optgroup if first entry

### ISSUE THREAD

**Issue by sebhaase** [ehynds/jquery-ui-multiselect-widget#687]
I'm not clear about this - but I think, it might be a bug ...
Having an empty optgroup without any option, makes that optgroup hidden
 (<ul class="ui-multiselect-optgroup" style="display: none;">)
After adding an option into that optgroup should make it automatically visible .

**Comment by mlh758** [comment]
You have to call `refresh` after adding options for it to reflect the changes.

**Comment by sebhaase** [comment]
I'm trying to circumvent `refresh` because I have more than 1000 Elements in my <select>  und refresh need multiple seconds....

**Comment by mlh758** [comment]
I just used the basic demo under the demos folder and removed all options from Group One. The option group is still visible. Calling `addOption` populated an option under that option group.

**Comment by mlh758** [comment]
Can you confirm you are still seeing this with the latest code in master, or provide a fiddle or something? Since I wasn't seeing the issue I am planning on closing this soon.
