### ISSUE TITLE
filter-plugin: text-input should hold keyboard focus

### ISSUE THREAD

**Issue by sebhaase** [ehynds/jquery-ui-multiselect-widget#688]
For long lists of options the filter plugin is really great !
It is frustrating however that moving the mouse immediately makes the text input  lose focus and you cannot continue typing before having to click first into the text field again.

**Comment by mlh758** [comment]
If you're using the 2.x version of the widget you can use shift-tab to quickly get back to the filter input.

These [other shortcuts](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Keyboard-Navigation) might be helpful for you as well. You can use the filter without ever touching your mouse now.

At this point I don't have any plan on changing how the mouse focuses elements.
