### ISSUE TITLE
no method of check specified value 

### ISSUE THREAD

**Issue by martinzh717** [ehynds/jquery-ui-multiselect-widget#689]
wanna check a collection of value as default, but no method found.

pls help, 3ks.

**Comment by mlh758** [comment]
Are you saying you want to have a collection of values pre-selected in the widget?

**Comment by LawlietZe** [comment]
i wanna it too

**Comment by mlh758** [comment]
You want to be able to pre-select a collection of items in the widget?

https://github.com/ehynds/jquery-ui-multiselect-widget/wiki#manually-check-or-uncheck-a-checkbox

If you add the `selected` attribute to the options and refresh the widget (or before the widget is constructed) you will have a collection of selected items.
