### ISSUE TITLE
jQuery UI dependency raised for the filter plugin

### ISSUE THREAD

**Issue by Celos** [ehynds/jquery-ui-multiselect-widget#690]
This is a documentation issue: v2 seems to have raised the jQuery UI dependency to 1.11 (specifically the calls to the instance method), which is not mentioned in the release notes nor the files themselves.
```
 * Depends:
 *   - jQuery 1.4.2+
 *   - jQuery UI 1.8 widget factory
```
and 
```
 * Depends:
 *   - jQuery UI MultiSelect widget
```

**Comment by mlh758** [comment]
Ah! I'll fix that. That's why I jumped to 2.0 instead of another 1.x
release.

**Comment by mlh758** [comment]
Depends and wiki updated. Thank you for bringing this up.
