### ISSUE TITLE
Positioning issue in scrollable container

### ISSUE THREAD

**Issue by apisselhoy** [ehynds/jquery-ui-multiselect-widget#691]
I am using the widget in a scrollable container and set the "appendTo" to the offsetParent so it scrolls with its button. The problem is that the menu is positioned with .offset() and so this doesn't work if the offsetParent is not at position (0,0).
I would suggest to introduce a new config option to switch positioning between
this.button.offset();
and
this.button.position();
in the position-function (file jquery.multiselect.js around line 725).

**Comment by mlh758** [comment]
I [changed how the menu is positioned](https://github.com/ehynds/jquery-ui-multiselect-widget/blob/master/src/jquery.multiselect.js#L874) in 2.0.0.

By providing a position option, the menu will be positioned using the provided position object and `position` otherwise it will default to `offset`.
