### ISSUE TITLE
Example link broken

### ISSUE THREAD

**Issue by avoliva** [ehynds/jquery-ui-multiselect-widget#692]
[Example](https://camo.githubusercontent.com/e999eef06fba175af7541f2e34c61cfba9db18d9/687474703a2f2f7777772e6572696368796e64732e636f6d2f6578616d706c65732f6a71756572792d6d756c746973656c6563742f73637265656e73686f742d7769646765742e676966)

`Error Fetching Resource`

**Comment by mlh758** [comment]
Where is this example link located?

**Comment by abzainuddin** [comment]
This one is also broken:

![link](https://cloud.githubusercontent.com/assets/3865520/24604538/6a487418-1865-11e7-8a25-65146a47ccf2.png)

Found on http://www.erichynds.com/blog/jquery-ui-multiselect-widget

**Comment by mlh758** [comment]
I have no control over the original website. Please refer to the wiki on
GitHub instead.

**Comment by mlh758** [comment]
If you find dead links in the Wiki though, please let me know and I'll fix those.

**Comment by avoliva** [comment]
The link is broken on the wiki page too: https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Usage

**Comment by mlh758** [comment]
I removed that link from the Wiki page.
