### ISSUE TITLE
demo page has an internal server error

### ISSUE THREAD

**Issue by kccarter76** [ehynds/jquery-ui-multiselect-widget#693]
I am trying to find the usage example for the filter plugin and the page you have provided will not load correctly.

**Comment by mlh758** [comment]
Is this from the wiki on GitHub or the original website?

**Comment by kccarter76** [comment]
http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/

**Comment by mlh758** [comment]
Yeah I have no control over the original website. Please use the wiki on
GitHub instead.
