### ISSUE TITLE
how to change color of ddl on  close event 

### ISSUE THREAD

**Issue by mattasanthoshreddy1** [ehynds/jquery-ui-multiselect-widget#695]
active ddl should be colored(when i select some options on dll it should be shown with some color)

**Comment by mattasanthoshreddy1** [comment]
no when I change or click on ddl the ddl color should change

**Comment by mattasanthoshreddy1** [comment]
yes button color should change

**Comment by mlh758** [comment]
What are you referring to when you say ddl? There are no definition lists in this widget.

**Comment by mlh758** [comment]
In any case, if you want to change the button color if there are checked items after the menu is closed, something like this will work:

    $("select").multiselect({ 
        close: function() {
            $this = $(this);
            if($this.multiselect("getChecked").length) {
                $this.multiselect("getButton").addClass("some-color-class")
            }
         }
      });

Basically, set a listener to the close callback that checks if there are any checked items then add a class of your choosing to the button.
