### ISSUE TITLE
multiselct("disable") causes error in IE8

### ISSUE THREAD

**Issue by flyingQuQu** [ehynds/jquery-ui-multiselect-widget#697]
multiselct("disable") causes error in IE8.

the error is in 
```
672          matchedInputs = checkboxes.querySelectorAll("input:enabled");
673          for(i = 0; i < matchedInputs.length; i++) {
```

**Comment by mlh758** [comment]
Yeah IE8 has limited support for `querySelectorAll`. I haven't been supporting anything prior to IE10 for quite a while though.

I changed the disable method  at 4ee469b8  since it was doing a lot of extra work and causing major slow downs with large selects.
