### ISSUE TITLE
multiselect panel does not open in boottrap modal() window

### ISSUE THREAD

**Issue by coda-apps** [ehynds/jquery-ui-multiselect-widget#699]
I have a multiselect object in a hidden bootstrap modal window.
this window can be activated and opened as a standard modal window, using:
`<a class="btn btn-warning" href="#chargeAdd" data-toggle="modal">open</a>`

But even though the multiselect has been activated (ie, i do not see a standard multiple select drop down) - i cannot open the panel of checkboxes to make selections. nothing happens.

using an old installation of bootstrap 2.0.3

Thanks

**Comment by mlh758** [comment]
What version of the widget are you using?

**Comment by coda-apps** [comment]
* jQuery MultiSelect UI Widget 2.0.0

**Comment by mlh758** [comment]
You will definitely want to bump up to 2.0.1, there's an important bug fix for when multiple widgets are on the page.

Are you initializing the multiselects while the modal is still hidden? Or do you have a callback to initialize them once it becomes visible? The `outerHeight` method isn't reliable on hidden elements so we usually recommend you either initialize the widgets and then hide the element they are on, or wait to initialize them until they become visible.

Let me know if that helps.

**Comment by coda-apps** [comment]
Thanks for your response.
I have downloaded the updated file and am using it,

i am initializing the script when the modal is open (via a listen event:

`
	$( "#chargeAdd" ).on('shown', function(){
		$(".multiSelect").multiselect(); 
	});
`
and it has fired - because i can see that the select is no linger a standard multiple select downdown, but rather how it looks as a "multi select" object.
but when i click on it, nothing happens, other than it getting the blue-ish 'active' styling.

**Comment by mlh758** [comment]
Is it possible for you to create a fiddle demonstrating this?

If not, can you determine if the `open` method on the widget is being reached?

It could also be useful to determine if the menu is appearing, and is just hidden behind the modal.

You could try using the `appendTo` option to bind the widget to an element you know will be at the front of the stacking order and see if it appears there.

**Comment by mlh758** [comment]
Did `appendTo` fix the issue for you? Any other follow up?

**Comment by coda-apps** [comment]
Thanks for following up!
I actually tried to setup an initial jsfiddle, but its giving me JS errors when i include the library.
https://jsfiddle.net/kneidels/oa14mgkq/11/

Any ideas?

Thanks again!

**Comment by mlh758** [comment]
You didn't include jQuery, jQuery UI, or the multiselelect widget in your fiddle.

Here's an updated version with all the libraries included:
https://jsfiddle.net/oa14mgkq/12/

It looks like the widget is opening behind the modal window instead of within it.

**Comment by mlh758** [comment]
It looks like you are manually creating the modal window instead of using a method to build it. Modals should have the `ui-front` class applied to them to indicate their presence in the stacking order.
https://api.jqueryui.com/theming/stacking-elements/

By adding `ui-front` to your modal, the menu appears over the modal as expected.

**Comment by mlh758** [comment]
Here's the fixed version just for your reference: https://jsfiddle.net/oa14mgkq/13/

**Comment by coda-apps** [comment]
That's amazing - thank you for your help!
