### ISSUE TITLE
multiselectclick event not firing on dynamically added select

### ISSUE THREAD

**Issue by arshadasgar** [ehynds/jquery-ui-multiselect-widget#700]
I have a select box which is added into the dom dynamically with jquery and applied `multiselect` on it which worked without any problem. I had a `multiselectclick` event which was firing normally for those multiselects which was there in the dom before. But for the dynamically added multi-selects, this event is not firing. What should I do?

**Comment by arshadasgar** [comment]
Instead of using the `multiselectclick` event outside the multiselect initializer I have used the `click` function inside it and solved the issue.

**Comment by mlh758** [comment]
I'm glad you were able to resolve the issue.
