### ISSUE TITLE
multiple:false & IE doc mode 10 cannot get selected value from change event

### ISSUE THREAD

**Issue by jay23606** [ehynds/jquery-ui-multiselect-widget#701]
The following is blank in document mode 10 but works fine in document mode 9 in Internet Explorer (jquery-1.9.1)

$('#mySelect').change(function(){
    alert($(this).find('option:selected').text())
});

I suppose I could look at the click or close event when creating the multiselect but I'm curious why this doesn't work.

**Comment by mlh758** [comment]
What happens if you use the `getChecked` method instead of trying to find them yourself?

**Comment by jay23606** [comment]
getChecked works:

```
$('#mySelect').change(function(){
    alert($(this).multiselect("getChecked")[0].value);
});
```
Thanks!

**Comment by mlh758** [comment]
Glad I could help!
