### ISSUE TITLE
100+ options causes blank space at bottom of page when dropdown is opened

### ISSUE THREAD

**Issue by esvi** [ehynds/jquery-ui-multiselect-widget#703]
Hi,

I'm going to try an explain this as best I can!

```
$('.countries').multiselect({
    maxHeight: 400
});
```
 
I have an issue where opening the dropdown (with 100+ options) creates a huge blank space at the bottom of the containing page, which is fixed by adding a maxHeight.

That maxHeight then causes a second scrollbar inside the dropdown, this I can live with but...

Selecting an option far from the top then breaks the dropdown when opening it again, so all you see is a blank list. All the items are way at the top out of view. 

Scrolling works, but it's not ideal for your user to see a blank page with no visible options.

Anyone have this issue and managed to fix it?

I'm using it with Bootstrap3 if that makes a difference.

Thanks in advance :)

**Comment by mlh758** [comment]
What version of the widget are you using?

**Comment by esvi** [comment]
Yeah, I was thinking that might actually be the problem, and I've updated the version. 

I'm re-doing a really old UI and they were using one from 2011! Hopefully updating won't break something somewhere else.

Will test again and update here tomorrow if it's still broken :)

Thanks.

**Comment by esvi** [comment]
I updated to the latest version of the widget, but the issue still exists. Any ideas?

![lists](https://user-images.githubusercontent.com/1637621/28354226-5cdf1176-6c5f-11e7-806d-27d647fcfcdf.PNG)

![lists2](https://user-images.githubusercontent.com/1637621/28354264-86f93932-6c5f-11e7-89c8-46eaa36e1b7c.PNG)

**Comment by mlh758** [comment]
I created a fiddle based on your description, I'm not having the issue without Bootstrap, could you use this to reproduce your issue?

https://jsfiddle.net/gn49x019/

**Comment by esvi** [comment]
I could not reproduce it, maybe the Bootstrap or some other JS is messing with it. 

Back to the drawing board I guess. Thanks anyway :)

**Comment by mlh758** [comment]
It probably is! But I'd like the widget to work well with Bootstrap if
possible. I was hoping you would add it to that fiddle and try to reproduce
the issue with Bootstrap on the page since then I would have something to
go with and investigate.

**Comment by esvi** [comment]
Turns out, another multiselect plugin's CSS was causing the issues. It was ALSO being used on that page for some reason. Options from both plugins were being used together as well. Explains why some options didn't always work, depending on which JS was loaded last I suppose.

It works perfectly when I remove that. Problem solved! :D

**Comment by mlh758** [comment]
Hahah well that would do it. Thanks for following back up.
