### ISSUE TITLE
multiselect().val(array) selected is incorect

### ISSUE THREAD

**Issue by Jehanramadhan** [ehynds/jquery-ui-multiselect-widget#705]
I have some multiselect option list :
Select Option
[ ] 1
[ ] 2
[ ] 3
[ ] 4
[ ] 5

when i run my code like this :

```
setSelected = function(invoiceSelected) {
  if (invoiceSelected.length) {
    console.log(invoiceSelected) // array [1,2,3,4,5]
      var selector = $(invoiceSelector).find('select') // invoiceSelector is my element
      selector.multiselect().val(invoiceSelected)
      selector.multiselect('refresh')
    }
}
```

only make selected number 1
whats wrong with my code?

**Comment by mlh758** [comment]
https://github.com/ehynds/jquery-ui-multiselect-widget/wiki 

There is a section on the wiki for manually selecting / pre-selecting items in the list.

**Comment by Jehanramadhan** [comment]
when i run $(select).multiselect('getLabels')
i got error like :

Uncaught Error: no such method 'getLabels' for multiselect widget instance

**Comment by mlh758** [comment]
What version of the widget are you using?
