### ISSUE TITLE
Repair demo page

### ISSUE THREAD

**Issue by ChoOo7** [ehynds/jquery-ui-multiselect-widget#708]
Hello

Please can you repair the demo page ?

http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/index.htm#filter

Thanks

**Comment by mlh758** [comment]
Unfortunately I don't have any control over the demo page. The original maintainer isn't supporting that anymore.

**Comment by ChoOo7** [comment]
Oups indead

If anyone interested, you can find it here
https://web.archive.org/web/20160318045658/http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/index.htm#single
