### ISSUE TITLE
Select all/none and close links not keyboard accessible

### ISSUE THREAD

**Issue by philwareham** [ehynds/jquery-ui-multiselect-widget#709]
First off, great script - very handy!

The select all, select none, and close links are not able to be accessed/focussed via keyboard (OK, the `esc` key closes the menu - as does `tab` key - so the close link isn't a big issue). It would be nice to be able to use the arrow keys to focus these links too and make the menu better for those with accessibility requirements.

Tested on MacOS with Safari 11, Firefox 58 dev edition, Chrome62. Same behaviour on all.

**Comment by mlh758** [comment]
Do these help at all? 
https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Keyboard-Navigation

**Comment by philwareham** [comment]
Ah, OK, closing this then. Thanks!

**Comment by mlh758** [comment]
You're welcome! Feel free to reopen if these aren't sufficient and I'll look into the issue further.
