### ISSUE TITLE
Usage Document Link No Longer Works

### ISSUE THREAD

**Issue by ebsllc** [ehynds/jquery-ui-multiselect-widget#710]
http://www.erichynds.com/blog/jquery-ui-multiselect-widget this link no longer works, can someone take a look?  Thx

**Comment by mlh758** [comment]
The original website isn't under support anymore. I'm not the original
maintainer and don't have access to his website. Is that link still in the
wiki somewhere?

**Comment by Eric--** [comment]
It seems that nobody maintain it !

**Comment by mlh758** [comment]
That is correct. The original maintainer doesn't maintain it and I don't have access to. Please use the wiki for documentation.
