### ISSUE TITLE
Dropdown sticky, not closing when scrolling

### ISSUE THREAD

**Issue by schittuluri1** [ehynds/jquery-ui-multiselect-widget#713]
I try to scroll with the refiner dropdown open in sharepoint, and it is not sticking to the refiner but detaching from there. Please refer to the jquery loaded on the page.
Below are the version of jquery I am using.
jQuery MultiSelect UI Widget 1.14pre
jQuery MultiSelect UI Widget Filtering Plugin 1.5pre
 jQuery UI - v1.11.4
 jQuery v1.10.2 

![image](https://user-images.githubusercontent.com/34896174/34391325-8137a8ba-eb0a-11e7-8607-c3c4326e7d1c.png)

Do I need to update any of the above files for this to be fixed? I tried a lot of combinations with latest 2.0 version as well but issue still prevails.
A noob question, since the dropdown is mainly coming from the multiselect js files, do I need to update every related css files as well?
I have the related issue here #647.

Thanks a lot.

**Comment by mlh758** [comment]
It might be worth upgrading to the 2.0.1 version of the widget.

**Comment by schittuluri1** [comment]
jQuery MultiSelect UI Widget 2.0.1
jQuery MultiSelect UI Widget Filtering Plugin 1.5pre
I tried with these but still getting the same issue. I have bootstrap running on the pages. But that doesn't seem to be the issue.
Can you help me with any alternative?

**Comment by mlh758** [comment]
What's the console error you are getting?

Also, the filter plugin should be at 2.x as well.

**Comment by schittuluri1** [comment]
The debugger is pausing here when I upgraded to jQuery MultiSelect UI Widget Filtering Plugin 2.0.0
![image](https://user-images.githubusercontent.com/34896174/34540054-b1c5f674-f098-11e7-94c0-1e507005642f.png)

And then it hits this error.
![image](https://user-images.githubusercontent.com/34896174/34540088-d42f8b58-f098-11e7-90d5-2be6da2fcfbe.png)

I try same combination with 1.5pre, it loads fine without error.
![image](https://user-images.githubusercontent.com/34896174/34540134-fdd16594-f098-11e7-9d1e-1ed00512387e.png)

Is there an event I can include like mouse scroll -- close the widget?

**Comment by mlh758** [comment]
As per the minimum requirements your version of jQuery UI is too low: https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Usage#requirements

The `instance` method was defined in newer versions of jQuery UI.

**Comment by schittuluri1** [comment]
Hi 
Thanks for your response. I can give you access to my o365 site where the issue is happening.
Can you please provide your microsoft id so I will try and see if access can be given. 
 I have updated to latest and seem to be some issues with the order I am calling each .js and .css files. And separately is the drop down sticky issue. Below is the order of my loading the jquery.

$includeCSS("", "~sitecollection/Style%20Library/Jquery/jquery-ui.min.css"); 
--- jQuery UI - v1.12.1 - 2016-09-14
$includeCSS("", "~sitecollection/Style%20Library/Jquery/jquery.multiselect.css");
------(https://github.com/ehynds/jquery-ui-multiselect-widget/blob/master/jquery.multiselect.css)
$includeScript("", "~sitecollection/Style%20Library/Jquery/jquery.min.js");
------ jQuery v3.2.1
$includeScript("", "~sitecollection/Style%20Library/Jquery/jquery-ui.min.js");
----jQuery UI - v1.12.1 - 2016-09-14
$includeScript("", "~sitecollection/Style%20Library/Jquery/jquery.multiselect.js");
----jQuery MultiSelect UI Widget 2.0.1
$includeScript("", "~sitecollection/Style%20Library/Jquery/jquery.multiselect.filter.min.js");
----jQuery MultiSelect UI Widget Filtering Plugin 2.0.0
$includeScript("", "~sitecollection/_catalogs/masterpage/Display Templates/Filters/Filter_MultiValueDropdown_Body.js");

I was getting the dropdown sometimes before getting all the errors and could see the same issue when scrolling.

**Comment by mlh758** [comment]
I would rather not have access to your site directly if I can avoid it.

I don't see the multi select filter css in that list of files.

Are you getting a different error now or something?

**Comment by schittuluri1** [comment]
I included the mult select refiner css as well. It just styled the widget. Didn't fix the issue.
Just to clarify the original error of drop down not sticking is happening however(And specifically happens on my 2013 site).
Earlier comment I was trying out the same thing on my o365 and it was giving me those errors.(with different jquery versions as mentioned)
I am trying now with different jquery UIs, see if that works out. The o365 site is my own subscription not company related. :)

Also looking to see if I can close the widget if the mouse hovers outside or if mouse scroll outside widget , not sure if this is the right direction. But will keep trying to get drop down in my o365 with latest 2.* versions of multiselect.

**Comment by schittuluri1** [comment]
I was seeing all the working models and could fin this js fiddle working as expected. https://jsfiddle.net/schittuluri/f6t9k8tf/

I will try this out and post here if this works.

**Comment by mlh758** [comment]
Your life will be a lot easier with those fiddles if you use a CDN to pull in the widget: https://cdnjs.com/libraries/jquery-ui-multiselect-widget

**Comment by SteveTheTechie** [comment]
The stated issues as I understand them are that an open menu does not close when the container div (or other) that contains the multi-select is scrolled, and the menu is not maintaining its position at the bottom of the button.

Currently, I do not see that the code has any kind of event handler for "exterior scrolling" that would cause an open menu to close.

As far as it not maintaining the position at the bottom of the button I would simply ask how big is the exterior div and whether it can contain the menu or whether you need to shrink the height of the menu so that it is not forced to overlap the button.

**Comment by mlh758** [comment]
Yeah the widget wouldn't close itself on scrolling an outside container. I would prefer not to put listeners on outer elements if I can avoid it, the consuming developer can determine when that might be appropriate.

**Comment by schittuluri1** [comment]
On 32bit Chrome or Firefox the dropdown UI widget closes fine. But on 64 bit is the issue of sticking.

**Comment by schittuluri1** [comment]
Below code is used to invoke close on scroll. To help others facing the issue
`jQuery(document).ready(function() {
		jQuery("#s4-workspace").scroll(function (event) {
		if(jQuery('.ui-multiselect-menu.ui-widget.ui-widget-content.ui-corner-all').length)
		{

		jQuery('.ui-multiselect-menu.ui-widget.ui-widget-content.ui-corner-all').each(function( index ) {

		if(jQuery(this).is(":visible"))
			{
			jQuery(this).find('a.ui-multiselect-close').click();
			}
			});

		}

			});`
