### ISSUE TITLE
Clone pop-up menu from one widget instance to another

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#720]
One thing that would likely improve performance for the case of many instances of the widget with the same configuration would be the ability to quickly clone the menu from one instance to another rather than building it from scratch.  I believe that this could maybe be done by copying the innerHTML for the menu of the source widget to the destination widget.  I think you would still incur a lag from the browser parsing the inserted HTML, but perhaps that could be optimized to not be noticeable.

I have a use case where I have a table of club members.  One of the columns contains multi-selects (1 for each person/row) to enable selecting one or more club officer roles for each person.   The roles to choose from never change, just the selections.  When I get to over 50 or so people in the table, things get really slow.  I have determined via some performance testing that the menu building is the culprit.   Currently, I deal with it by some creative use of setTimouts to force some async processing.

This use case is a good example of why some sort of cloning ability would be helpful.

**Comment by mlh758** [comment]
I just want to verify, the performance issues are still present with the 2.x version of the widget?

**Comment by SteveTheTechie** [comment]
It is hard for me to give you a quick answer.  Keep in mind that while it looks like we had similar thinking in a number of areas, there are so many differences between what you did and what I did that I need to get my head around. 

I doubt very much that I can just use the 2.x version as a drop in replacement for what I did.  There were a number of issues I addressed that we have not touched on yet.  (like z-index handling in the css)

**Comment by mlh758** [comment]
Yeah that's a good point, you've modified several other behaviors as well.

I did address the z-index stuff in my changes as well, instead of in css it's using the normal stacking order by checking .ui-front and dialogs. I'm sure that's not the extent of it.

**Comment by mlh758** [comment]
We should put this one on hold until we can evaluate the impact of the other performance issue you opened. Cloning the menu might end up being fairly tricky if we want to do it in a way that is performant.

**Comment by mlh758** [comment]
Mind if I close this one? Seems like the other performance improvements you made already did a lot. Copying the menu around seems like it would introduce more complexity than we need.

**Comment by SteveTheTechie** [comment]
Ok, but I am still going to work on it on my own, as it is directly related to a key use case for me:  many instances w/ same menu but different selections.

**Comment by mlh758** [comment]
Sounds good.
