### ISSUE TITLE
Fixed menu (list box) variant

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#721]
One of the things I really like about this widget is how it conserves screen space.  It puts a lot of functionality in the space of a button.  

In contrast, the underlying native multi-select takes up more screen space, particularly if there are a lot of options.

However, there are cases involving small set of options where it can be helpful to immediately show the user all of the available options without needing to click a button.   For these situations, it would be helpful to have a variant of this widget that just shows the menu fixed in place (no pop-up) without the button.

**Comment by mlh758** [comment]
This one I think I'm going to have to say no to. That might be better as a separate widget.

**Comment by SteveTheTechie** [comment]
It does not need to be a separate widget...  Just set appendTo to the element, do not insert a button, force autoOpen to true and never change it.   I think it would be reasonably simple.
