### ISSUE TITLE
More comments in the code

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#722]
Given that the original developer is not maintaining this anymore, I think it would be helpful to have a lot of comments in the Javascript to enable easy understanding of the code.   The comments would get minified away, anyhow so this should not be a big deal.

There are a number of subtle nuances to the way this code works.  It took me a long time to get my head around it.  I do not think others should have to incur the same learning curve.

**Comment by mlh758** [comment]
Pushed a commit with some additional comments that should help clarify what the various methods are doing.

**Comment by SteveTheTechie** [comment]
I would recommend a comment for each option stating what the valid values are for the respective option.  (or at least the ones where multiple types of values are allowed)

**Comment by mlh758** [comment]
https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Options The wiki page has that information although I can see wanting it in the code as well.
