### ISSUE TITLE
showCheckAll vs checkAllText is null

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#729]
It seems to me that having both showCheckAll and checkAllText options is superfluous, since you could just use a checkAllText === null option setting to imply that the related link should not be shown.  This also could allow for a checkAllText === '' (blank) setting to mean that the related icon, but not the text, should be shown.

This also applies to the showUncheckAll and the showFlipAll options (the latter being what I added).

I would like to ditch the showCheckAll, showUncheckAll, and showFlipAll options in favor of just using more values in the respective Text options to accomplish the same thing.

Your thoughts on this?

**Comment by SteveTheTechie** [comment]
Yes

**Comment by mlh758** [comment]
Your changes merged so closing this issue.
