### ISSUE TITLE
iconSet option vs individual icon options

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#730]
I would like to add the ability to use alternative icons for the widget.  However, even though I already added some individual options for specifying alternative icons, _it recently occurred to me that, in practice, a developer will likely just use all jQuery icons, all HTML Entities for icons, or all Font Awesome icons_--these are the alternatives I am accounting for currently.  (More could be added later.)

Right now, I have the following defined in my "not-yet PR'd" code:

```
	var msIcons = {
		'jQuery': {
			'open': '<span class="ui-icon ui-icon-triangle-1-s"></span',
			'close': '<span class="ui-icon ui-icon-circle-close"></span>',
			'checkAll': '<span class="ui-icon ui-icon-check"></span>',
			'uncheckAll': '<span class="ui-icon ui-icon-closethick"></span>',
			'flipAll': '<span class="ui-icon ui-icon-arrowrefresh-1-w"></span>'
		},
		'HTMLEntities': {
			'open': '<span class="html-entity">&#9660;</span>',
			'close': '<span class="html-entity" style="color:lightgrey;background-color:black;padding:0 2px;margin-right:1px;">&times;</span>',
			'checkAll': '<span class="html-entity">&check;</span>',
			'uncheckAll': '<span class="html-entity">&cross;</span>',
			'flipAll': '<span class="html-entity">&olarr;</span>'			
		},
		'FontAwesome': {
			'open': '<i class="fa fa-caret-down" aria-hidden="true"></i>',
			'close': '<i class="fa fa-times-circle" aria-hidden="true"></i>',
			'checkAll': '<i class="fa fa-check" aria-hidden="true"></i>',
			'uncheckAll': '<i class="fa fa-times" aria-hidden="true"></i>',
			'flipAll': '<i class="fa fa-undo" aria-hidden="true"></i>'
		}
	};

```
It seems like it may be better to just have an "iconSet" option to specify which predefined set of icons to use and then also provide a method to swap out an individual icon dynamically.  For example, maybe the open or close icons could be changed dynamically for indicating context.  However, to me, "dynamically" implies using a method rather than having an option.

Your thoughts?

**Comment by SteveTheTechie** [comment]
Again, the reason for allowing for alternative icons is that the default jQuery icons are not scaleable and can look rather small on some screen resolutions.

**Comment by mlh758** [comment]
I like the idea of being able to use alternative icon sets, I'm a little hesitant about coding in some specific ones though. Using an `iconSet` option with the defaults being jQuery as they are now seems reasonable.

Would there be a risk of introducing a new performance concern if we add callbacks to change the icons? It seems like the consuming developer could already hook into the `click` callback and use the `getMenu` or `widget` methods to swap icons around.

**Comment by SteveTheTechie** [comment]
Well, I already have some callbacks I added to facilitate swapping out specific icons... see below.   I already specifically added the span w/ class ui-multiselect-open to allow for the open icon to be dynamically changed for context.  (e.g. to indicate the multi-select is disabled with a different open icon) These callbacks are already in the PR code you merged.

So the dynamic swapping of icons is not a problem... that is handled already.  What I was looking at was whether I should help those using this widget by providing some possible icon alternatives and an option to specify which set rather than leaving it up them to figure it out on their own.  However, there are a number of ways to accomplish that.  Alternatively, I could ditch the iconSet opton and just put the icon alternatives I came up with in the code comments... would that be better?

```
case 'checkAllIcon':
case 'uncheckAllIcon':
case 'flipAllIcon':
   $menu.find('a.ui-multiselect-' + {'checkAllIcon': 'all', 'uncheckAllIcon': 'none', 'flipAllIcon': 'flip'}[key] + ' span').eq(0).replaceWith(value);  // eq(0) finds the first span
    break;
case 'openIcon':
    $menu.find('span.ui-multiselect-open').html(value);
    break;
case 'closeIcon':
    $menu.find('a.ui-multiselect-close').html(value);
    break;

```

**Comment by SteveTheTechie** [comment]
> I think the confusion comes from the iconSet discussion. I was thinking you meant move all the options for icons under that option as an object for simplicity.

I think that is fine.  Let's just do that then.  I like your thought of putting how-to examples in the wiki.

**Comment by mlh758** [comment]
Closing this since your changes for this merged.
