### ISSUE TITLE
Ditch _toggleChecked replacement in jquery.multiselect.filter.js

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#733]
The redefinition of _toggleChecked in jquery.multiselect.filter.js seems like overkill, particularly since the difference from the default definition is small and the behavior difference could just be handled by some sort of flag that the filter code sets on the main instance to cause the difference in logic.  Right now, you essentially have to keep the two definitions in sync if any changes to them are made.

My thinking is that the flag could either be set via a new call back that the filter code calls on the instance, or a new "filtered" parameter could be added to _toggleChecked that the filter code makes use of via "currying" the function.  (baking in the parameter value when filtering is in use)

Your thoughts?

**Comment by mlh758** [comment]
Yeah if we can get rid of it I would be all for it. I haven't looked at that portion of the code much yet. It's something I can investigate. I'm pretty fond of function programming concepts but I don't have much of an opinion yet since I haven't looked at that code much.

**Comment by SteveTheTechie** [comment]
I appears that when we changed to valid HTML markup we broke the select by optgroup functionality for the filtered version.   I am looking at that, and will probably just include the fix with the PR for this issue.

**Comment by mlh758** [comment]
> I appears that when we changed to valid HTML markup we broke the select by optgroup functionality for the filtered version. I am looking at that, and will probably just include the fix with the PR for this issue.

What part of it broke? That was working when I merged the PR in, both filtered and unfiltered. Clicking by option group title and filtered and clicking the check all / uncheck all buttons.

**Comment by SteveTheTechie** [comment]
Sorry... I jumped the gun.  Hence, I deleted the comment.   The sky is not falling.  lol  😆

**Comment by mlh758** [comment]
Oh, woops. I didn't notice it was deleted last night. I just see the e-mails and go. I'm just gunna... delete all these comments and we can pretend it never happened.

**Comment by SteveTheTechie** [comment]
Closed by merge of #745
