### ISSUE TITLE
Generated HTML markup for Option Groups is invalid

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#740]
Reference [https://validator.w3.org/#validate_by_input](https://validator.w3.org/#validate_by_input)

The following models the way that anchor tags are used in the generated markup for option groups. However, this markup is flagged as invalid HTML by the HTML validator.  (I suspected it would be.)
```
<!DOCTYPE HTML SYSTEM>
<html>
<head>
<title>tester</title>
</head>
<body>
<ul>
<a href="https://www.google.com/">test</a>
<li>test2</li>
</ul>
</body>
</html>
```

If the anchor can somehow be wrapped in a `<li>`, it is then valid... e.g. the following validates fine:
```
<!DOCTYPE HTML SYSTEM>
<html>
<head>
<title>tester</title>
</head>
<body>
<ul>
<li><a href="https://www.google.com/">test</a></li>
<li>test2</li>
</ul>
</body>
</html>
```

**Comment by mlh758** [comment]
Yup, only permitted content is `<li>`
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul

**Comment by mlh758** [comment]
Probably need a class for the option group ul and a first child selector to modify that first element.

**Comment by mlh758** [comment]
I'll work on a fix for this today.

**Comment by SteveTheTechie** [comment]
I looked at your commit...  You may want to take a look at the following:
[https://stackoverflow.com/questions/5899337/proper-way-to-make-html-nested-list](https://stackoverflow.com/questions/5899337/proper-way-to-make-html-nested-list)

**Comment by mlh758** [comment]
PR for this is merged.
