### ISSUE TITLE
Broken link to Demo page

### ISSUE THREAD

**Issue by ltdeta** [ehynds/jquery-ui-multiselect-widget#743]
The link Wiki \ Usage \ "Filter Plugin" is broken
http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/index.htm#filter

**Comment by mlh758** [comment]
Thank you for pointing that out. The original website is gone and I've been getting references to it off the wiki. That one has now been removed as well.

**Comment by ltdeta** [comment]
any plans making new examples based on version 3 ?
a working demo  would make it easier to understand the options

**Comment by mlh758** [comment]
All the demos in the demo folders are updated for version 3 if you use the version 3 branch.
