### ISSUE TITLE
Too many this references results in a larger minified file size

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#746]
@mlh758  You have decided not to provide minified files anymore (understandable), but I am betting that many users will still minify them on their own.

If they are using something like uglify that uses identifier obfuscation to get smaller file sizes, then not having so many this references or object property references in the code will result in users getting smaller minified file sizes.  `this` and object property references cannot be obfuscated... that is why it is worthwhile to set them to local variables in functions... The local variables *can* be obfuscated to single character variables, which usually results in a smaller minified file.

If you consider refresh():

```
   refresh: function(init) {
      var $element = this.element;

      // update header link container visibility if needed
      if (this.options.header) {
         this.$headerLinkContainer
              .find('.ui-multiselect-all, .ui-multiselect-none, .ui-multiselect-flip')
              .toggle( !!$element[0].multiple );
      }
      this._buildOptionList();                                  // Clear and rebuild the menu.
      this._updateCache();                                      // cache some more useful elements

      this._setButtonWidth();
      this.update(true);

      // broadcast refresh event; useful for widgets
      if (!init) {
        this._trigger('refresh');
      }
    },
```

I count 8 this references.  If the statement `var self = this;` was added to the function, and all the this references were replaced with self's, then you would get the following result via obfuscation:

1.  Since the self's are local to the function, they would replaced by a single character variable during obfuscation. That means you end up saving 3 bytes for each this replaced by self.  Also, whether it is "self" or "that" or "me" (or whatever) does not matter... Whatever it is gets replaced by a single character variable during obfuscation.
2.  However, you have to add `var self=this;` at the beginning... the obfuscation will convert that to `var x=this;` or similar single char variable and then it will lose the var since there is already a var statement in the function. Thus, you add 7 characters for that.

Net Result = 8 x 3 - 7 = 17 bytes saved via obfuscation.    If you consider this savings potential for the rest of the file, then this can add up for functions where there are 3 or more this references. 
(3 x 3 bytes saved > 7 bytes added)

Generally speaking, using primarily local variables in functions instead of a lot of this references or object properties will result in a smaller minified file when using obfuscation.

**Comment by mlh758** [comment]
> You have decided not to provide minified files anymore (understandable), but I am betting that many users will still minify them on their own.

Yeah I fully expect people to minify the files with something like uglify, or an automatic build suite like webpack. I will also provide minified files attached directly to the release once I go and tag it.

> Net Result = 8 x 3 - 7 = 17 bytes saved via obfuscation.

I have a hangup about unnecessarily using `self`, and that's a pretty small amount of data saved. I'd prefer you not do it, but if you include a comment at the top of the file about why there are selfs everywhere I'd still merge it if it came in on some changes.

**Comment by SteveTheTechie** [comment]
> that's` a pretty small amount of data save
