### ISSUE TITLE
jQuery only version for future?

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#748]
My impression is that jQuery UI is dying a slow death from lack of attention and lack of updates.

Therefore, it may be worthwhile to consider eventually coming up with an alternative version of this widget that only depends on jQuery.  I do not think it would be too difficult when you consider the following.

1.  As it stands, the only jQuery UI code that I think is being used is the widget factory and position, and this widget already has a fallback for the position functionality not being loaded.
2.  There are only 5 jQuery UI icons being used... those could be carved out into a separate sprite.
3.  There are only about 6 jQuery UI classes (that I counted) being used... those could be carved out into the existing (or separate) CSS file.
4.  The widget factory function would probably need to be replaced with another factory function w/ some object inheritance baked in, but again, I think that would be doable.

Perhaps this is something to consider for version 4...

**Comment by mlh758** [comment]
Well, you're not wrong there, jQuery UI is fading out. However, jQuery use itself is also fading away somewhat. Tools like ReactJS and Angular seem to be winning the battle for the DOM. It's something to consider for version 4, but I also wonder if there will be a need for a version 4, especially with Select2 and Chosen also floating around.

As long as there are people contributing/asking for help on the widget I'll keep maintaining it but I do wonder how much of a future it has for broad use.

**Comment by SteveTheTechie** [comment]
I personally prefer this widget over the alternatives.  The reason is that the "foundation element" for this widget is a simple button whereas the others have a combination of elements that take up space only so that you can delete items without opening the menu.  Additionally, the links in the menu header are very useful.  Don't discount what this widget offers... Granted, it has some rough edges, but we can fix those.

Also, if you are willing to allow me to make some updates to provide features that are not in the alternatives, then I think you may find that there is some renewed interest in this widget.

This is why I feel that this widget should have a future regardless of what happens to jQuery UI or even jQuery.

**Comment by mlh758** [comment]
> Also, if you are willing to allow me to make some updates to provide features that are not in the alternatives, then I think you may find that there is some renewed interest in this widget.

Yeah, new features will generally be welcome.

**Comment by SteveTheTechie** [comment]
Some additional thoughts on a future "divorce" from jQuery UI:

1.  jQuery UI CSS generally falls into two categories: "structural" CSS and "appearance" (theme related) CSS.  The structural classes could just be pulled into the widget CSS files.  The appearance stuff could be put into separate theme based CSS files that are arranged to allow for easy modifications.

2.  The jQuery UI position() dependence could be eliminated with some effort.  There are really just a few position() options that are useful for the widget. 

3.  The jQuery UI resizable() dependence could be eliminated with some effort.  Would have to put in some mouse drag logic, but that could also be useful for implementing selections of a range of options via a mouse drag.

4.  The _allowInteraction piece I put into the code recently could just be put into a separate JS file with some instructions for use.

5.  The hardest part, the widget factory function, could likely be be replaced with a custom class based factory function.  A review of the underlying jQuery UI widget factory code could help with this... a very lightweight version of the widget factory could be implemented.

If need be, all of the above could be put into a separate "no-jqueryui.js" file.

**Comment by mlh758** [comment]
I created a milestone for this to log issues against to track the various steps required.
