### ISSUE TITLE
Resync method

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#750]
A "resync" method would be helpful.  

This would simply resynchronize the selected state between the native select and the widget.

This would be useful since it would allow changing selected states of the native select's options and then this could be reflected on the widget by simply calling the resync method.

Currently, the only way to show this update in the widget is by calling refresh, which rebuilds all the options from scratch which is really overkill if you are just changing selected states as in this case.  Sometimes I think "refresh" should really be called "rebuild" since it is really rebuilding the menu.

Another thing a resync method would make possible would be a val(x) (set value) method for the widget.  This would just call $('select').val(x) on the native select, then call the resync() method to reflect the new selections in the widget. 

```
	 /** 
	  * Updates the widget checkboxes' checked states
	  * from the native select options' selected states.
	  *
	  */
	 resync : function() {
		var $inputs = this.$inputs;
		var $options = this.element.find('option');
		
		if ($inputs.length === $options.length) {
			var inputValues = {};
			$inputs.each( function() {
				inputValues[this.value] = this;				
			});
			$options.each( function() {
				if (this.value in inputValues) {
					inputValues[this.value].checked = this.selected;
				}
			});
			this._trigger('resync');
			this.update();
		}
		else {
			this.refresh();
		}
	 },

```

**Comment by mlh758** [comment]
Currently you can use `val` to set the value, but you have to call `refresh` after for it to show up in the widget.

**Comment by SteveTheTechie** [comment]
my point is that doing a refresh is overkill for simply updating the checked states in the widget from the native select.

**Comment by SteveTheTechie** [comment]
A built-in val method could maybe simply be:
```
val:  function(newValue) {
  if (typeof newValue !== 'undefined') {
     this.element.val(newValue);
     this.resync();
     return this.element;
   }
   return this.element.val();
}
```

**Comment by SteveTheTechie** [comment]
@mlh758 I now have this working as expected in my WIP code.
