### ISSUE TITLE
Set default branch for PRs

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#755]
@mlh758 The GitHub allows setting a default repo branch to land PRs.  I suggest setting that so that it does not default to the master branch... this can be helpful moving forward to allow people to contribute without touching the master branch.

After you release version3, I would suggest creating another branch (e.g. dev or whatever) to land PRs so that you can bunch them up before merging to the master branch.

**Comment by mlh758** [comment]
I'm not the repo owner so I don't have permission to make that change. I'd also like to add something like Travis CI to run tests on PRs.

This isn't a large enough or active enough repo to really worry about a dev branch though anyway. Most people should be pulling their code from npm or web cdn which rely on tags.
