### ISSUE TITLE
Default position incorrectly described in the wiki

### ISSUE THREAD

**Issue by Celos** [ehynds/jquery-ui-multiselect-widget#756]
[The wiki](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Options) states that any value passed to the `position` option is merged with the internal default of `{my: 'left top', at: 'left bottom', of: $button}`.

[The source code](https://github.com/ehynds/jquery-ui-multiselect-widget/blob/master/src/jquery.multiselect.js#L910) has the default options as `{my: 'top', at: 'bottom', of: $button}`. 

According to the [position utility documentation](https://api.jqueryui.com/position/), single values that specify vertical alignment will be normalized to `center` horisontally, making the final result `{my: 'center top', at: 'center bottom', of: $button}`.

Depending on the way you look at it, this is either a documentation issue or a bug in the code. I'm inclined to go with the latter.

**Comment by SteveTheTechie** [comment]
Bear with us... I got I bit ahead of myself and edited that.  It will be that way as soon as we get the next release out.

**Comment by mlh758** [comment]
Hm... I'll revert it for now, just to make the documentation accurate to the latest version and avoid confusion. We can revert the revert once version3 releases.

**Comment by mlh758** [comment]
Okay, I've updated the docs to be accurate to what version 2 is actually doing so people know what to expect.

Once version 3 releases we can just revert the changes I made and put the docs back to what @SteveTheTechie changed in version 3. I agree that left aligning it makes more sense than centering it.
