### ISSUE TITLE
How to trigger a callback programmatically?

### ISSUE THREAD

**Issue by schittuluri1** [ehynds/jquery-ui-multiselect-widget#757]
I am trying to preset a refiner on SharePoint 2013 search.I have used multivalue display template and added the multiselect. Now I have a requirement to select a single value from one of the dropdown to be enabled only on page load, but remove it when users want to select some other refiner like as usually works. I was able to use get labels method and refresh the multiselect. But unless I click on the dropdown the filter is not applying to search results.Can anyone help, where to keep the jQuery("#" + "FileType" + "Select").multiselect("getLabels").find("input[value='ǂǂ786c7378']").click(); for this to apply the filter on only first time page load.

This code executes only when I click on dropdown and close. Because of the Close(). Is there like a manually trigger this programatically?
Or Simple how to apply close function only once after option is selected programatically?

I was using this as well.

`jQuery(this).find('a.ui-multiselect-close').click();`

I need to select the option which I am able to but it is not triggering a refresh of another function. How to do this?

```
jQuery("#" + propertyName + "Select").multiselect({
  selectedList: 10,
  close: function() {
    var refinement = {};
    refinement[ctx.RefinementControl.propertyName] = [];
    var thisvariable = this;
    jQuery("#" + propertyName + "Select").multiselect("getChecked").each(function() {
      refinement[ctx.RefinementControl.propertyName].push('"' + $(this).val() + '"');
    });
    if (refinement[ctx.RefinementControl.propertyName].length == 0) {
      delete refinement[ctx.RefinementControl.propertyName];
    }
    $getClientControl(this).updateRefinersJSON('{"' + ctx.RefinementControl.propertyName + '":null}');
    $getClientControl(this).addRefinementFiltersJSONWithOr(JSON.stringify(refinement));

    //push a single refinement on ducment ready
    jQuery("#" + "FileType" + "Select").multiselect("getLabels").find("input[value='ǂǂ786c7378']").click();
    var refinement = {};
    refinement["FileType"] = [];
    var value = "ǂǂ786c7378";
    refinement["FileType"].push('"' + value + '"');
    $getClientControl(this).addRefinementFiltersJSONWithOr(JSON.stringify(refinement));
  }
});
```

**Comment by mlh758** [comment]
Are you trying to pre-select some options without using `click`? There are some instructions [here](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki#manually-check-or-uncheck-a-checkbox) but basically add `selected` to the options in the `<select>` tag you want to be checked and then call `refresh` on the widget.

**Comment by schittuluri1** [comment]
I have below code. Which uses the get labels and the option is selecting after refresh as well. But it is not firing the code above. I wanted a one time default preset not after the page load but before. Or after postrender, trigger the js.
Currently it works if I manually just click on the dropdown and close without selecting anything.


``

**Comment by mlh758** [comment]
What is your overall objective from a high level?

You can manually trigger close on the widget by getting the instance and triggering close on it like this: https://github.com/ehynds/jquery-ui-multiselect-widget/blob/master/src/jquery.multiselect.js#L806

but it sounds like you're really trying to solve a different problem and using `close` to do it and you probably shouldn't.

**Comment by schittuluri1** [comment]
ok Let me explain it clearly. 
1. When I select an option in the dropdown and click outside, it triggers the multiselect and hence the below code executes and the search results render based on the selection.
$getClientControl(this).updateRefinersJSON('{"' + ctx.RefinementControl.propertyName + '":null}');
    $getClientControl(this).addRefinementFiltersJSONWithOr(JSON.stringify(refinement));
![image](https://user-images.githubusercontent.com/34896174/36794754-dbc1d2be-1c66-11e8-925a-330b4b1d8572.png)

2 .  Now I want the same thing to happen after selecting the option programatically by this code.
jQuery("#" + "FileType" + "Select").multiselect("getLabels").find("input[value='ǂǂ786c7378']").click(); 

So my question is how to enable the same functionality if one does select a option, the js code runs, because of this [https://github.com/schittuluri1/Multivalue/blob/a2f3da28b4012a37ed506c5276a53bcf6b1a39b6/Filter_MultiValueDropdown.js#L122] line. it updates/filters search results, I wanted to have same functionality programatically. Like presetting the option and updating results accordingly.

Please find the full code here.
https://github.com/schittuluri1/Multivalue/blob/master/Filter_MultiValueDropdown.js

**Comment by mlh758** [comment]
Then the code I mentioned earlier would work for you:
```
var instance = $("select").multiselect('instance');
instance._trigger('close');
```

**Comment by schittuluri1** [comment]
Thank you so much. This has worked for me.
