### ISSUE TITLE
Filter doesn't work with "&" special character

### ISSUE THREAD

**Issue by gs-rpal** [ehynds/jquery-ui-multiselect-widget#759]
Please look into this fiddle

https://jsfiddle.net/ghcrgvqm/8/

Thanks.

**Comment by mlh758** [comment]
What are you expecting to happen, and what is happening?

![image](https://user-images.githubusercontent.com/4331955/37166217-1caaa784-22c4-11e8-989c-b6180f080276.png)

**Comment by gs-rpal** [comment]
When you type " &* ", no options are visible

**Comment by gs-rpal** [comment]
its becoz of filtering on innerHTML content

**Comment by SteveTheTechie** [comment]
@mlh758 I think that this may get addressed by the new Version 3 code.  It is calling text() (textContent vs innerHTML) to build the filter cache:

```
// Version 3.0 code follows...
    updateCache: function(alsoRefresh) {
      var cache = {};  // keys are like 0, 0.1, 1, 1.0, 1.1 etc.
      this.instance.$checkboxes.children().each(function(x) {
         var $element = $(this);
         // Account for optgroups
         if ($element.hasClass('ui-multiselect-optgroup')) {
            // Single number keys are the option labels
            cache[x] = $element.children('a').text(); 
            $element = $element.find('li');
         }
         $element.each(function(y) {
            cache[x + '.' + y] = $(this).text();
         });
      });
      this.cache = cache;
      this.$rows = this.instance.$checkboxes.find('li');
      if (!!alsoRefresh) {
         this._handler();
      }
    },
```

**Comment by gs-rpal** [comment]
So is it safe to use text() instead of innerHTML

*Code here*
updateCache: function() {
      // each list item
      this.rows = this.instance.menu.find(".ui-multiselect-checkboxes li:not(.ui-multiselect-optgroup-label)");

      // cache
      this.cache = this.element.children().map(function() {
        var elem = $(this);

        // account for optgroups
        if(this.tagName.toLowerCase() === "optgroup") {
          elem = elem.children();
        }

        return elem.map(function() {
          return this.innerHTML.toLowerCase();
        }).get();
      }).get();
    },

**Comment by SteveTheTechie** [comment]
@gs-rpal no. One is jQuery other is plain js

**Comment by gs-rpal** [comment]
@SteveTheTechie yeah. Which one to use then?

**Comment by mlh758** [comment]
Well this is a jQuery widget so using jQuery `text()` in this case should be fine.

**Comment by SteveTheTechie** [comment]
If you are swapping out innerHTML in `this.innerHTML.toLowerCase();`  you would need to use textContent, not text(), since "this" in this case references a DOM element, not a jQuery object.

**Comment by SteveTheTechie** [comment]
@mlh758 I think this is a non-issue w/ the pre-release code, so this issue can probably be closed.

**Comment by mlh758** [comment]
@gs-rpal Would you mind trying out your use case with the version 3 release?

**Comment by gs-rpal** [comment]
I dont want to upgrade the version as such. SO for now going ahead with .text()
