### ISSUE TITLE
Update of wikis/docs for Version 3

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#760]
Just creating this issue for communications around updating the wikis for Version 3.

**Comment by SteveTheTechie** [comment]
Created the following:
https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Migrating-to-Version-3

**Comment by SteveTheTechie** [comment]
Will need the other wikis updated, as appropriate.

**Comment by mlh758** [comment]
I also need to revert that revert around position.

**Comment by mlh758** [comment]
>htmlText - This option allows you to specify types of text in the widget that should be treated as html.
wrapText - This option allows you to specify types of text in the widget that should be wrapped.

These two could probably use some elaboration. Types of text isn't clear by itself.

**Comment by mlh758** [comment]
I updated the main readme so people will see that version 3 is available up front.

**Comment by SteveTheTechie** [comment]
> htmlText - This option allows you to specify types of text in the widget that should be treated as html.
> wrapText - This option allows you to specify types of text in the widget that should be wrapped.
> 
> These two could probably use some elaboration. Types of text isn't clear by itself.

Ok, updated migration page.  Feel free to edit as needed.

**Comment by SteveTheTechie** [comment]
FYI:  https://pages.github.com/

The demo pages and the index could be redeployed as github pages.  Essentially, what ehynds was doing with the demo index file and individual demo files can be redeployed as github pages for a nice presentation.  I think it is just a matter of some minor reorganizing of the repo.

**Comment by SteveTheTechie** [comment]
@mlh758 Editing https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Events

**Comment by SteveTheTechie** [comment]
@mlh758 Updated https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Filter-Options

**Comment by SteveTheTechie** [comment]
@mlh758 Updated https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Methods

**Comment by SteveTheTechie** [comment]
FYI:  I have been alphabetizing lists of things in the wiki's that I have edited to make stuff easier to find.

**Comment by mlh758** [comment]
I think I may need admin permissions to set up GitHub pages. I'll double check that.

I appreciate the alphabetization.

**Comment by SteveTheTechie** [comment]
https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Customization

I added quite a bit of details (& examples) on how to use the new linkInfo option for customizing the links.

**Comment by SteveTheTechie** [comment]
@mlh758 I think I have updated all of the relevant wiki pages to reflect Version 3 information.  Let me know if there is anything I should change.

**Comment by mlh758** [comment]
I fixed the default in `selectedText`, probably something I did a long time ago and didn't notice until I was re-reading it all carefully. Otherwise I think it all looks good.
