### ISSUE TITLE
No CSS in https://cdnjs.com for 3.0.0

### ISSUE THREAD

**Issue by sergey-nagaytsev** [ehynds/jquery-ui-multiselect-widget#764]
At https://cdnjs.com/libraries/jquery-ui-multiselect-widget/3.0.0 , no CSS files are available. Had to revert to 2.0.2

**Comment by mlh758** [comment]
Are you able to pull it from npm instead? I'll try to contact the cdnjs folks, the folder structure has changed in the app.

**Comment by mlh758** [comment]
Issue [opened](https://github.com/cdnjs/cdnjs/issues/12611) with cdnjs. Hopefully I can have this resolved soon.

**Comment by mlh758** [comment]
cdnjs hasn't followed up on this at all, and it didn't resolve when I merged v3 to master. There's nothing else I can really do here.
