### ISSUE TITLE
List not shown after refresh when using multiselectfilter (V 3)

### ISSUE THREAD

**Issue by BrendaH** [ehynds/jquery-ui-multiselect-widget#771]
**I'm submitting a bug report**

**What is the current behavior?**
Situation: Using multiselect and filter for a select with all options inside optgroups.

When opening a multiselect with filter interface there's no list. Inspecting with the Developer Toolbar shows that the list has a height of 4px. Disabling that css rule displays the list.
So seems like the height of the list is not calculated correctly.

The list is correctly displayed after refresh when multiselect filter is not used.

**What is the expected behavior?**
I'd expect to actually see the list of options, neatly ordered by the optgroups they're in.

**Minimal demo**:
https://jsfiddle.net/w6avmr1w/16/

### Please tell us about your setup
  
  * Version: 3
  * Browser: FireFox 58.0.2 (64-bit) on Windows 10
  * Other frameworks in use: Jquery, jquery-ui

**Comment by mlh758** [comment]
Doing a little testing, refresh doesn't even have to be called in `beforeOpen`. Just loading up a multiselect with the filter and calling `refresh` hides the whole list. This is a lot like the thing you PR'd a couple days ago.

**Comment by mlh758** [comment]
`resync` doesn't hurt anything though

**Comment by BrendaH** [comment]
For my own purposes I do want to refresh the list in a beforeopen. I have not tested using refresh in a different function or after editing the options of a select because those are not my use cases. But if it is broken in the beforeopen then I assume it might be broken elsewhere too?

Resync only syncs the state of the checkboxes, I want the whole list to be redrawn (which is what refresh does).

**Comment by mlh758** [comment]
> For my own purposes I do want to refresh the list in a beforeopen.

Right, but it's broken in more cases than just that, which is important since this is a broader issue.
I wasn't suggesting you use resync, I'm just keeping track of what is/isn't impacted since we just added that and it can touch the options as well.


Changing anything in the filter input causes it to refresh so I think this is a caching issue. I suspect triggering a reset in the filter after the main widget does a refresh will fix it.

**Comment by mlh758** [comment]
That suspicion was wrong, after refreshing each filter instance is having it's _handler method called twice.

**Comment by mlh758** [comment]
PR #773 addresses this.

**Comment by SteveTheTechie** [comment]
I am looking at this.   

One note...  The following is not valid:  `header: [false, false],`

**Comment by SteveTheTechie** [comment]
@mlh758 What is happening is that the main widget refresh calls both updateCache() for the main widget and updateCache() for the filter.   The updateCache for the filter is also refreshing the filtered options shown which would typically adjust the menu height... but that is really only of value if the menu is open.   This is supposed to handle the case of refreshing w/ the filter in use and the menu open.

I think the fix you did should be fine and will take care of the problem.

**Comment by mlh758** [comment]
PR merged. This should be fixed.
