### ISSUE TITLE
Filter not working (V3)

### ISSUE THREAD

**Issue by BrendaH** [ehynds/jquery-ui-multiselect-widget#772]
**I'm submitting a bug report**

**What is the current behavior?**
When using multiselect with the filter, the filtering does not work on a select with all the options inside optgroups. The interface for filtering is shown, but typing doesn't do anything.

**What is the expected behavior?**
When I type something in the filter box I expect the list underneath it to only show results that match the filtering.

Minimal demo:
https://jsfiddle.net/7udz0uha/3/
Try searching for 'rik' for example.

### Please tell us about your setup
  
  * Version: 3
  * Browser: FireFox 58.0.2 (64-bit) on Windows 10
  * Other frameworks in use: jquery, jquery-ui

**Comment by mlh758** [comment]
It looks like you're missing some css. I updated the [fiddle](https://jsfiddle.net/7udz0uha/5/) with the missing class and it seems to work now.

**Comment by SteveTheTechie** [comment]
> It looks like you're missing some css. I updated the fiddle with the missing class and it seems to work now.
>
>Specifically it was .ui-multiselect-excluded {display: none}

Agreed.  Works for me.  Also, the filter demo works fine and it is what I used for testing.
