### ISSUE TITLE
Combo Box Variant

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#774]
## I'm submitting a ...
  -  bug report
  - [x] feature request
  -  question

### What is the current behavior?
Users cannot dynamically add to the multi-select.  Additions can only be dynamically added via code.

### What is the expected behavior?
Future enhancement...

Just overlay a text input w/ transparent background over the button to allow users to dynamically add new options to the menu.

Since this would be additive functionality, it could be another widget like the filter widget.  (If you think about what is happening... adding an input, there are simlilarities.)

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo
_Common options for demos are [jsfiddle](https://jsfiddle.net/) and [codepen](https://codepen.io)_

### If you are requesting a new or changed feature, please provide a rationale
It would be another way to differentiate this widget from others of this ilk.  The simple button element used as the anchor for the widget would allow for this enhancement.

### Please tell us about your setup
  
  * Version: 3
  * Browser: Chrome
  * Other frameworks in use:

**Comment by mlh758** [comment]
This one is easy enough to code up by the implementing developer, there's even a demo that is doing this, albeit not integrated into the menu. It also seems like it runs the risk of crowding the menu.

Adding it as a separate control nested under the button removes the menu crowding, but it'll be hard to account for everyone's use case on how much detail they want to add to each option, as well as where to add it in the document flow.

That said, following along with the separate widget idea, I wonder if creating a UI element that takes a mutliselect enabled element as a parameter to link them would work. If it's entirely separate (maybe instantiate it onto a text input or something) the developer can choose where to put it. That would give more room for flexibility and assuage my concern about adding more complexity to the main widget. There's already some code in there to account for the filter being present and I'd prefer not to have to add more for another extension.

**Comment by mlh758** [comment]
I'm actually going to say no to this feature. There's a demo that shows how to do it, and I don't want to make this widget too many things. It's easy enough for a developer to add to their page, and I think the needs per-developer are going to be pretty varied visually for such a tool.
