### ISSUE TITLE
Fix sequencing of animations and positioning

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#775]
## I'm submitting a ...
  - [x] bug report
  -  feature request
  -  question

### What is the current behavior?
Reference the animations demo.  The positioning of the animated top menu is wrong.  It is positioned to the second bottom widget.

This is likely caused by the asynchronous execution of animations, causing the positioning to actually take place before the animation completes.

You can also see this in the fact that the width of the menu does not match the button width as it should.  Again, the asynchronous animations are messing up the sequencing.

### What is the expected behavior?
Each animated menu should be positioned to their respective widget on open.

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo
_Common options for demos are [jsfiddle](https://jsfiddle.net/) and [codepen](https://codepen.io)_

Run the animations demo.

### Please tell us about your setup
  
  * Version: 3
  * Browser: Chrome
  * Other frameworks in use:

**Comment by SteveTheTechie** [comment]
I have a "sort-of" working fix that does the positioning a dimension setting w/ the animation.

However, there is still an issue of getting things to happen in the right order.  You cannot do a position() or dimension setting on a hidden div, but those really need to be set prior to doing the animation.  Therefore, we kind of have a circular logic situation where we need to set position and dimensions prior to animating, but we can't because it is the show w/ animating that makes setting those possible.

**Comment by SteveTheTechie** [comment]
My fix works now.

**Comment by mlh758** [comment]
I'll take a look at it soon and get this merged. I haven't had time to take a close look at this one yet.

**Comment by SteveTheTechie** [comment]
Associated pull request was merged... closing this.
