### ISSUE TITLE
Visual Indicator for groupsSelectable option

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#779]
## I'm submitting a ...
  -  bug report
  -  feature request
  - [x] question

### What is the current behavior?
No visual indicator is shown for when groupsSelectable is enabled.  Shouldn't something be shown?

### What is the expected behavior?
Good question... maybe show a check mark somewhere in the group heading when you can select groups?  I do not really have a good idea for this.

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo
_Common options for demos are [jsfiddle](https://jsfiddle.net/) and [codepen](https://codepen.io)_

### If you are requesting a new or changed feature, please provide a rationale
If nothing is visible, how should users know if functionality is available to them?

### Please tell us about your setup
  
  * Version: 3
  * Browser: Chrome
  * Other frameworks in use:

**Comment by mlh758** [comment]
Well right now there is `cursor: pointer` css on the option group headers, which is sort of the universal "You can interact with this" indicator. Prior to version 3 they were always clickable. Maybe now make that pointer bit a separate class that only gets added if the option is enabled.

**Comment by SteveTheTechie** [comment]
pr merged... closing this
