### ISSUE TITLE
Suggestion for Issue Template PR reference

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#780]
@mlh758 I suggest adding a question to the issue template asking whether the issue poster will submit an accompanying PR to resolve the issue (and maybe a rough idea of when it might be done).   Hopefully, this would encourage people to not just post issues, but post fixes also.

**Comment by mlh758** [comment]
Feel free to open a PR against the issue template :)

**Comment by SteveTheTechie** [comment]
I did not know I could do that.  Thx!
