### ISSUE TITLE
Suggestions for PR template

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#781]
### Suggestions for a PR template:
----
**This Pull Request is a**
  - [ ] Bug fix
  - [ ] Feature addition
  - [ ] Code refactoring / optimization 
  - [ ] Test Addition
  - [ ] Demo Addition
  - [ ] i18n Addition
  - [ ] Other (explain below)

**Related Issue numbers** _(use [Github "keywords"](https://help.github.com/articles/closing-issues-using-keywords/): Fixes #nnn, Closes #nnn, etc.)_

**Why is this Pull Request needed; what does it do?**
_(Provide use cases, code references, [jsfiddle](https://jsfiddle.net/), [codepen](https://codepen.io), etc.)_

**Pull Request Approval Checklist:**
  - [ ] No Tabs / Code Spacing Consistent
  - [ ] Tests Ran and 0 Failing
  - [ ] Tests Added/Updated
  - [ ] Impacted Demos Updated
  - [ ] Impacted i18n Code Updated

**Comment by mlh758** [comment]
This looks reasonable. I'll add it soon.
