### ISSUE TITLE
Question: Why _setOptions on widget prototype?

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#785]
## I'm submitting a ...
  -  bug report
  -  feature request
  - [x] question

### What is the current behavior?
`$.Widget.prototype._setOption.apply(this, arguments)` is at the end of the `_setOption()` method.

I find this puzzling as it would seem to me that this would change the option in every future instance of the widget.   Is this correct?  Am I missing something? 

### What is the expected behavior?
Shouldn't we just be setting options on the current instance?

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo
_Common options for demos are [jsfiddle](https://jsfiddle.net/) and [codepen](https://codepen.io)_

### If you are requesting a new or changed feature, please provide a rationale
If the options in the prototype need to be updated, I would expect that to be done separately from the _setOption() method.

### Please tell us about your setup
  
  * Version: 3
  * Browser: Chrome
  * Other frameworks in use:

**Comment by mlh758** [comment]
The widget instance `setOption` method is essentially an override. Calling the prototype method and applying it to `this` (the widget instance) is like calling `super`. It's making sure whatever widget factory logic that is required for the `setOption` method is also called after handling our implementation.

You can test this isn't affecting all future widgets by using the basic demo, setting `buttonWidth` to 400, destroying the widgets and making new ones. They come back at the default width again.

**Comment by SteveTheTechie** [comment]
Ok, got it!  Thanks for the clarification!
