### ISSUE TITLE
Code refactor

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#788]
@mlh758 

The code should probably be refactored before version 3 release to break up the monstrous _bindCheckboxEvents() function, and relocate the resizable initialization so that it does not need to have a $menu.show() and $menu.hide() to initialize it.

Your thoughts?

**Comment by mlh758** [comment]
Yeah, before merging to master I was wanting to do a pass of code cleanup.

**Comment by SteveTheTechie** [comment]
Is there a way to start a code review without doing a pull request?

**Comment by mlh758** [comment]
There's nothing wrong with opening a PR and leaving it open for a while.

**Comment by SteveTheTechie** [comment]
ok

**Comment by SteveTheTechie** [comment]
Another thing to consider on this is to review whether the option defaults should be as they are now.   I added a number of new options, but if they were related to existing functionality, I set the default to maintain consistency with existing functionality.   

A good example is `optionsSelectable` ... The default is `true` for this option, but I have wondered if it would be better if it were set to `false`.

**Comment by mlh758** [comment]
`optionsSelectable`?

But yeah, I would be open to reviewing the defaults while version3 is still in pre-release.

**Comment by SteveTheTechie** [comment]
oops... I meant `groupsSelectable`     

Hmmm... where is the autocomplete function that fixes my typos for me... lol

**Comment by mlh758** [comment]
Yeah it's almost tempting to switch selectable and collapsible. I can see people more often wanting to collapse groups than select an entire group. And collapsing a group is less surprising than suddenly having selected all the options in it.

**Comment by mlh758** [comment]
Specific changes will be treated as separate issues.
