### ISSUE TITLE
Make _setOption() take a plain object

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#789]
## I'm submitting a ...
  - bug report
  - [x] feature request
  - question

### What is the current behavior?
Can only dynamically set one option at a time after create

### What is the expected behavior?
Should be able to use a plain object of options to set.

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo
_Common options for demos are [jsfiddle](https://jsfiddle.net/) and [codepen](https://codepen.io)_

### If you are requesting a new or changed feature, please provide a rationale
This approach is supported in several jQuery UI widgets and is pretty simple to implement.  Just use a loop to iterate the plain object.

### Will you submit a corresponding Pull Request to fix the bug or implement the feature?
Yes, if this approach is approved.

### Please tell us about your setup
  
  * Version: 3
  * Browser: Chrome
  * Other frameworks in use:

**Comment by mlh758** [comment]
This is in line with the widget factory behavior.

You can call `$('select').mutliselect({options...})` to set multiple options at once even after creation.

This should be handled through `init` instead: https://api.jqueryui.com/jquery.widget/#method-_init

Alternatively we could implement the `_setOptions` method: https://api.jqueryui.com/jquery.widget/#method-_setOptions

The best case is probably a combination of the two, where `init` just delegates to `setOptions` after creation to set options. Some of the new options also aren't handled in real time after creation like `optionGroupsCollapsable`

**Comment by SteveTheTechie** [comment]
I am a bit confused.  From the API docs, it looks like using a plain object is already available... am I missing something?

**Comment by mlh758** [comment]
https://api.jqueryui.com/jquery.widget/#method-_setOption

It takes a key and a value.

**Comment by SteveTheTechie** [comment]
Yes, but when I read the method descriptions, it looks like _setOptions() is just an already defined iterator for _setOption()... it looks like it already has a default definition.  The method descriptions also say that the option() method calls _setOptions() which in turn calls _setOption().

----
Ok, I just looked at the default definition of _setOptions _in the actual jQuery UI code_:
```
	_setOptions: function( options ) {
		var key;

		for ( key in options ) {
			this._setOption( key, options[ key ] );
		}

		return this;
	},
```

_See what I mean?_   What I am requesting is already possible (I should have actually checked), so I am closing this issue.

**Comment by SteveTheTechie** [comment]
>Some of the new options also aren't handled in real time after creation like optionGroupsCollapsable

They are handled by the default clause in _setOption()--see code excerpt below.  The question is whether anything needs to be down for those beyond setting the option, and whether it makes sense to do so.   For the mentioned `optionGroupsCollapsable`, keep in mind that causes a button to get created in the option headings, so there is a question of whether it makes sense "reshuffle" the HTML after create for that.

``` 
     default:
         this.options[key] = value;
```

**Comment by mlh758** [comment]
> They are handled by the default clause in _setOption()--see code excerpt below.

I get that, they're being set. There just isn't a reaction to them.

> The question is whether anything needs to be done for those beyond setting the option

That would be a per-option thing to evaluate.

> See what I mean? What I am requesting is apparently already possible (I should have actually checked).

I know it's possible, to set multiple options you use init like I said in my initial reply:

> The best case is probably a combination of the two, where init just delegates to setOptions after creation to set options.

But I'm not going to break the API into the widget factory to pass `option` an object for setting multiple options: https://api.jqueryui.com/jquery.widget/#method-option

**Comment by mlh758** [comment]
Revisiting this, it looks like `init` is already behaving the way you would want.

On the basic demo:
`$($("select")[0]).multiselect({buttonWidth: 400, maxSelected: 3, menuWidth: 500});`

That sets (and the widget responds to) all 3 of those options at once and it doesn't pass back through `create` to do it so it isn't a full re-initialization.

**Comment by SteveTheTechie** [comment]
Ok, thanks!  I had not yet had a chance to check that.  

I think we could close this issue then.
