### ISSUE TITLE
onchange event does not fire when unselecting last selected option

### ISSUE THREAD

**Issue by vporton** [ehynds/jquery-ui-multiselect-widget#799]
`onchange` event does not fire when unselecting last selected option (that is when the number of selected options becomes zero).

## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] question

### What is the current behavior?
It does not fire the event.

### What is the expected behavior?
It should fire `onchange`.

### Please tell us about your setup
  
  * Version: MultiSelect UI Widget 1.13
  * Browser: Chromium
  * Other frameworks in use:

**Comment by mlh758** [comment]
Does this issue persist with v2.0.2?

**Comment by vporton** [comment]
Where to get 2.0.2?

**Comment by vporton** [comment]
Found `v2.0.2` tag.

The following code (with v2.0.2)

```
<html>

<head>
<script src="jquery.min.js"></script>

<link rel="stylesheet" href="jquery.multiselect.css">
<script src="jquery.multiselect.min.js"></script>

<body>

<select multiple="multiple" class="select" onchange="alert(11)">
<option>A</option>
<option>B</option>
</select>

<script>
$(".select").multiselect();
</script>
```

with jQuery v3.3.1 fires this error:

```
jquery.multiselect.min.js:21 Uncaught TypeError: $.widget is not a function
    at jquery.multiselect.min.js:21
    at jquery.multiselect.min.js:21
(anonymous)	@	jquery.multiselect.min.js:21
(anonymous)	@	jquery.multiselect.min.js:21
test.html:17 Uncaught TypeError: $(...).multiselect is not a function
    at test.html:17
(anonymous)	@	test.html:17
```

**Comment by vporton** [comment]
Oh, I found it needs jquery-UI library.

Yes, now v2.0.2 works perfectly.

**Comment by mlh758** [comment]
Good, I'll go ahead and close this issue then. Glad upgrading fixed your issue.
