### ISSUE TITLE
Filtered Menu Needs to be Repositioned

### ISSUE THREAD

**Issue by SteveTheTechie** [ehynds/jquery-ui-multiselect-widget#802]
## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] question

### What is the current behavior?
If the menu is opened above the button, then the filter is used to hide some of the menu options, the menu is not re-positioned down to be adjacent to the button.

### What is the expected behavior?
The menu should always be adjacent to the button.

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo
_Common options for demos are [jsfiddle](https://jsfiddle.net/) and [codepen](https://codepen.io)_

Create the widget with a filter.  Locate the button near the bottom of a dialog with "position within" in effect so that the menu is forced to open above the button.   When you enter something in the filter box that hides a menu option, the menu looks "detached" from the button.  This can only be seen if the menu opens above the button.

### Will you submit a corresponding Pull Request to fix the bug or implement the feature?
I could.  Just need to figure out where to call the position function from the filter.

### Please tell us about your setup
  
  * Version: 3
  * Browser: Chrome
  * Other frameworks in use:

**Comment by SteveTheTechie** [comment]
@mlh758 

Frankly, I am wondering the menu height should be adjusted at all when filtering/hiding options... It contributes to additional complexity like this.

**Comment by mlh758** [comment]
It certainly introduces some more edge cases but it also keeps the menu looking neat. People don't seem to like the extra white space left behind when items are filtered out. I imagine similar projects do it for the same reason.

**Comment by SteveTheTechie** [comment]
@mlh758 

Ok, thx.   Are you going to merge the PR?

**Comment by mlh758** [comment]
Yup, was waiting to see your response and got sidetracked with work.
