### ISSUE TITLE
Filter dosn't work

### ISSUE THREAD

**Issue by fglueck** [ehynds/jquery-ui-multiselect-widget#809]
## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] question

### What is the current behavior?
If you type anything into the filter inputfield it would not be filtered, the input is ignored.

### What is the expected behavior?
Normaly it shows only the listitems with the given text.

### Please tell us about your setup

  * Version: 3.0.0 (release) and current source on github
  * Browser: FF 60
  * Other frameworks in use: jquery, dhtmlx, ..

**Comment by mlh758** [comment]
Do you have the css file included from https://github.com/ehynds/jquery-ui-multiselect-widget/blob/version3/css/jquery.multiselect.filter.css?

**Comment by SteveTheTechie** [comment]
@fglueck We need to be able to reproduce the problem you are seeing to be able to resolve it...

Can you provide a code pen, gist, jsfiddle, or steps to reproduce?  That would really help.

CC: @mlh758

**Comment by fglueck** [comment]
Sure, here my code: 
https://codepen.io/ugnaz/pen/dmaRqx

**Comment by mlh758** [comment]
The css is necessary for the filtering part of the widget to work.

**Comment by fglueck** [comment]
Yes, so you can check, follow css are used:
https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css
https://cdn.rawgit.com/ehynds/jquery-ui-multiselect-widget/version3/css/jquery.multiselect.css
https://cdn.rawgit.com/ehynds/jquery-ui-multiselect-widget/version3/css/jquery.multiselect.filtercss

**Comment by SteveTheTechie** [comment]
One thing I see right off is that you are pulling the src from the master branch rather than the version 3 branch.   Version three is still in pre-release, so it is not yet merged to the master branch.

**Comment by mlh758** [comment]
https://cdn.rawgit.com/ehynds/jquery-ui-multiselect-widget/version3/css/jquery.multiselect.filtercss is a 404

Changing the end to .filter.css yields the correct css files which contains the class needed to make the filter work `.ui-multiselect-excluded {display: none}`

**Comment by mlh758** [comment]
I also see a JavaScript error in the console when it's trying to load the filter. If I delete your overrides and change the JavaScript on that right panel to just `$('#x').multiselect().multiselectfilter();` it loads up and the filter works. That remains true if I change the cdn links to version3 instead of master.

**Comment by mlh758** [comment]
I found the issue. You're calling `multiselectfilter` on the closing parenthesis of the `$(function...` block that you opened at the beginning instead of on the closing of the `multiselect` call. If I move the call it works and begins filtering.

**Comment by fglueck** [comment]
sorry, for that!
