### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by mlh758** [ehynds/jquery-ui-multiselect-widget#812]
## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] question

### What is the current behavior?
This only appears to be an issue with the filter present.

When navigating the open menu with the keyboard, going to the top of the menu will cycle you to the bottom but the bottom of the menu doesn't seem to cycle you to the top anymore. Also, if you navigate to the top option the option group wrapping it does not scroll into view like it does when there is no filter present.

### What is the expected behavior?
Hitting the top and bottom of the menu while navigating with the keyboard should be consistent. Both should cycle.

Navigating to the top option should scroll to expose its option group.

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo
_Common options for demos are [jsfiddle](https://jsfiddle.net/) and [codepen](https://codepen.io)_
Open the filter demo and use the keyboard to traverse up and down the menu in Chrome.

### Please tell us about your setup
  
  * Version: 3
  * Browser: Chrome
  * Other frameworks in use:

**Comment by SteveTheTechie** [comment]
@mlh758  You may want to close this issue now....  Did not auto-close.
