### ISSUE TITLE
Demo pages

### ISSUE THREAD

**Issue by yairEO** [ehynds/jquery-ui-multiselect-widget#816]
It would be good to add a Github demo page instead of a person needing to actually download the repo in order to see the demos...

https://pages.github.com

it can take a second since you already have the demo file `index.html` prepared.
just need to put all the demos in on single file and that's it.

**Comment by mlh758** [comment]
I don't have admin access to this repo to set up github pages. I would need to set up my own website instead.

Or I guess I could use my own fork of the repo and link to it from the readme here...

**Comment by ehynds** [comment]
@mlh758 if you create a `docs/` folder i can turn on github pages if you want. Also looking to see if I can give you admin permissions on this repo. Amazing work by the way, thank you so much.

**Comment by mlh758** [comment]
Awesome, thank you!

**Comment by mlh758** [comment]
I pushed up a docs folder with a blank markdown file in it.

**Comment by mlh758** [comment]
Excellent. Now to hopefully not break things while I figure out how to use it. I'm thinking I should just be able to move the demos over to the docs folder since Pages should use that index file.

**Comment by mlh758** [comment]
Just a heads up, the pages are up. They're just a bit broken since the script tags are still pulling from relative paths. I'll keep working on it.

**Comment by mlh758** [comment]
@ehynds I pushed up a new version of the docs folder last night using [jekyll](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/) to build and test my changes locally. My understanding was that this should have just built and looked the same in GitHub pages since it uses jekyll too. Something seems to have gone wrong but I can't see the build errors.

Can you send me the build errors or give me access to the repo settings?

**Comment by ehynds** [comment]
I don't think github supports giving admin access to individual users, or at least I can't find where the setting is. The error is this though:

``` Your site is having problems building: A file was included in src/index.html that is a symlink or does not exist in your _includes directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink/.
```

**Comment by mlh758** [comment]
I think you would have to [convert yourself](https://help.github.com/articles/creating-a-new-organization-from-scratch/) to an organization and then you could add me to it and give me owner permissions.

As for this error, it's probably how I laid the folders out. Jekyll was happy with it locally, I wonder if GitHub Pages ignores that part of the config file. I wish I didn't have to push to master to find out :(

**Comment by mlh758** [comment]
Sorry about the delay, but this is now working at http://ehynds.github.io/jquery-ui-multiselect-widget/

**Comment by ltdeta** [comment]
Can you please enter a link to the demo page on the main page?
I only found the link because I searched the issues

**Comment by mlh758** [comment]
Yes I can, I meant to add it to the readme and clearly forgot. I'll have that done today.

**Comment by mlh758** [comment]
I've updated it on the readme.
