### ISSUE TITLE
dropdown is appearing above and getting cutoff

### ISSUE THREAD

**Issue by edwardselig** [ehynds/jquery-ui-multiselect-widget#819]
## I'm submitting a ...
  - [ x] bug report
  - [ ] feature request
  - [ ] question

### What is the current behavior?
dropdown options are appearing above the select line in google chrome

### What is the expected behavior?
I want the options to be under the select line

<img width="416" alt="screen shot 2018-05-18 at 4 50 44 pm" src="https://user-images.githubusercontent.com/13319212/40257296-b65ea5d6-5abb-11e8-87e2-c3d36fa5ebdf.png">

**Comment by mlh758** [comment]
Can you provide a little more context?

Do you have any other frameworks in use? What version of the widget are you using?

What does your call to `multiselect` look like?

**Comment by psyafter** [comment]
@edwardselig it's ok.
When no enough space for menu at bottom, so it opened above.
You can adjust it in position object, read about collision http://api.jqueryui.com/position/

**Comment by edwardselig** [comment]
I have no other frameworks in use.  I'm using jquery-3.3.1.min.js, jqueryui/1.12, MultiSelect UI Widget 2.0.1.  This is my call to multiselect:

$("#streamTo").multiselect({
					  noneSelectedText: 'Select Stream(s)...',
					  selectedText: "# of # selected",
					  selectedList: 3,
					  height:400,
					  position:{
							my: 'center top',
							at: 'center bottom',
  						  collision:"flip"
						}
				   }).multiselectfilter();

I also tried without the position but nothing changed.  Also one of the big problems with it isn't just that it's opening upward, but that it gets cut off by the URL bar in my browser.  Also the code works on safari but not google chrome.

**Comment by psyafter** [comment]
ok, there is a bug that prevent using "collision" property of position object.

See the bug fix here: https://github.com/ehynds/jquery-ui-multiselect-widget/pull/820/commits/5d97ca4a9f5b2d13ce3fcd7f1da86bc886bbf520

Your code should be collision='none':

`$("#streamTo").multiselect({
noneSelectedText: 'Select Stream(s)...',
selectedText: "# of # selected",
selectedList: 3,
height:400,
position:{
my: 'center top',
at: 'center bottom',
**collision:"none"**
}
}).multiselectfilter();`

**Comment by edwardselig** [comment]
Alright it turns out all I had to do was reduce the height to 200. We were upgrading from an older version and before setting the height as 400 worked.  Now when I scroll down it keeps scrolling back up to the first element in the drop-down, do you know why this would happen?

**Comment by psyafter** [comment]
can you post a sample here https://jsfiddle.net/?

**Comment by mlh758** [comment]
Is it scrolling up each time you open the widget? Or is it scrolling on you while you have it open?

**Comment by edwardselig** [comment]
it scrolls up when I have it open, I scroll down a tiny bit and about a second goes by and it goes back to the top

**Comment by mlh758** [comment]
Sounds good.
