### ISSUE TITLE
Pre populate selected filters

### ISSUE THREAD

**Issue by sreeramjayan** [ehynds/jquery-ui-multiselect-widget#821]
### What is the current behavior?
We have a modal that displays multiple multi select filters. When a person selects filters, we store the filters in the database so people don't have to select the options again. Once we retrieve the saved filters, we initialize the filters with the previously selected options. We update the options tag with the selected filters and then refresh the multiselect element. 

But when we try to determine the checked elements using `multiselect("getChecked")` no results are returned. 

Is there any way I can programmatically set certain options as checked and the state gets updated to show that the elements are checked?

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo
_Common options for demos are [jsfiddle](https://jsfiddle.net/) and [codepen](https://codepen.io)_

### Please tell us about your setup
  
  * Version:
  * Browser:
  * Other frameworks in use:

**Comment by mlh758** [comment]
In case someone else comes here with the same question: https://github.com/ehynds/jquery-ui-multiselect-widget/blob/master/docs/preselected.html

That demo shows how this can be done.
