### ISSUE TITLE
AutoReset filter option regression (v3)

### ISSUE THREAD

**Issue by Celos** [ehynds/jquery-ui-multiselect-widget#822]
### What is the current behavior?
Setting the `autoReset` filter option to true causes the following behaviour: opening a multiselect dropdown once and then reopening it, the list of items disappears until you enter something into the filter field. It seems that the height of the list is set to 0px;

### What is the expected behavior?
Reopening a multiselect dropdown should have an empty filter input field and the full list of selectable options visible.

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo
Forked jsFiddle from some other V3 issue: https://jsfiddle.net/gw3dxhue/
Also reproduces when you add that option to the filter sample.

### Please tell us about your setup
  
  * Version: 3

**Comment by mlh758** [comment]
Thank you for providing steps to reproduce.

**Comment by mlh758** [comment]
@Celos Take a look at #823 it should fix your issue. I tested it against the filter demo. I'll merge once it looks good to you.

**Comment by Celos** [comment]
@mlh758 Looks good.

**Comment by mlh758** [comment]
Merged the fix.
