### ISSUE TITLE
Responsive button width

### ISSUE THREAD

**Issue by Celos** [ehynds/jquery-ui-multiselect-widget#827]
### What is the current behavior?

The width of the multiselect button is calculated during it's initial rendering and then left unchanged when the window is resized.

### What is the expected behavior?

The button is resized when the underlying select width changes.

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo
https://jsfiddle.net/xpvt214o/562336/
Resize the browser after clicking run.

### If you are requesting a new or changed feature, please provide a rationale
It seems that a fairly common use case is changing the window size after initial load, possibly due to features like Windows snap. This means that already rendered multiselect widgets tend to break the layout of the page.

### Please tell us about your setup
  
  * Version: 3

**Comment by mlh758** [comment]
Using a percentage for the button width should get you some of this behavior. There's not really any css in this widget currently that would satisfy responsive design requirements. There's no media selectors to change behavior for example.

The default button width is just 225px and can be overridden with the `buttonWidth` option.

**Comment by mlh758** [comment]
Closing since you can change the buttonWidth to a percentage or use a callback to resize. I don't think the widget itself is in a position to handle that in general sense for its consumers.

If you disagree I can reopen and we can discuss.
