### ISSUE TITLE
Missing methods to check/uncheck a single option

### ISSUE THREAD

**Issue by doublej74** [ehynds/jquery-ui-multiselect-widget#830]
I work with an app displaying the values in the multiselect list in two different ways (one in the select list) and the other way is a graphical way. I need to keep the status (check/unchecked) in both displays in sync.

Therefor I'm missing methods to check/uncheck of a single option in the multiselect. 
(uncheckall and checkall exist)

**Comment by mlh758** [comment]
https://github.com/ehynds/jquery-ui-multiselect-widget/wiki#manually-check-or-uncheck-a-checkbox

Does this help?
