### ISSUE TITLE
With Big Data Set - Widget Getting Stuck 

### ISSUE THREAD

**Issue by erangaapp** [ehynds/jquery-ui-multiselect-widget#832]
### Widget getting stuck with more than 10,000 options.

Is it possible to use this widget with big dataset + async

  * Version:2.0.1
  * Browser:Any
  * Other frameworks in use:

**Comment by mlh758** [comment]
Version 3 offers a substantial performance boost, you may be able to get by with that.

The widget doesn't directly support async loads, but you can use Ajax to load the underlying `select` tag up with options after the page loads and then use the [refresh](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Methods) method to build out the widget.
