### ISSUE TITLE
For some reason, the dropdown menu gets placed in a wrong position

### ISSUE THREAD

**Issue by rasben** [ehynds/jquery-ui-multiselect-widget#837]
Im 99% sure that this is not an actual issue with the library, but i hope someone here recognises my issues and can nudge me in the right direction

### What is the current behavior?
- I init the multiselect widget and it looks great
- I click on the element
- The dropdown menu gets placed totally randomly on my page

<img width="749" alt="Screenshot 2019-03-11 at 16 18 19" src="https://user-images.githubusercontent.com/12376583/54150862-cfb3c300-4439-11e9-8adc-eb6cb027b6fd.png">

### What is the expected behavior?
- I would expect the dropdown to appear below the input

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo
- I've tried so hard to reproduce it in a codepen, but it just doesnt work
- I *think* its to do with margins/paddings on the page.
- When i disable some of my CSS, the element works fine

### Please tell us about your setup
  
  * Version: v2 and v3 
  * Browser: Chrome
  * Other frameworks in use: Drupal

**Comment by mlh758** [comment]
If you call the `refresh` method on it, does it end up in the right place?

**Comment by rasben** [comment]
@mlh758 you mean like this?

```
$("#the_id_of_my_original_select").multiselect("refresh")
```

i tried to run that in my chrome console:

<img width="291" alt="Screenshot 2019-03-11 at 23 11 45" src="https://user-images.githubusercontent.com/12376583/54161637-0ea24280-4453-11e9-9786-47172233d77b.png">


and i still have the same issue :(

**Comment by mlh758** [comment]
I wrongly assumed that `refresh` would also reset the position of the widget.

`$("#the_id_of_my_original_select").multiselect("position")` should actually impact the position.

I'm wondering if something else on the page is interfering with where the widget is placing the menu. If resetting the position manually like this helps we at least know where to start looking.

**Comment by rasben** [comment]
same result with .multiselect("position")

I know for sure that it's some CSS on the page that's causing troubles, but I really cannot figure out what part of it that causes the trouble

I was hoping someone had run into the same problem and could say "Oh, its cause you used float on the parent" or something :(

**Comment by rasben** [comment]
Hmm.. Ok after digging a bit, i found the following "solution":
- the Drupal admin adds a sticky toolbar header. To leave space for that, It also adds a padding-top value on the `<body>`.
- If I remove the padding and use `multiselect('destroy')` & `multiselect()` on my element in the chrome dev tools, it looks correct.

I've been able to recreate something similar happening due to my custom header styling - which is not sticky, just a regular HTML header that pushes the rest of the elements on the page down

How strange..

any ideas @mlh758 ? (and thanks for your time!!)

**Comment by rasben** [comment]
I dont know if its connected, but I see the same (kind of) issue on the demo page:
https://ehynds.github.io/jquery-ui-multiselect-widget/#animations

**Comment by mlh758** [comment]
Yeah it does look like the menu is attaching itself to the other select. For some reason I thought that had been fixed a while back but it's been about a year since I've looked at any of this code.

**Comment by rasben** [comment]
Well, I found solution that works for me..
@mlh758 https://github.com/ehynds/jquery-ui-multiselect-widget/pull/838

**Comment by mlh758** [comment]
I looked a little more into why position might be giving the wrong value. According to the [docs](https://api.jquery.com/position/):
>The .position() method allows us to retrieve the current position of an element (specifically its margin box) relative to the offset parent (specifically its padding box, which excludes margins and borders). Contrast this with .offset(), which retrieves the current position relative to the document.

I think this might have to do with where the menu is getting adding to the dom. Can you try using the `appendTo` option to ensure the menu gets added to the container the button is in?

**Comment by rasben** [comment]
Well, i tried to pass the wrapper element to appendTo as '.form-item-area' but then i get this error:

<img width="532" alt="Screenshot 2019-03-14 at 11 20 23" src="https://user-images.githubusercontent.com/12376583/54349291-3a881880-464b-11e9-89ab-23ac874558d0.png">

**Comment by mlh758** [comment]
I think in v2 of the widget you need to pass a jquery object to appendTo

**Comment by rasben** [comment]
In that case, this line should probably be updated:
https://github.com/ehynds/jquery-ui-multiselect-widget/blob/version3/src/jquery.multiselect.js#L178

:D

**Comment by mlh758** [comment]
That line is in the v3 code

**Comment by rasben** [comment]
Oh, but the error im getting up there is from me using V3 code

**Comment by mlh758** [comment]
![image](https://user-images.githubusercontent.com/4331955/54378277-f7cb3e00-4654-11e9-8020-b7d86af5e664.png)
That looks like v2.0.1

**Comment by rasben** [comment]
Ah, its because i forgot to clear the cache in Drupal, where i previously used 2.0.1 - but it was the correct v3 that was being loaded in as you saw :)

<img width="470" alt="Screenshot 2019-03-14 at 18 38 56" src="https://user-images.githubusercontent.com/12376583/54378907-a0df5c00-4688-11e9-8ab1-384bfd5ad192.png">

In case you're curious, I'm trying to introduce this module to a contrib Drupal menu - thats also why you're getting so much spam from me these days :D

https://www.drupal.org/project/better_exposed_filters/issues/3039760

**Comment by mlh758** [comment]
It's certainly nice to see the widget getting some use out in the wild. Is that length error what happens when you use `appendTo` with a jQuery object?

**Comment by rasben** [comment]
The length error is unrelated, thats why i just cropped the image :D but, isnt the issue here:

<img width="471" alt="Screenshot 2019-03-14 at 18 44 34" src="https://user-images.githubusercontent.com/12376583/54379201-3975dc00-4689-11e9-9d62-3b68901830e7.png">

from what i can see, theres no this.document available?

**Comment by rasben** [comment]
ah, now i see this:

>     * NOTE:  this.element and this.document are jQuery objects per the jQuery UI widget API.

could it be perhaps that Drupal is using a too old version of jQuery UI?
>  version: &jquery_ui_version 1.12.1

**Comment by mlh758** [comment]
That's what has been throwing me off. 1.12 is pretty new, this widget's requirements are 1.11 and up.

**Comment by rasben** [comment]
Hmm.. historically, jQuery has been super far behind in Drupal. I can see that I'm using v3.2.1, but i guess thats not too bad either.

**Comment by mlh758** [comment]
I can reproduce this error in the demo pages as well. Presumably this worked at some point but clearly the assumption in that comment is now wrong.

**Comment by rasben** [comment]
Isnt this a simple fix @mlh758 ?

https://github.com/ehynds/jquery-ui-multiselect-widget/pull/843/files

**Comment by mlh758** [comment]
Yeah it should be a simple fix.

**Comment by rasben** [comment]
with that change ^ in pull/843, the appendTo works as expected, but i still have a variant of the same issue..

I can however fix that by adding this CSS to override some of the inline style (which probably shouldnt be added when using appendTo?)

<img width="582" alt="Screenshot 2019-03-14 at 19 10 16" src="https://user-images.githubusercontent.com/12376583/54380955-e867e700-468c-11e9-8ea4-0263a4a791f9.png">

these are the overrides I have to use:
<img width="185" alt="Screenshot 2019-03-14 at 19 12 01" src="https://user-images.githubusercontent.com/12376583/54381048-1a794900-468d-11e9-8a03-f77ec2673a4d.png">


For it to work, I also have to get rid of some of my `overflow: hidden;`s in my code, but thats not really this librarys fault :)

It does mean though that practically I personally cant use the appendTo solution, because those `overflow: hidden`'s are necessary for me - and then it'll look like this sadly:

<img width="500" alt="Screenshot 2019-03-14 at 19 14 24" src="https://user-images.githubusercontent.com/12376583/54381172-65935c00-468d-11e9-8748-5be33696ddfd.png">

**Comment by mlh758** [comment]
Is there a `.ui-front` somewhere on your page already?

**Comment by rasben** [comment]
Nope, and not after loading the module either (?)

**Comment by rasben** [comment]
But everything is peaches with #838 and without `appendTo`

<img width="508" alt="Screenshot 2019-03-14 at 19 25 44" src="https://user-images.githubusercontent.com/12376583/54381832-00406a80-468f-11e9-97af-762988451e74.png">

**Comment by mlh758** [comment]
Yeah, I want to test how the widget behaves in a modal before merging that PR. That's something that's given me problems before and I think offset/position could have an impact there.

**Comment by rasben** [comment]
That makes sense :) 
If you find out that #838 is causing trouble you can just close that + this issue - If im the only one having issues, I'll just stick with the patch Im using now

**Comment by mlh758** [comment]
Closed with #838
