### ISSUE TITLE
Is there any way to replace the "selected" text with chosen options?

### ISSUE THREAD

**Issue by rasben** [ehynds/jquery-ui-multiselect-widget#839]
Like this:

<img width="237" alt="Screenshot 2019-03-13 at 15 13 22" src="https://user-images.githubusercontent.com/12376583/54285700-c2feae80-45a2-11e9-8609-01bbbc20e7ea.png">

**Comment by mlh758** [comment]
Does the [selected list](https://ehynds.github.io/jquery-ui-multiselect-widget/#selectedlist) option do what you need?

**Comment by rasben** [comment]
God, how did I miss that, I've been staring at the demo page a billion times :D

Sorry - yes that does exactly what i want :)
Thanks!!
