### ISSUE TITLE
appendTo not working with selector string

### ISSUE THREAD

**Issue by mlh758** [ehynds/jquery-ui-multiselect-widget#842]
### What is the current behavior?
Using `appendTo` with a selector raises an exception
`this.document.find` is not a function

### What is the expected behavior?
The widget can use a selector to append to an element

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo

Call `appendTo` with a selector instead of a node or jQuery object

### Will you submit a corresponding Pull Request to fix the bug or implement the feature?
Yes

### Please tell us about your setup
  
  * Version: v3.0.0
  * Browser: Chrome
  * Other frameworks in use: None

**Comment by mlh758** [comment]
Fixed with #843

**Comment by rasben** [comment]
For historical reasons, more info here:
https://github.com/ehynds/jquery-ui-multiselect-widget/issues/837
