### ISSUE TITLE
Where's the documentation?

### ISSUE THREAD

**Issue by vincentwansink** [ehynds/jquery-ui-multiselect-widget#844]
I can't find any documentation for the options to this control.  There's a demo page from which I can glean some of the options, though it requires some hunting, but it would be nice if there was a list of options somewhere.

**Comment by mlh758** [comment]
Would something like a [wiki](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki) on the [GitHub](https://github.com/ehynds/jquery-ui-multiselect-widget/issues/844) page help?

**Comment by vincentwansink** [comment]
Thanks.  Found it.  Not too familiar with GitHub.
