### ISSUE TITLE
Label count after refresh incorrect when using filter

### ISSUE THREAD

**Issue by mtgtnt** [ehynds/jquery-ui-multiselect-widget#851]
### What is the current behavior?
Incorrect length count after refresh

### What is the expected behavior?
Correct length count after refresh

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo
refresh any multiselect with filter and start checking, the count of options is 1 too many

Line 594:
      this.$labels = this.$menu.find('label:not(.ui-multiselect-filter-label)');

should be one of the following:
      this.$labels = this.$menu.find('ul label');
      this.$labels = this.$menu.find('label:not(.ui-multiselect-filter)');

**Comment by mlh758** [comment]
#850 fixed basically this exact issue. The filter plugin adds that class to the filter label. Are you on the latest code?

I fired up the examples in my local, went to the filter demo, got 8 labels, refreshed, and still had 8 labels.

**Comment by mtgtnt** [comment]
I grabbed the code before posting to make sure. I see .ui-multiselect-filter not .ui-multiselect-filter-label

**Comment by mtgtnt** [comment]
I have triple checked now. It is getting the .ui-multiselect-filter-label on the filter label, but still counting it.

**Comment by mtgtnt** [comment]
sorry.. it is now right. i still had the fix i had. put it back to yours and it works :( *hangs head*

it looks like the filter js was not getting updated to browser even with a cache clear... I hate ff some days.
