### ISSUE TITLE
Undefined function _parse2px() when rendering page

### ISSUE THREAD

**Issue by cigamit** [ehynds/jquery-ui-multiselect-widget#852]
Getting these warnings in the console.  It looks like someone forget to include this function from some merge:

TypeError: this.instance._parse2px is not a function (jquery.multiselect.filter.js:97:40).  Ive found the function in jquery.multiselect.js, but is named incorrectly in the filter file.

This is found in latest develop.

**Comment by mlh758** [comment]
I'm not seeing these errors in the console when I load the page. I opened the test suite in my browser (index.html under tests) and there were no warnings like that. I also don't see the warnings when I fire up the docs (`bundle exec jekyll serve` under the docs folder) and navigate to the filter demo.

**Comment by mlh758** [comment]
I just wanted to follow up. Was there a specific situation you saw these errors happening in? I'm not encountering them in the test suite or demos when filtering is active.

**Comment by cigamit** [comment]
$('#object').multiselect().multiselectfilter({ width: somevalue });

It's the width attribute.  When you include the width attribute, it will call the ._parse2px() function in jquery.multiselect.js, which is of course named .parse2px() and not ._parse2px(), which results in the error.

**Comment by mlh758** [comment]
Thank you, now I can get a failing unit test together as well.

**Comment by mlh758** [comment]
Fixed this in  10b44a4
