### ISSUE TITLE
Add new features multipleRow boolean, multipleRowWidth, and minWidth features

### ISSUE THREAD

**Issue by cigamit** [ehynds/jquery-ui-multiselect-widget#854]
The current jQuery Multiselect does not allow for multiple row dropdowns.  This enhancement, when completed will allow the jQuery Multiselect plugin to present dropdowns with multiple rows and columns.

### What is the expected behavior?
When, multipleRow boolean is set, then multipleRowWidth will be looked for an the Multiselect will allow the multiselect to cascade to multiple rows upto the width defined in the option.

Additionally, add the minWidth option to specify a minimum width for the selectbox.

### If you are requesting a new or changed feature, please provide a rationale
If you review tools like Linux and Windows task schedulers, they provide a Multiselect interface that allows rows and columns.  Say for example, month day, or day of month.  Just emulate this in jQuery Multiselect.

### Will you submit a corresponding Pull Request to fix the bug or implement the feature?
Yes.  This was completed in Cacti 1.x almost two years ago, we have simply failed to submit a pull request to merge the feature.

### Example screen shots

![MultiSelect1](https://user-images.githubusercontent.com/957322/61185420-03d50580-a61f-11e9-87b2-ce1d6080ef08.PNG)
![MultiSelect2](https://user-images.githubusercontent.com/957322/61185422-06cff600-a61f-11e9-9419-d878ce0d3a45.PNG)
![MultiSelect3](https://user-images.githubusercontent.com/957322/61185423-09cae680-a61f-11e9-91fa-dac98f1b8285.PNG)
![MultiSelect4](https://user-images.githubusercontent.com/957322/61185424-0c2d4080-a61f-11e9-935e-c608cc51aeff.PNG)

**Comment by cigamit** [comment]
Just gave this some thought, I guess it should be multipleColumn and not multipleRow.  Took me a few years to figure that out.

**Comment by mlh758** [comment]
There is already a column view option in the widget. `groupColumns: true` will display option groups as columns. I see that this is a little different, in that it allows putting the checkboxes inline with each other up to a maximum width but I wonder if that could be accomplished by overriding the default styles instead.

There is already a way to set minimum widths to the button and menu. `menuWidth: '>= 50px'` for example.

**Comment by cigamit** [comment]
Well, that's awesome!!!

**Comment by cigamit** [comment]
Is there a demo?  All I can see of this option is the ability to set a class attribute.  Is it functional?

**Comment by mlh758** [comment]
The minWidth and groupColumns options are documented in the [wiki](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Options). The variation on the columns you're talking about doesn't have a demo anywhere.

The `classes` option adds css classes to the button and menu, although there are other ways to override the css as well by manually adding the classes during one of the callbacks or just globally in your own css. You can also add the css classes on the underlying options and those will get copied to the `li` tag that represents the item in the list. I was thinking you might be able to override the list items to be inline block [like this](https://jsfiddle.net/vme7L3tb/) but I haven't tried doing it on this widget.

**Comment by cigamit** [comment]
Yea, I was reviewing the source code of the the widget, and found that the groupColumns option is only valid for the optiongroup tagName.  So, I think I might be able to force the class onto the &lt;li&gt; tags.  If that does not work, I guess I'll submit a pull request.

**Comment by cigamit** [comment]
I added the changes to my other pull request which changes the function name in the filter file from _parse2px to parse2px.

**Comment by mlh758** [comment]
I'd be a little hesitant to introduce another path for visual layout into the library which is why I'm hoping you can accomplish it with css.
