### ISSUE TITLE
jquery-ui-multiselect-widget does not work when jQuery upgraded to 3.5.1

### ISSUE THREAD

**Issue by rlk-27** [ehynds/jquery-ui-multiselect-widget#868]
### What is the current behavior?
Multiselect  does not work jQuery upgraded to 3.5.1

### What is the expected behavior?

Multiselect  should work with jQuery upgraded to 3.5.1

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo
In, jquery-ui-multiselect-widget-3.0.0/tests/unit/index.htm  update the jquery version to 3.5.1 CDN link as shown below
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

reload jquery-ui-multiselect-widget-3.0.0/tests/unit/index.htm,  see it fail.

### Please tell us about your setup
  
  * Version: V3 jquery-ui-multiselect-widget from github
  * Browser: firefox/chrome
  * Other frameworks in use:

**Comment by rlk-27** [comment]
issue was due to jquery .val function changes in 3.5.1

**Comment by mlh758** [comment]
You closed the issue, does that mean it will work with 3.5.1 after all or will there have to be a code change in this library to support it?
