### ISSUE TITLE
clear filter text on refresh

### ISSUE THREAD

**Issue by jlcox** [ehynds/jquery-ui-multiselect-widget#87]
I'm using the multiselect as the child select in a related select setup...change the master value, the multiselect is repopulated with new children. All works well, except that if the user has entered text in the filter (via plugin), it remains in place after the refresh and is an active filter on the new data. How can I clear the filter on a refresh?

**Comment by mlh758** [comment]
This is pretty old, but here's a snippet you could use:

`$("select").multiselectfilter("instance").input.val("").trigger("input", "")`
