### ISSUE TITLE
jQuery unsupported pseudo: data when checking if the widget is in use

### ISSUE THREAD

**Issue by vanarebane** [ehynds/jquery-ui-multiselect-widget#870]
### What is the current behavior?
jquery.js:1560 Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: data

### What is the expected behavior?
not to have a error :)

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo

Problem is in `src/jquery.multiselect.js` on line 621

`      // If the filter widget is in use, then also update its cache.`
`      if ( this.element.is(':data("ech-multiselectfilter")') ) {`
`            this.element.data('ech-multiselectfilter').updateCache(true);`
`      }`

Demonstration of the problem with solution is here:
https://jsfiddle.net/pgem28vy/1/

### Will you submit a corresponding Pull Request to fix the bug or implement the feature?
If the solution is acceptable, I can make a pull

### Please tell us about your setup
 
  * Version: jQuery UI Multiselect Widget 3.0.0
  * Browser: Chrome 89
  * Other frameworks in use: jQuery 3.6.0, jQuery UI 1.12.1,

**Comment by mlh758** [comment]
The data selector should be brought in by jQuery UI. Has something changed with 1.12? I haven't used this library in quite a while.

**Comment by mlh758** [comment]
I added jQuery UI to your fiddle and the error went away, although it still didn't log anything.

**Comment by mlh758** [comment]
I'm closing this assuming there was something up with your jQuery UI dependency. I'll reopen if that ends up not being the case.

**Comment by maksimus256** [comment]
same problem, thanks for the solution
