### ISSUE TITLE
collapse button should be type="button"

### ISSUE THREAD

**Issue by mokraemer** [ehynds/jquery-ui-multiselect-widget#872]
collapse buttons are created as 
`<button title="Collapse" class="ui-state-default ui-corner-all ui-multiselect-collapser"><span class="ui-icon ui-icon-minusthick"></span></button>`

but if the attribute type="button" is missing, the form is submitted immediately.

Patch, change:
```
var $collapseButton = !!self.options.groupsCollapsable
                                 ? $( document.createElement('button') )
                                    .attr({'title': self.linkInfo.collapse.title})
                                    .addClass('ui-state-default ui-corner-all ui-multiselect-collapser')
                                    .html(self.linkInfo.collapse.icon)
                                 : null;
```
to
```
var $collapseButton = !!self.options.groupsCollapsable
                                 ? $( document.createElement('button') )
                                    .attr({'title': self.linkInfo.collapse.title,'type': 'button',})
                                    .addClass('ui-state-default ui-corner-all ui-multiselect-collapser')
                                    .html(self.linkInfo.collapse.icon)
                                 : null;
```

**Comment by mlh758** [comment]
Seems like it would be a straightforward PR if you want to submit one.

**Comment by mokraemer** [comment]
nope. I'm not familiar with git/github.

**Comment by mlh758** [comment]
![image](https://user-images.githubusercontent.com/4331955/125638564-7cc83e59-15fb-4979-a12b-8e188bbce5ca.png)

**Comment by mokraemer** [comment]
yeah, 13, because 12 didn't work. I'm not familiar with git - I'm using mercurial all day. With git I always end up with a broken archive.
Do we really need to discuss this? I've given a "patch" and opened a bug report.

Full patch is:
`diff -Naur jquery_multiselect-old.js jquery_multiselect.js
--- jquery_multiselect-old.js	2021-07-14 18:34:49.994292271 +0200
+++ jquery_multiselect.js	2021-07-14 15:58:38.038178751 +0200
@@ -512,7 +512,7 @@
           // Build the list section for this optgroup, complete w/ option inputs...
           var $collapseButton = !!self.options.groupsCollapsable
                                  ? $( document.createElement('button') )
-                                    .attr({'title': self.linkInfo.collapse.title})
+                                    .attr({'title': self.linkInfo.collapse.title,'type': 'button'})
                                     .addClass('ui-state-default ui-corner-all ui-multiselect-collapser')
                                     .html(self.linkInfo.collapse.icon)
                                  : null;
`

**Comment by mlh758** [comment]
A PR would get your issue resolved faster, didn't seem unreasonable given that you already have the change. I don't use this project or jQuery anymore so it'll take me longer to get everything set back up and test the changes on my own.

Since a PR is off the table I'll try and get around to this in the next couple of days when I have time.

**Comment by mokraemer** [comment]
thank you!
