### ISSUE TITLE
Allow different button / menu widths

### ISSUE THREAD

**Issue by ElteHupkes** [ehynds/jquery-ui-multiselect-widget#95]
When you specify a width for a normal browser (single) select box it truncates the contents of the first item, but when you start selecting an item it shows all items in full width. I would like to see the same behavior on this multiselect widget (which I love, by the way), getting the option to have small widget buttons with large menus.

For the time being I just added "return false;" to the _setMenuWidth function, giving my menu an auto width which triggers the desired behavior. This because I'm not sure how to make this an option in a clean way (it could be more flexible than just this).

**Comment by mlh758** [comment]
I'm sure this is well beyond the scope of you caring anymore, but a [menuWidth option](https://github.com/ehynds/jquery-ui-multiselect-widget/wiki/Options) has been added that adds the desired behavior.
